### ISSUE TITLE
jatm 1.8-1.0

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#1]
Crashes client

crash report: http://paste.ee/p/ZHDmU
fml client latest: https://paste.ee/p/I2lqZ

**Comment by kreezxil** [comment]
it says something about not being able to cast models

**Comment by Dyonovan** [comment]
Ok it only happens with liteloader installed. I will have to look into it.

As to the not being able to cast models, thats ok and expected as we are rendering things different.

**Comment by Dyonovan** [comment]
Talking to Liteloader mods to try and fix issue.

**Comment by Dyonovan** [comment]
Ok @pauljoda fixed the issue with liteloader it looks like. Going to close the issue. Re open it if you see it again.
