### ISSUE TITLE
Miner causes sever lag?

### ISSUE THREAD

**Issue by MoonCutter2B** [TeamBR-Modding/NeoTech#10]
In my world I get sever lag and fps drops a lot when the Miner is running.
If I move far away from the Miner or push tge "stop" button in the Miner the fps returns to normal and the lag is gone.

**Comment by MoonCutter2B** [comment]
Ok, it worse than that.
I'v tried the same new world with and without NeoTech installed and as soon as it is installed the fps drops and the chunk generation/chunk loading gets very laggy.
I haven't even cretaed any items, just installed it.
Suggestion: check comminukation between client and server.

Same problem as #6?

**Comment by MoonCutter2B** [comment]
After reading the code I wonder if there shouldn't be some "clientonly" and "serveronly" annotations or is that handled another way?

**Comment by Dyonovan** [comment]
Should be fixed in rewrite. Initial release later today. Miner won't be in initial release
