### ISSUE TITLE
Not enough power to complete an operation causes lag

### ISSUE THREAD

**Issue by rob-ed** [TeamBR-Modding/NeoTech#105]
Scenario: Furnace generator with processor upgrade connected to basic RF storage, and an electric cursher and furnace connected to that.

One machine works fine while the other repeatedly attempts to start a process and fails due to lack of power. Seems to do this every tick and causes lag.

p.s like the mod so far :+1:

**Comment by Dyonovan** [comment]
What version are you using?

**Comment by rob-ed** [comment]
Found the issue in 2.3.4 with FTB Unstable. Tried 2.3.5 with only neotech and bookshelf 2.3.0 and had the same problem.

**Comment by pauljoda** [comment]
I actually saw this issue. I've been trying to think of a way to reduce this. I'll probably just add a cooldown after the fail so it waits a second before trying again
