### ISSUE TITLE
2.3.5 Crash

### ISSUE THREAD

**Issue by SummitSummit** [TeamBR-Modding/NeoTech#106]
Just updated my FTB Unstable pack to 3.0.26 and found the Neotech pipes no longer working, so I updated to 2.3.5 of Neotech and now it crashes when I put my solar panel on top of my Elite energy cell.

**Comment by Dyonovan** [comment]
Can we get a crash log please so we can pinpoint where the issue is. Thanks

**Comment by Dyonovan** [comment]
Ok found the issue. For some reason when Unstable was updated, @Quetzi and the FTB team updated Bookshelf, but not NeoTech. The new Bookshelf and Neotech uses the new Official COFHApi for RF.

Now the version they are using in Unstable of RF Tools still uses the Old RF Api. If you update Bookshelf, Neotech, RFTools and McJtyLib to the latest, we will all be using the same RF API.

This should sort itself out in a couple of days once people finish updating to the new Official RF Api

**Comment by SummitSummit** [comment]
Thanks for the quick response Dyonovan.  I'll grab those updates and see if it fixes everything. 
Yup, everything is working again.

**Comment by Quetzi** [comment]
I overlooked the fact Bookshelf was part of Neotech, I'll roll it back in tomorrows update and then update all the RF stuff once it's moved to the new API
