### ISSUE TITLE
pipes crash 2.3.5

### ISSUE THREAD

**Issue by mrvoll98** [TeamBR-Modding/NeoTech#107]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 12.02.16 09:14
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.onPipeEntered(ResourceEntity.java:194)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.travelPath(ResourceEntity.java:166)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.updateEntity(ResourceEntity.java:106)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:130)
    at com.dyonovan.neotech.pipes.tiles.energy.EnergyInterfacePipe.onServerTick(EnergyInterfacePipe.scala:22)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:70)
    at com.dyonovan.neotech.pipes.tiles.energy.EnergyInterfacePipe.func_73660_a(EnergyInterfacePipe.scala:22)
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.onPipeEntered(ResourceEntity.java:194)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.travelPath(ResourceEntity.java:166)
    at com.dyonovan.neotech.pipes.entities.ResourceEntity.updateEntity(ResourceEntity.java:106)
    at com.dyonovan.neotech.pipes.types.InterfacePipe$class.onServerTick(InterfacePipe.scala:130)
    at com.dyonovan.neotech.pipes.tiles.energy.EnergyInterfacePipe.onServerTick(EnergyInterfacePipe.scala:22)
    at com.teambr.bookshelf.common.tiles.traits.UpdatingTile$class.update(UpdatingTile.scala:70)
    at com.dyonovan.neotech.pipes.tiles.energy.EnergyInterfacePipe.func_73660_a(EnergyInterfacePipe.scala:22)

-- Block entity being ticked --
Details:
    Name: pipeEnergyBasicInterface // com.dyonovan.neotech.pipes.tiles.energy.EnergyInterfacePipe
    Block type: ID #428 (tile.neotech:pipeEnergyBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-245,67,180), Chunk: (at 11,4,4 in -16,11; contains blocks -256,0,176 to -241,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #428 (tile.neotech:pipeEnergyBasicInterface // com.dyonovan.neotech.pipes.blocks.BlockPipeSpecial)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['myrvoll98'/284, l='New World', x=-245,98, y=66,70, z=179,61]]
    Chunk stats: ServerChunkCache: 758 Drop: 0
    Level seed: -2719952063385344840
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: true
    Level spawn location: -228,00,64,00,149,00 - World: (-228,64,149), Chunk: (at 12,4,5 in -15,9; contains blocks -240,0,144 to -225,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 126750 game time, 6253 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 787 (now: false), thunder time: 150 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:152)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 206254184 bytes (196 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.19 Powered by Forge 11.15.1.1735 51 mods loaded, 51 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1735.jar) 
    UCHIJAAAA   Forge{11.15.1.1735} [Minecraft Forge](forge-1.8.9-11.15.1.1735.jar) 
    UCHIJAAAA   cei{0.1} [Chunk Edge Indicator](1.8.9-chunkedgeindicator-1.0.jar) 
    UCHIJAAAA   ac2{1.1.3 Beta} [Alchemy Craft 2](alchemycraft2 v1.3.0.jar) 
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore](AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAA   basemetals{1.6.4} [Base Metals](BaseMetals-1.6.4.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-16} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-16.jar) 
    UCHIJAAAA   bookshelfapi{2.3.0} [Bookshelf](Bookshelf-1.8.9-2.3.0.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.1.jar) 
    UCHIJAAAA   chunkloaderz{1.0.3} [ChunkLoaderZ](ChunkLoaderZ-1.8.9-1.0.3.jar) 
    UCHIJAAAA   deadmess{1.2.0} [Dead Mess](deadmess-1.8.9-1.2.0.jar) 
    UCHIJAAAA   defaultworldgenerator-port{0.3} [Default World Generator](DefaultWorldGenerator-port-1.8.9-0.3.jar) 
    UCHIJAAAA   et{1.0.3} [Energy Tools Core](EnergyTools 1.0.3.jar) 
    UCHIJAAAA   exnihilo2{0.28} [Ex Nihilo 2](ExNihilo2-0.28.jar) 
    UCHIJAAAA   substratum{1.1.0.1} [Substratum](Substratum-1.8.9-1.1.0.1.jar) 
    UCHIJAAAA   foundry{1.4.0.0} [Foundry](Foundry-1.8.9-1.4.0.0.jar) 
    UCHIJAAAA   FunOres{1.1.0-beta6} [Fun Ores](FunOres-1.8.9-1.1.0-beta6-45.jar) 
    UCHIJAAAA   genloader{1.8.9-0.0.1.6} [Generation Loader](GenLoader-1.8.9-0.0.1.6.jar) 
    UCHIJAAAA   graves{1.8.9-b31-universal} [Graves Mod](graves-1.8.9-b31-universal.jar) 
    UCHIJAAAA   HungerInPeace{1.0.0} [Hunger In Peace](HungerInPeace-mc1.8.9-1.0.0.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.25.11.151} [Just Enough Items](jei_1.8.9-2.25.11.151.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft](Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons](JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   jeresources{0.3.1} [Just Enough Resources](JustEnoughResources-1.8.9-0.3.1.jar) 
    UCHIJAAAA   k4lib{1.8.9-1.0.7} [K4Lib](k4lib-1.8.9-1.0.7-universal.jar) 
    UCHIJAAAA   lteleporters{1.0.0} [Lemon's Simple Teleporters](LemonsSimpleTeleporters-1.0.1.jar) 
    UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJAAAA   MCM{1.0.1} [MCM](MCM.jar) 
    UCHIJAAAA   mcmultipart{1.0.5} [MCMultiPart](MCMultiPart-1.0.5-universal.jar) 
    UCHIJAAAA   ModNameTooltip{1.0.0} [Mod Name Tooltip](modnametooltip_1.8.8-1.0.0.jar) 
    UCHIJAAAA   ProjectE{1.8.9-PE1.1.3} [ProjectE](ProjectE-1.8.9-PE1.1.3.jar) 
    UCHIJAAAA   mrfusion{0.1.004} [Mr Fusion](mrfusion-0.1.004.jar) 
    UCHIJAAAA   MystTech{1.8-1.0.0_Alpha} [MystTech](MystTech-1.8.9-1.0.0_Alpha.jar) 
    UCHIJAAAA   neotech{2.3.5} [NeoTech](NeoTech-1.8.9-2.3.5.jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter](OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   ProjectOres{1.0.0} [ProjectOres](ProjectOres.jar) 
    UCHIJAAAA   RandomThings{3.6.2} [Random Things](RandomThings-MC1.8.9-3.6.2.jar) 
    UCHIJAAAA   rftools{4.22beta18} [RFTools](rftools-1.8.9-4.22beta18.jar) 
    UCHIJAAAA   rftoolsdim{4.22beta20} [RFTools Dimensions](rftoolsdim-1.8.9-4.22beta20.jar) 
    UCHIJAAAA   SGCraft{1.10.1} [Greg's SG Craft](SGCraft-1.10.1-mc1.8.9.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.4.0} [Storage Drawers](StorageDrawers-1.8.9-2.4.0.jar) 
    UCHIJAAAA   storagenetwork{1.5} [Storage Network](StorageNetwork-1.8.9-1.5.0.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAAAA   unlogicii{4.1.0.42} [UnLogic II](UnLogicII-4.1.0.42.jar) 
    UCHIJAAAA   unlogiciivc{1.5} [UnLogic II Version Checker](UnLogicII-4.1.0.42.jar) 
    UCHIJAAAA   WIT{1.0.5} [WIT](WIT-1.8.9-1.0.5-14.jar) 
    UCHIJAAAA   YALSM{2.1.5} [Yet Another Leather Smelting Mod](yalsm-2.1.5-mc1.8.9.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.8.9-3.6.2.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerDebug (Enabled/Not Forced)

```
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['myrvoll98'/284, l='New World', x=-245,98, y=66,70, z=179,61]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Dyonovan** [comment]
Do you happen to know what the pipe was connected to and what mod its from?

**Comment by pauljoda** [comment]
Yeah I had found this issue. It has been fixed and will be in the next release
