### ISSUE TITLE
Energy Levels Forgotten On World Load

### ISSUE THREAD

**Issue by MortisLegati** [TeamBR-Modding/NeoTech#109]
Every time I load my world, it seems that the 8-HDD-upgraded devices in my world reset to 0RF stored.  This also occurs whenever a device is turned with the wrench.

**Comment by pauljoda** [comment]
Yeah I've messed with it a bit. Its an issue with the RF api that restricts us a bit. We will work around it

**Comment by Darktotaled** [comment]
it's not happening on my world '-'

**Comment by avatarscion** [comment]
So far for me it only seems to happen to the thermal binder.

**Comment by Darktotaled** [comment]
i'll gonna check mine, brb

**Comment by Darktotaled** [comment]
My thermal binder still has it's energy buffer full

**Comment by pauljoda** [comment]
I'm working on a Mutable energy storage class. Should help make changing energy much easier

**Comment by Darktotaled** [comment]
@pauljoda Way to go man
