### ISSUE TITLE
Issue: Neotech occasionally crashes server on player login

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#11]
Issue: Neotech occasionally crashes server on player login

crash report:
https://gist.github.com/d23f7e24c84ad7f3c3d5

fml server latest:
https://gist.github.com/c382a96e7becd4390c1b

I suspect that if you take Cyanobacterium up his offer to do something with RF between the two mods that this might go away. I use his Power Advantage API as well.

**Comment by Dyonovan** [comment]
Yea Ive got to fix the COFHApi to be compatiable with a few other mods.

**Comment by Dyonovan** [comment]
Should be fixed in rewrite. initial release later today
