### ISSUE TITLE
Pump loves energy

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#110]
So, after 2 hours trying to understand how the pump works, i managed to setup a simple pump>steam boiler(steam advantage) system. The energy comes from the battery i have upstairs. Some time later, i've noticed that the energy kept flowing through the pipes and it kept going for a long time. Seems like the pump eats energy as much as it can. Can you add a simple GUI for it? Showing internal buffer of energy and water.

Btw, awesome mod. Keep Rockin' guys.

**Comment by pauljoda** [comment]
I'll add a waila tag. It does use a lot of energy to pump, I can reduce that as well
