### ISSUE TITLE
looks like u cant shift click ores into the manual grinder

### ISSUE THREAD

**Issue by Sailren** [TeamBR-Modding/NeoTech#111]
well, title explains it, redeem here: http://paste.ubuntu.com/15056391/

used ore was tin from substratum

update: u cant even place it manually into it

**Comment by Darktotaled** [comment]
maybe substratum's tin isnt compatible with the grinder. Base metals' tin and copper at the other hand are compatible. Does it happens only with the grinder or the crusher do that too?

**Comment by Dyonovan** [comment]
Delete your config/NeoTech/Registries/crusherRecipe.json file. It will be recreated on server load. This should pick up the substratum ores.

Going to close this issue. If it doesnt fix the issue, just reopen it.
