### ISSUE TITLE
MCMP Suggestion

### ISSUE THREAD

**Issue by Thutmose** [TeamBR-Modding/NeoTech#112]
I am not sure how difficult this would be, but what would be quite useful would be MCMP (https://github.com/amadornes/MCMultiPart) compatibility for the pipes, as it would allow using something like [Chisel and Bits](http://minecraft.curseforge.com/projects/chisels-bits?gameCategorySlug=mc-mods&projectID=231095) to make covers

**Comment by pauljoda** [comment]
It's something I've considered. It would be nice if agree but it seems like in order to add support there is a lot of changes that would need to be made. I can look and see if an easier way is available, but at the moment we plan to add our own cover system

**Comment by Thutmose** [comment]
If you already have a cover system planned, I would suggest looking into the MCMP compatibility for that as well, It should already have most of the code in place for that sort of thing.

C&B somehow has MCMP as optional, so there may also be a way to make it optional for this too, I would need to look more into how MCMP works to find out more though.

**Comment by pauljoda** [comment]
Don't get me wrong, I would love to add support to MCMP. However, the work involved isn't really worth it in my opinion. I agree it would be nice, but multi part tiles are simply too different for me to change to without lots of effort. We are too far along to go back and change everything. For this reason, we will not be adding support. 

This does not mean we are not giving some options for covering pipes, we plan on adding a cover system that will allow you to paint pipes much like Ender IO. Look forward to this soon
