### ISSUE TITLE
Liquid duplication with the pump

### ISSUE THREAD

**Issue by mille449** [TeamBR-Modding/NeoTech#114]
Place down one bucket of liquid (was using hydraulicraft oil) and put the pump over it.  Pump will suck up 5 buckets; the original bucket plus the four surrounding blocks that are actually flowing liquid.

Would also like to see different behavior between lava/water/everything else. Case in point is the oil well again - the pump does not reach the bottom of deep wells and fills from the bottom up with stone.  This appears very weird in game since the top of the oil well is the last liquid to be sucked up, and then you don't know if you've really gotten all of it without digging back down to find out.

**Comment by mille449** [comment]
One other bug.  Place down a bucket of liquid, then place the pump over a flowing liquid block.  The pump will path-find back to the source and remove the source, but not give you a bucket of liquid.

**Comment by pauljoda** [comment]
I've actually been looking at this. Has something to do with mod fluids and levels. I need to read more into how exactly they define a source block at the base level. There is a handy function at higher levels of fluids but not all fluids. Strangely, there are like 3 different fluids you can extend, each barely different from each other
