### ISSUE TITLE
Energy Interface regression

### ISSUE THREAD

**Issue by AngelCry** [TeamBR-Modding/NeoTech#115]
hi. idk if you already noticed, but looks like last update (NeoTech-1.8.9-2.3.6) break Energy Interface. things already connected in 2.3.5 still work in 2.3.6, while any new connection do not. monor note: besides interfaces stop transfer energy, connection also cheged visually - there no wide part at the end.

**Comment by Dyonovan** [comment]
Pipes now default to insert. You need to hit the pipe with the wrench and configure for output. I believe its the second tab on the right.

**Comment by AngelCry** [comment]
thanks for advice and sorry for false report, but now i have a question: may be you can select default mode depend on what is connect to? at least, in obvious cases, like generators.
