### ISSUE TITLE
Crash on pipe destruction

### ISSUE THREAD

**Issue by Berserker66** [TeamBR-Modding/NeoTech#116]
Crashed when destroying a pipe through which coal was going.

http://pastebin.com/B2LRTn0C

**Comment by pauljoda** [comment]
This has been fixed in the recent release. Are you using that version?

**Comment by Berserker66** [comment]
the most recent version on curse.

**Comment by pauljoda** [comment]
Are you using the most recent beta build? You have to check through the website as the launcher will not show an update. Are you using this version http://minecraft.curseforge.com/projects/neotech/files/2281972

**Comment by Berserker66** [comment]
No, I'm using the user created profile option in curse, which means I cannot use beta builds. If I add a mod manually it'll just stop auto-updates and that'll not help in the long run.

**Comment by pauljoda** [comment]
I see. Well this issue has been solved in the beta build on curse. You are free to add it yourself or wait for the full release in a few days. We didn't want to have a release with issues out so we send a beta out for bug testing.

**Comment by Berserker66** [comment]
The current "stable" is however not stable at all.
In professional programming, you'd either flag an earlier working version as stable, or move forward, but not stay on a broken release as stable.

**Comment by pauljoda** [comment]
Clearly we didn't know it was unstable at the time. These issues came up after the release. We have fixed them and labeled the fixes as beta to prevent the same issue. Please be patient with us, this is not professional programming we do this outside of our jobs and in our spare time. I would love to do this professionally but sadly I cannot. I ask you please keep this in mind in the future. We do this for fun. Its just a game, we are doing are best
