### ISSUE TITLE
Interface opens after pipe removal.

### ISSUE THREAD

**Issue by Berserker66** [TeamBR-Modding/NeoTech#118]
Take the Wrench, shift+right click on an item interface pipe. The pipe is removed as block and drops as item, but the interface gui is opened for the now non existent pipe. Some options in the gui result in various crashes.

**Comment by ConditionOfMan** [comment]
I am experiencing this exact thing. Sneak+right-click both opens the item interaction pipe GUI interface AND removes the pipe.  Ver: 1.8.9-2.3.5

**Comment by pauljoda** [comment]
This was fixed in 2.3.6

**Comment by Berserker66** [comment]
I'm using the latest version from Curse. Mind updating that then?

**Comment by pauljoda** [comment]
The 2.3.6 version is labeled beta for the time being, the issue you are having is fixed in that version. http://minecraft.curseforge.com/projects/neotech/files/2281972
