### ISSUE TITLE
Pipes are very thirsty

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#119]
So, i was playing with fluid pipes and buildcraft refinery and this is what happened. I filled 4 Diamond fluid tanks and went back home. I plugged a fluid interface on the side of the refinery, set the output and input and placed the tank above the fluid interface(maybe this is the problem). Somehow 4 fluid tanks filled with oil made only 14 buckets of fuel. Destroyed the pipes and changed to buildcraft pipes. Put the fluid tank over a pipe without pulling it's liquid with a engine(i let the fluid auto output) and it's 1:1 ratio now. Maybe, just maybe, an interface pipe set to output in the bottom side of a fluid tank can be sucking up more and passing through less liquid than it should. Version 2.3.5 by the way. Still need to update.

See ya guys. Love you all S2

**Comment by pauljoda** [comment]
I'll look into this. Thanks for the report

**Comment by Darktotaled** [comment]
I'm here to help :D

**Comment by pauljoda** [comment]
It seems this is an issue. When I updated pipes to a new system, I overlooked this one. I'm working on it now

**Comment by Darktotaled** [comment]
Glad to help
