### ISSUE TITLE
Can't put any items into crusher

### ISSUE THREAD

**Issue by RayzoRayy** [TeamBR-Modding/NeoTech#120]
Title says it all ^^ everytime i place a stack or even 1 ore(s) into the crusher, my game seems to crash, Haven't tried with the furnace yet..

I am using the 2.3.6 beta, i was using 2.3.5 and was happening in that as well, i figured i'd update and try the new version, still same issue, it was working fine before using 2.3.5 though.

Here is a pastebin of the crash- http://pastebin.com/g8e9XT1c

**Comment by Darktotaled** [comment]
It's strange, i have most the mods you have and i do not crash '-' which ore are you trying to crush? and which mod is it from?

**Comment by Darktotaled** [comment]
There is a guy with the same problem with tin from substratum

**Comment by Dyonovan** [comment]
Try to delete the config/Neotech/Registries/crusherRecipe.json. It will be recreated when you load the server and should fix the issue.

Going to close the issue. If this doesnt fix it, just reopen this issue

**Comment by RayzoRayy** [comment]
Not sure what fixed it, but I re added all my mods to a new instance in MultiMc and updated forge to latest version, so something fixed it, but seems to be working now. :)
