### ISSUE TITLE
I've found the problem with the pipe

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#121]
http://prntscr.com/a3v25m

I've discovered how the issue works. In the setup if the engines are off everything will be fine. The fluid tank will send 8 packets of 1 bucket of fuel till it fills the engines. When the engines are on it will still send 1 bucket of fuel even though the engine didnt use this amount of fuel. The pipe is detecting space in the inventory but not how much it should send there.

**Comment by pauljoda** [comment]
This was fixed in a recent commit. Try this build and let me know if it still happens http://teambrmodding.com:8080/job/NeoTech/148/
