### ISSUE TITLE
Net Launcher recipe conflicts with Iron CAD Assembly from PSI

### ISSUE THREAD

**Issue by cgalliva** [TeamBR-Modding/NeoTech#122]
4 Iron ingots maayyy be a bit generic of a recipe for mods to use!

**Comment by Darktotaled** [comment]
4 iron ingots in a L-shaped pattern to create an iron item L-shaped seems normal unless it has circuits and stuff then you add more items to the mix

**Comment by pauljoda** [comment]
We are going to require the launcher to use power. This means we need batteries, which means we will put a battery in the recipe avoiding conflict. Stay tuned

**Comment by Darktotaled** [comment]
Yay batteries \o/
