### ISSUE TITLE
Pipes not connecting

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#123]
Got the last build on jenkins as sugested by @pauljoda and it seems that interface pipes set to input aren't connecting to inventories as you can see in the print below.

http://prntscr.com/a42zsp

**Comment by pauljoda** [comment]
This is due to storage drawers not implementing the new capabilities
system. It is now how forge handles item handlers. I'll have a look and see
if I can send them the info they need

**Comment by pauljoda** [comment]
Issue submitted to the developers https://github.com/jaquadro/StorageDrawers/issues/217

**Comment by Darktotaled** [comment]
i just checked again and the pipes isnt connecting to the dimensional crates either '-'

**Comment by pauljoda** [comment]
Oops. Forgot to add that to those

**Comment by Darktotaled** [comment]
haha Derp Paul to the rescue :v 
 Keep rockin' m8

**Comment by pauljoda** [comment]
I have fixed our own derp with this commit. Should you choose to try it out grab the latest build of bookshelf and neotech from the Jenkins build server (click the build passing on the main git page) 7eb6083c1bcf8c5549c52e98acfa367444b38acd

**Comment by pauljoda** [comment]
Closing for now, Storage Drawers said they would update when they could. We have updated ourselves so there is no issue. Just waiting for updates from other mods. This issue will happen from time to time as we will always use the latest systems (for better or for worse)

**Comment by Darktotaled** [comment]
Thanks man o/
