### ISSUE TITLE
Bug & Suggestion: Use the Ore Dictionary for the Crusher

### ISSUE THREAD

**Issue by zacklmoore** [TeamBR-Modding/NeoTech#127]
So far from my experience it seems that the crusher will only crush ores into dusts that NeoTech itself has added the dusts for, but not ores from other mods that have equivalent dusts. Some grinder mods use the ore dictionary to auto-detect and link up which ores can be crushed and which dusts they should be crushed into. For example, I'm using the Substratum mod (http://minecraft.curseforge.com/projects/substratum) currently to act as a convenient base to convert most ores to, but many of the ores from that mod (all of which have dusts) are not accepted into the crusher. 

I think doing something like this could also potentially fix a little bug (and maybe it's not even really a bug) I found where occasionally the crusher will crush ores into several different ore dictionary dust entries for the same ore. For example, the crusher gave me mostly iron dusts from NeoTech, but also occassionally gave me Iron dusts from substratum. Not really a big deal and nothing that can't be fixed using an Auto Ore Converter, but just an interesting little bug.

**Comment by pauljoda** [comment]
Delete the json for the crusher recipies in your config directory. We don't regenerate unless that file is absent. We do use ore dictionary to generate recipes but if you add a mod after the registry is created they will not be added

**Comment by Dyonovan** [comment]
As to the output, if you really wanted to, after recreating the crusherRecipe.json, you could go through it and change the output to the exact one you want. When the json is created, it usually just picks the first one it finds in the oredict.

I am going to close this, but if regenerating the json doesnt fix the issue, just reopen this and I will look further into it.
