### ISSUE TITLE
Suggestion: Upgradeable Filter Capactiy for Item Interface Pipes

### ISSUE THREAD

**Issue by zacklmoore** [TeamBR-Modding/NeoTech#128]
I have a system that is routing ores into a crusher -> furance route, however I have enough mods installed to where I have more ores than I can fit into the filter for a single item interface pipe. To workaround this I have 2 interface pipes that hook up to the same network out of the same chest, but it is a little bit of an annoyance. If we could have upgrades that could allow us to increase the number of filter slots for item interface pipes that would be awesome.

**Comment by pauljoda** [comment]
The pipes can match ore dictionary, so if you enable that and put in one copper ore all copper ores will get pulled. The number we set is fairly standard. I will think about it though

**Comment by pauljoda** [comment]
Pipes are gone
