### ISSUE TITLE
Tinker's ore don't like being crushed

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#130]
Ardite and Cobalt can't be crushed. Already deleted the json file and no solution. Can you guys add to the default crusherRecipe file?

**Comment by Dyonovan** [comment]
Reason they cant be crushed is Tinkers doesnt add a dust version of them. Not sure if I want to add them. Lets see what @bonii-xx thinks.

**Comment by Darktotaled** [comment]
You're right. forgot about that. The only way to crush them is through Hydraulicraft i guess. Let's see how it goes

**Comment by Berserker66** [comment]
Usually tinkers ore crushing should be handled by the mod "another ore bites the dust".  But I don't know if that adds the recipes to neotech.

**Comment by Darktotaled** [comment]
don't think AOBD is out '-'

**Comment by Berserker66** [comment]
Yeah, unfortunately. But also a chance to maybe contact the author and get neotech support in on first 1.8.9 release.

**Comment by bonii-xx** [comment]
Cobalt and Ardite are only useful in combination with Tinkers anyway. To use them you need to smelt them in a smeltery and pour them into a cast.
While mod integration is a good thing, I don't see any reason for mod integration for mod integration's sake.

**Comment by Darktotaled** [comment]
Hey @bonii-xx o/ how you doin'? The only reason i wanted to crush them is to make minimal trips to the nether for lava's sake. Using rf provided by a solar panel is less wasteful.

**Comment by Dyonovan** [comment]
I agree with boni for this one.
