### ISSUE TITLE
Wasting energy

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#131]
I'm testing with FTB Unstable. I hooked 3 basic solar panels to 3 basic storage cells and piped the energy to a furnace and a grinder. The pipes extract energy and put it in the machines and the machines start. Once they use the energy, they stop and loose progress. Basically, if you hook solar panels to a machine and leave it for days nothing will get done.

**Comment by Darktotaled** [comment]
My guess is that the machines have the same configuration as the thermal binder
it loses progress when it runs out of energy. If i remember correctly the solar panels produce 10 rf/t each and the machines consume 20 rf/t each. Try adding one more solar panel, wait till you fill the machines' internal buffer and then use them. See if they work.

**Comment by pauljoda** [comment]
All this means is you are not producing enough power. Solar panels produce 10 rf/tick, each furnace and crusher uses 20 rf/tick by default. You are still 10 rf/tick short. I do not see this as an issue as it seems you just don't have enough power to support the machines. If you know for a fact you do and you still can't maintain the machines, comment back here and I will reopen this

**Comment by ghost** [comment]
I knew about the deficit. The jump-grinder stores completion status and I expected the powered machines to do that as well, and just work more slowly (as some other mods do). If you want the machines to not store completion status, I'll add a switch or something to store power.
Thank you.
