### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#132]
Opened this issue cause i don't know how else i can talk to you. Can you customize that part where the RF bar is? Like giving it shape or adding an overlay?

**Comment by mille449** [comment]
What exactly are you asking for?  A fancier UI or the ability to change it yourself?

**Comment by Darktotaled** [comment]
fancier UI. Not exactly fancier but cooler and more NeoTech-ish

**Comment by pauljoda** [comment]
At the moment we are not using a texture. That is a GL rendered white pixel colored and streched to what we need it to be. So it's not really possible to do what you're asking. However, I do have a solution that I have in mind. I won't spoil the surprise. Also, you can always reach us in the #neotech irc channel on espernet

**Comment by Darktotaled** [comment]
had some ideas gonna send you as soon as i can

**Comment by pauljoda** [comment]
Here is a sneak peak at what I've been doing
![java_2016-02-18_22-43-31](https://cloud.githubusercontent.com/assets/3199533/13166774/41e49fa4-d691-11e5-80f6-9a2eafe330bf.png)

**Comment by Darktotaled** [comment]
looks way better than the color changing one btw. Awesome @pauljoda is awesome

**Comment by Darktotaled** [comment]
finally got my scanner working again. that's what i meant  http://prntscr.com/a5a954 @pauljoda
