### ISSUE TITLE
Dimensional crate duping itself?

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamBR-Modding/NeoTech#133]
It seems whenever I break dimensional crate block I get them double back.

Happens on NeoTech-1.8.9-2.3.6.jar

**Comment by Darktotaled** [comment]
tried that and didn't happen to me '-'

**Comment by Dyonovan** [comment]
Can't seem to replicate this either. Going to do a release later today.

Going to close. If this still happens to you after the release, go ahead and reopen the issue

**Comment by Kazzamkablam** [comment]
Seems to still happen on newest version. Probably cross mod conflict?

Attached forge log if it's any use here.
http://www.filedropper.com/fml-client-latest_1

**Comment by Kazzamkablam** [comment]
Yup, still happens with newest version.

http://www.filedropper.com/showdownload.php/fml-client-latest_2 

Forge log if it's any use.

**Comment by Dyonovan** [comment]
Its actually not NeoTech thats causing the dupe. It seems to be one of these mods (as best we can tell) that was causing it but updating to the latest version fixes it.

AbyssalCraft, AbyssalCraft Integration, ArchitectureCraft, Base Metals (1.6.2), Bedrock Layer, Biomes O'Plenty (1867), Building Bricks (1.3.1), Chisel, Chisels & Bits (1.8.10), Fast Leaf Decay, Flat Colored Blocks, Glass Shards (1.6), Iron Chest, JourneyMap, Just Enough Items (2.25.11.150), JEI Addons (0.11.2.56), Metal Gem Craft, Mineralogy, Neotech (2.3.5), Roguelike Dungeons, Skyland (Japanese mod), Storage Drawers (2.3.4) + coremod, Thaumcraft, TC Research Helper, The Void (Japanese mod), Tinker's Construct, and WAILA
