### ISSUE TITLE
Was looking through JEI

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#135]
And then a wild mechanical pipe appears. What is that? What is it function? what is it recipe?

**Comment by pauljoda** [comment]
The mechanical pipe is not something that is crafted. It is used in world by machines. At the moment, its only the pump. It is the pipe that extends out the bottom. Its just a block instance we can use to make things look a little better

**Comment by Darktotaled** [comment]
holy jesus, i swear i never saw it hahahaha like buildcraft's pump lol. Thanks man
