### ISSUE TITLE
Regenerating crusherRecipes

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#137]
i regenerated the crusherRecipe file cause i added base metals to the mix, now everytime i throw a metal that has on both neotech and base metals i get base metals dust equivalent and then the ingot. Problem is, i have dimensional crates full of copper and tin from neotech and every copper and tin i put on the crusher doesnt go to their crates. I guess the crates doesn't accept other types of the same ingot right?

**Comment by Dyonovan** [comment]
I am going to be adding oreDict support to the DimStorage at some point. (Will be part of the upgrade system)

**Comment by Darktotaled** [comment]
i see. had to change the crates for storage drawers as they auto convert ingot to the one that is stored. Thanks o/
