### ISSUE TITLE
Upgrades..?

### ISSUE THREAD

**Issue by Vizis** [TeamBR-Modding/NeoTech#140]
So we have all those magnificent upgrades boosters for maschines and pipes etc.. we have slot for it and.... When You gonna add functionality for them?

**Comment by Darktotaled** [comment]
functionality?

**Comment by Dyonovan** [comment]
The upgrades do work. You have to make a completed motherboard in the Thermal Binder.

Once you have a completed MB, thats what gets inserted into the machines/pipes. The tab on the left in GUI's says what each upgrade does for the specific machine.

**Comment by Vizis** [comment]
Damn i didn't know that, i have tried to use just "upgrade" or other items. didn;t know i have to prepare it on motherboard first in Thermal Binder, THX ~!

**Comment by mille449** [comment]
Maybe we should add something a bit more obvious to indicate this?  I ran into the same confusion the first time I used them also.

**Comment by Darktotaled** [comment]
i saw the machine thermal binder and didn't know the use and then i saw an EMPTY motherboard. Some time later things made sense
