### ISSUE TITLE
Tanks not acepting Input via lava Sigil

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#143]
I can use the lava sigil from Blood magic to fill up a smeltery from Tinkers construct (click on drain just with a bucket). This does not work for tanks from Neotech.

Is this a bug or just a missing feature?

**Comment by Dyonovan** [comment]
I will have to look into how he is doing it.

**Comment by pauljoda** [comment]
Try the latest build from Jenkins please. I have changed how things are handled to the new system http://teambrmodding.com:8080/job/NeoTech/184/ with http://teambrmodding.com:8080/job/Bookshelf%20API%201.8.9/42/
