### ISSUE TITLE
SolarPanel Crash

### ISSUE THREAD

**Issue by Vizis** [TeamBR-Modding/NeoTech#144]
[crash-2016-02-20_00.39.02-server.txt](https://github.com/TeamBR-Modding/NeoTech/files/138870/crash-2016-02-20_00.39.02-server.txt)

i have placed a couple of energy pipes (they were connected to RF storage by one ordinary and one energy again),then i have placed solar panels (the best), when i placed 3rd (all next to each other on a grid of pipes) server got Crash

I checked it 2 times SP on superflat 
Version: NeoTech-1.8.9-2.3.6  from curse.com

**Comment by Dyonovan** [comment]
just released a new version of both NeoTech and Bookshelf. Should fix the issue. Give them a try and if they dont fix it reopen this issue.
