### ISSUE TITLE
EnergyStorage Crash

### ISSUE THREAD

**Issue by Vizis** [TeamBR-Modding/NeoTech#145]
[crash-2016-02-20_01.18.06-client.txt](https://github.com/TeamBR-Modding/NeoTech/files/138900/crash-2016-02-20_01.18.06-client.txt)
Placed Elite EnergyStorage on ground caused instant crash.
Neotech Top Version
forge-1.8.9-11.15.1.1755

**Comment by Dyonovan** [comment]
Looks like one of the other mods you have are using the unofficial RF API. Cofh released an official RF API for 1.8.9 which we are using. 

Maybe buildcraft?

**Comment by Vizis** [comment]
i Have removed buildcraft but still crash, i will check all mods and i will report results

**Comment by blockbreaker1361** [comment]
All of my mods are latest versions with latest RF API in them. When I attempted to place the net launcher in an elite energy cube, I got this instant crash.
http://pastebin.com/eT5kJGyR

**Comment by Dyonovan** [comment]
@blockbreaker1361 Please dont take over other peoples threads as your issue is different. Try breaking and replacing the RF storage Cube

**Comment by Vizis** [comment]
[1.8.9] Thaumic Additions - 0.38 it;s the one. rest of my mods works fine
There is a update for this mod but dev is idiot and he didn;t add libs for download which this mod require

**Comment by Dyonovan** [comment]
Ahh. Figured it had to be someone still using the old API.
