### ISSUE TITLE
Crash trying to charge battery

### ISSUE THREAD

**Issue by Majestyc2k1** [TeamBR-Modding/NeoTech#146]
Got two crashes will trying to place battery in Advanced Storage block. Firsrt crash is placing in top slot, second crash is from bottom slot.

[Crash #1](http://pastebin.com/Ttw4Kr3k)

[Crash #2](http://pastebin.com/GfKuLKPk)

**Comment by Dyonovan** [comment]
Try breaking the rfstorage then replacing it on the ground.

**Comment by Majestyc2k1** [comment]
That fixed it. Thanks.
