### ISSUE TITLE
[Problem] pipes and wrench

### ISSUE THREAD

**Issue by Vizis** [TeamBR-Modding/NeoTech#150]
Ok so...
Wrench can affect chest.. and it's good to rotate yea but wrench also affect torch when used
Next problem, on my vid below chest with output/input has motherboard with 7 HD & 7 CPU when it pupm items they sometimes jumpfrom pipes
The last problem is that some in some cases items wont pump items when whitelisted, you gonna see it in my short vid <still better than screenshots>, The problem is when i for example remove carot from whitelist and i ll put it to other pipe it gonna pump those carrots.
http://www.twitch.tv/vizi_/v/48316422

**Comment by Darktotaled** [comment]
wont it changed if you put just output instead of both?

**Comment by Vizis** [comment]
Nop tried in few configuration, btw it's just test chest, i have other insertion chest, al items fom there comes to this chest on vid, and from there it is sorted to whitelisted chest, if item it's on wl it stays in this chest. I done it for check if my magazine is ready. That's how i found this "bug"

**Comment by pauljoda** [comment]
I'll have a look into those issues. Though wrenches call the default forge rotate block. The torch is going to rotate but if you give it a block update it will break. Its just one of those things that is going to happen

**Comment by pauljoda** [comment]
Try latest build   http://teambrmodding.com:8080/

**Comment by Dyonovan** [comment]
Should be fixed with pipe update next release
