### ISSUE TITLE
Lightning bug with an active mob stand

### ISSUE THREAD

**Issue by dashkal16** [TeamBR-Modding/NeoTech#151]
Album demonstrating here:
http://imgur.com/a/TTS9J

Aside: The bat's animation plays super fast, looks like a hummingbat.

**Comment by Vizis** [comment]
What's the name of the blockwhich is connect to ur pipes and tanks?

**Comment by pauljoda** [comment]
Can you please point out exactly what block/object I should be looking at? I see nothing wrong

**Comment by Darktotaled** [comment]
@pauljoda the mob pedestal with the bat is white the other upfront are grayish

**Comment by pauljoda** [comment]
I guess I still don't see it

**Comment by Darktotaled** [comment]
@pauljoda  shouldn't this two be in the same color? http://prntscr.com/a5z7p1

**Comment by pauljoda** [comment]
I kinda see it. This is likely cause of the Entity Renderer from Minecraft. Usually entity renderers are rendered at a seperate time from tiles so MC code can be sloppy setting GL states back. I'll have to dig into their code and see what they left open and close it myself

**Comment by pauljoda** [comment]
Closing for now, might not be us but I'll keep an eye on it
