### ISSUE TITLE
idea for mob nets

### ISSUE THREAD

**Issue by ShadowAspect01** [TeamBR-Modding/NeoTech#152]
i was just test playing neo tech and i like it. i had an idea for the mob nets could there possible be a machine or recipe that lets you combine the nets and an egg to get a 1 use item of the spawn egg of that type of mob. if you added that you could use the spawner mover and the spawn egg to have what ever mob spawner you needed. should disable bosses spawn eggs lol might be op.

**Comment by pauljoda** [comment]
Yes we have a spawner machine planned. It is in the suggestions issue (probably) Please provide all suggestions there in the future please. We will keep your idea of a portable spawning mechanic in mind as we progress
