### ISSUE TITLE
NeoTech Crash (1.8.9) 2.3.6

### ISSUE THREAD

**Issue by Mickimoo** [TeamBR-Modding/NeoTech#153]
Hello, this has occured when I connected my endertank to fluid pipes which went into two fluid generators and those went to a furnace

Tank -> (Outake) Pipe -> (intake) fluid generators -> (outake) energy pipes -> electric furnace

Crash on start up (chunkloaded)
http://hastebin.com/akevoluyah.avrasm

Server Crash Report
https://gist.github.com/Mickimoo2/ebb32a1b294096fd2d76

**Comment by pauljoda** [comment]
There is a mod using the old RF API (the non official one). We will not work with those mods at this time until they update to the official RF API by Team COFH

**Comment by Dyonovan** [comment]
Best Guess is Actually Additions. The version you are using doesnt use the new RF API.

Upgrade AA and see if that helps. If not, there is another mod in there using the old API

**Comment by Mickimoo** [comment]
Okay, thank you. I had done an update of all those mods and I had never started the server again since I was going to be busy for a little while and didn't want it looping.
