### ISSUE TITLE
Recipe conflict with Psi

### ISSUE THREAD

**Issue by ArbitraryAlex** [TeamBR-Modding/NeoTech#154]
When crafting the Iron CAD Assembly from Psi you recieve a Net Launcher. Both have the same recipe.

**Comment by pauljoda** [comment]
Fixed with latest release

**Comment by Dyonovan** [comment]
https://github.com/TeamBR-Modding/NeoTech/issues/149

**Comment by ArbitraryAlex** [comment]
Oh sorry.. Didn't even see the latest release. :P thought i was on it. My bad.
