### ISSUE TITLE
Electric crusher causing framerate to drop

### ISSUE THREAD

**Issue by Ehysier** [TeamBR-Modding/NeoTech#159]
What Version of NeoTech are you using:2.3.6

If possible, did you break and replace the block:yes

Please Pastebin.com the crash Report and put link here:N/A

**Comment by Darktotaled** [comment]
the framerate only drops when crusher is placed?

**Comment by Ehysier** [comment]
That is correct. Ive tested it and whenever I place the crusher i get a drop in framerate while its rendered.

**Comment by Darktotaled** [comment]
which 2.3.6 version you using? mine is 2.3.6 B148 and it doesn't happen

**Comment by Ehysier** [comment]
All it says is 2.3.6... Where would i find any more info, if it helps Im using the pioneer modpack http://www.curse.com/modpacks/minecraft/241377-the-pioneers

**Comment by pauljoda** [comment]
Does it happen for all machines or just the crusher?

**Comment by Ehysier** [comment]
I believe it has to do with another mod after extensive experimenting. Fluxed solar panels. Alone they dont cause issues, the moment they get attached to something(which was the crusher) then it started. so my bad its not your mod.

**Comment by pooponbads** [comment]
Hey man just keep practicing, everyone has to start somewhere! Hopefully you won't be bad forever, but know your place until you get decent! Otherwise you just make yourself look stupid after getting destroyed! Good luck little man, was fun owning you, nice damage! Maybe play single player games??
