### ISSUE TITLE
Suggestion: Different break times for different types of blocks

### ISSUE THREAD

**Issue by MoonCutter2B** [TeamBR-Modding/NeoTech#16]
The time it takes to break a block should depend on how hard it is.
And empty blocks should be instant, i.e. jump directly to the next breakable block.

**Comment by Dyonovan** [comment]
Are you talking about the miner? I am currently rewriting the whole mod from scratch. initial release should be later today but won't have the miner yet. I will take this into consideration once I get to that block

**Comment by MoonCutter2B** [comment]
yes, the miner :)
