### ISSUE TITLE
Item duplication bug with Dimensional Crate v2.3.7

### ISSUE THREAD

**Issue by shortybsd** [TeamBR-Modding/NeoTech#162]
What Version of NeoTech are you using:
v2.3.7 for MC 1.8.9

If possible, did you break and replace the block:
Yes

Please Pastebin.com the crash Report and put link here:
N/A

When using the wrench to pick up a dimensional crate (to move it) it will dupe the entire crate with a clone, then double every time you do it. Also if you wrench one, then place the same one down. You basically have creative mode because it never removes the original dimensional crate from your inventory.

**Comment by Dyonovan** [comment]
Ill take a look at this tomorrow. I am pretty sure its another mod causing this. Are you using Unstable? If not, can you list your other mods and there versions.

**Comment by shortybsd** [comment]
My own modpack

ArchitectureCraft-1.3.1-mc1.8.9 
BaseMetals-1.6.4 
BiomesOPlenty-1.8.9-3.0.0.1894-universal 
BloodMagic-1.8.9-2.0.0-18 
Bloodmoon-MC1.8.8-1.4 
Bookshelf-1.8.9-2.3.2 
Botania.r1.8-248-unofficial-0.6.2 
buildcraft-7.2.0-pre12 
CandyCraft-1.3.1 
Chisel-MC1.8.9-0.0.2.7 
chiselsandbits-mc1.8.9-v1.8.10 
craftingtweaks-mc1.8.9-3.0.41 
EnderTanks-1.8.9-1.2.1 
enderutilities-1.8.9-0.5.0 
EnderZoo-1.8.9-1.1.3.35 
fastTravel-1.8.8-1.0.4-universal 
fluxedsolars-1.9 
Harvest-1.8.9-1.0.0-2 
HydCraft-1.8.9-3.1.65-universal 
intangible-1.8.9-0.0.22 
InventoryTweaks-1.60-beta-30 
IronBackpacks-1.8.9-2.0.5 
ironchest-1.8.9-6.0.125.770 
jei_1.8.9-2.28.2.166 
journeymap-1.8.8-5.1.3-unlimited 
k4lib-1.8.9-1.0.16-universal 
Mantle-1.8.9-0.7 
mcjtylib-1.8.9-1.8.1beta6 
MCMultiPart-1.0.6-universal 
MrCrayfishFurntiureModv3.6.1(1.8.9) 
NeoTech-1.8.9-2.3.7 
NetherEssence-4.0.1.1 
OpenComputers-MC1.8.9-1.5.22.6 
OpenGrave-1.8.9-2.0 
PowerAdvantage-1.5.0 
ProgressiveAutomation-1.8.9-1.6.35 
RandomThings-MC1.8.9-3.6.3 
rftools-1.8.9-4.22beta25 
rftoolsdim-1.8.9-4.22beta25 
RoguelikeDungeons-1.8.9-1.4.5 
ShetiPhianCore-1.8.9-3.1.0 
simplefluidtanks-1.8.9-1.3.0.2 
sodacanutils-2.0.4 
SteamAdvantage-1.5.1 
storagesilo-1.8.9-1.2.2b 
TConstruct-1.8.9-2.0.2 
Thaumcraft-1.8.9-5.1.6 
Waila-1.6.0-B3_1.8.8

**Comment by Dyonovan** [comment]
Great thanks. Was finally able to reproduce this. now to find out what mod is causing this.

**Comment by Dyonovan** [comment]
Ok. After going through and disabling mods, its Biomes O Plenty that is causing this. Disabling it stops it from happening. Will try and track down why
