### ISSUE TITLE
RF Storage

### ISSUE THREAD

**Issue by Dyonovan** [TeamBR-Modding/NeoTech#163]
https://github.com/BBoldt/ThePioneers/issues/24

**Comment by BBoldt** [comment]
Any fluxed solars solar panel with any NeoTech RF storage result results in the FPS drop.

**Comment by Dyonovan** [comment]
https://github.com/primetoxinz/FluxedSolars/blob/master/src/main/java/primetoxinz/fluxedsolars/tile/TileSolar.java#L43

Block is being marked for update every tick
