### ISSUE TITLE
Suggestions regarding solars and energy storage

### ISSUE THREAD

**Issue by BBoldt** [TeamBR-Modding/NeoTech#164]
1) **Config options** for power generated by solar panels, as well as for the amount of energy that can be stored in RF Storages.

2) **New recipes** for solar panels. 
Currently, it costs 8 of the previous tier + an energy cell, with no power generation benefit. To me, this seems pretty pointless. I'm not going to go to the trouble of making an energy cell just to save space.

Here are my suggested recipes, each tier presents a unique challenge, and you can still use solars of the previous tier in the upgrade.
![](http://i.imgur.com/iuz1odR.png)

3) **Power values**.
I am not a fan of exponential growth when it comes to storing or producing energy in minecraft. This usually leads to a sharp curve that can get extremely overpowered very quickly.

**Solars**
Currently, the production rate goes:
10rf/t, 80rf/t, 640rf/t

The biggest problem with a progression like this is the large jump between tiers that gets larger each time. If you were to add another tier, it would be 40960rf/t, which is crazy.

I would suggest a linear growth rate, as I said in IRC:
(x4)
8rf/t, 32rf/t, 512rf/t, 2048rf/t, etc.

**Energy Storage**
I don't even know what you were going for. The recipes do not justify these values, people will just skip tiers all the way to the end, you may as well just have one.
Yours:
25,000rf
(x40)
1,000,000rf
(x10)
10,000,000rf

My Suggestion:
32,000rf
(x4)
512,000rf
(x4)
4,096,000rf

**Comment by mille449** [comment]
Ultimately this decision is not mine, but  here's my two cents:

1) Config option would not be hard to make, but for power storage it doesn't make a lot of sense.  To play the devil's advocate: this sort of option would only really be useful to mod pack creators... but what would they use it for?  Reducing the values to make them less useful? Increasing the values to make them overpowered?  I'm not aware of any other mod that provides a config option for power storage values.  I don't disagree necessarily, I just don't see a good use case.

2) Current recipies scale resource costs with power output very nicely.  While I don't dislike your recipes, they are extremely cheap for the amount of power solars put out right now.

3) I'm pretty sure we've discussed increasing power output per tier as a bonus for upgrading, but we haven't gotten around to it yet.  I like your linear progression idea, but your math is not quite right:

8x4=32, 32x4=128, 512x4=2048

So your math is actually multiplying x8 after the first tier.  Additionally, while it is common to see numbers that are exponents of 2, it is not really user-friendly and doesn't accomplish anything but lazy math for the programmer.  With current recipes it makes sense to keep an x8 multiplier, but i would bump it to x10 for cleaner numbers and a bonus: 

2rf/t, 20rf/t, 200rf/t

Yes, that's a big power nerf.  But these are solars, and regardless of the crafting cost they have no maintenance cost, so they shouldn't be amazing.

**Comment by BBoldt** [comment]
oops, I did that kinda late at night, I skipped the 128 tier and went straight to 512 and multiplied that by 4, lmao

edited the OP

**Comment by BBoldt** [comment]
As for the power option configs, I _really_ wish more mods did that. I like to have power storages balanced across the board. Power storage can be just as OP as power production in a lot of circumstances.

I agree with the bump up to 10x for the bonus with the current recipe. But I still prefer my own recipe suggestion to the originals. As I said before, i'm just not a fan of that style of crafting. It doesn't make much sense to squish a bunch of solars together like that.
