### ISSUE TITLE
Only the Pipe System

### ISSUE THREAD

**Issue by Saphrym** [TeamBR-Modding/NeoTech#165]
I'm trying to do a magical modpack but still want a pipe system. I can't find anything that is just pipes. Is it possible to have a config to turn off everything BUT the pipes and tanks? I like your pipes the best out of everything I've tried. They are awesome. But I don't want the machines in the pack.

**Comment by pauljoda** [comment]
Without the thermal binder you can't upgrade the pipes. The two are linked for better or for worse. I'm glad you like them but perhaps just don't use the machines or if you are creating a pack just remove the recipes. Thanks for the input
