### ISSUE TITLE
1.8.9-Corruppted Fluid Registry for Steel

### ISSUE THREAD

**Issue by WenXin20** [TeamBR-Modding/NeoTech#166]
NeoTech: v2.3.8
Crash on World Load:
http://pastebin.com/xb4ErH2Z

**Comment by Dyonovan** [comment]
I just pushed what I hope is a fix. Could you try this version of NeoTech and let me know.

http://teambrmodding.com:8080/job/NeoTech/7/artifact/build/libs/NeoTech-1.8.9-2.3.8-B7.jar

**Comment by OldManCraft** [comment]
Was just starting up new server and ran into this. Seems you have fixed..TY

**Comment by WenXin20** [comment]
Mine works too, thanks for the fix.
