### ISSUE TITLE
Crucible does not accept Neotech metals

### ISSUE THREAD

**Issue by Shurhaian** [TeamBR-Modding/NeoTech#167]
What Version of NeoTech are you using: 1.8.9-2.3.8a

If possible, did you break and replace the block: Newly placed, but yes, replaced to be sure

Please Pastebin.com the crash Report and put link here: Not a crash

Placed an electric crucible next to the thermal binder, intending to use it to keep said binder supplied with liquid tin. Can't place tin in the input slot. Have tried shift-clicking and manual placement in the slot. Neotech is currently my only tin-supplying mod, so it's Neotech tin, not some other mod's. (Except for nuggets, those are Thaumcraft's.) Tried with ingots, blocks, and nuggets. Also deleted the crucible recipes cfg and json to let them autogenerate, but it doesn't generate any recipes relating to tin in any way (or copper, silver, or lead).

**Comment by Dyonovan** [comment]
Fixed for next release (in about an hour)
