### ISSUE TITLE
Solidifier recipes cause crash in JEI

### ISSUE THREAD

**Issue by Shurhaian** [TeamBR-Modding/NeoTech#168]
What Version of NeoTech are you using: 1.8.9-2.3.8a
JEI 1.8.9-2.28.5.172
JEIAddons 1.8.9-0.12.0.57

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: http://pastebin.com/98upDrrW

Attempting to look up recipes for Bronze Ingots in JEI, and tabbing over recipe types, results in the above crash. A glance at the crash report suggests that the recipe category in question is for the NeoTech solidifier.

**Comment by Dyonovan** [comment]
Can you delete the 2 solidifierRecipes files in config/NeoTech/Registries directory and see if that fixes it. I will still add some checks in the code to make sure errors in the recipe files dont cause crashes.

**Comment by Dyonovan** [comment]
Never mind. Found the issue and fixing it. Should have a release out later today with all the fluid fixes.
