### ISSUE TITLE
Grinder Put Items in Crash

### ISSUE THREAD

**Issue by ashly138** [TeamBR-Modding/NeoTech#174]
What Version of NeoTech are you using:
Bookshelf-API-1.8.9-2.3.4
NeoTech-1.8.9-2.3.9

If possible, did you break and replace the block:
Yes did that

Put any ingot in and it crashes the game
https://paste.ee/p/28TYv

**Comment by Dyonovan** [comment]
Try deleting your NeoTech config directory and let it re-create the jsons.

Let me know if this fixes it.

**Comment by ashly138** [comment]
Okay that worked thanks :D
