### ISSUE TITLE
Thermal Binder not starting when I click start.

### ISSUE THREAD

**Issue by Kriptikz** [TeamBR-Modding/NeoTech#175]
What Version of NeoTech are you using:
NeoTech 2.3.9
Bookshelf API Library 2.3.4

If possible, did you break and replace the block:
I did break and replace the Thermal Binder it didn't work. I started a new instance of minecraft with forge with just neotech installed to see if other mods caused this, still didn't start. Started a creative world and used Creative Energy Storage to power Thermal Binder put in motherboard with expansion and click start, still nothing happens. 

Please Pastebin.com the crash Report and put link here:
No crash to report.

**Comment by Dyonovan** [comment]
Did you add Molten Tin to it? It needs the tin to actually work.

You can use the Electric Crucible to melt tin

**Comment by Kriptikz** [comment]
Ah, thank you very much, I didn't realize it needed tin now lol, one other thing I just noticed was that I can't smelt iron to get steel anymore, is there a new recipe(not showing in jei for me)?

Also, that was a very fast response, very nice work!

**Comment by Dyonovan** [comment]
Yes. You need to melt iron and coal (charcoal gives you twice as much carbon) then use the Electric Alloyer to combine them. That will give you molten steel. Then use the Solidifer to make the ingot/nugget/block

It should how the steps in jei.
