### ISSUE TITLE
Crash with phantom glass

### ISSUE THREAD

**Issue by Majestyc2k1** [TeamBR-Modding/NeoTech#176]
What Version of NeoTech are you using: 2.3.9

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: [http://pastebin.com/AqN0fnCW]

I received the posted crash when trying to place a phantom glass block.

**Comment by Dyonovan** [comment]
Thank @Majestyc2k1 Keep em coming :P

**Comment by pauljoda** [comment]
Odd. These calls done look like my code. I don't remember adding any of the ConnectedTexture calls. Can you try with just our mod and bookshelf?

**Comment by Majestyc2k1** [comment]
I made a new world using just Neotech, Bookshelf and JEI. I was able to make and place Phantom Glass w/o crashing. I used the latest mod versions on Curse.

**Comment by pauljoda** [comment]
Ok. There may be a mod interfering. Can you try those versions and see if
you have any idea what mod could be causing this? Perhaps if you can make
it crash again, post the log so I can see if there are any errors when
loading. Thanks for the help

**Comment by pauljoda** [comment]
This seems to be a bug with architecturecraft. Not sure what they are doing but they are calling our model with their code on a minecraft block.

**Comment by Majestyc2k1** [comment]
Disabling that mod solved the problem. Thanks.
