### ISSUE TITLE
Neotech causing large CPU drops when trying to move items from full inventories to full inventories

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#177]
What Version of NeoTech are you using: NeoTech-1.8.9-2.3.7

If possible, did you break and replace the block: Yes :P

Please Pastebin.com the crash Report and put link here: http://imgur.com/glXH3cV

Trying to pipe items from a full diamond chest into a full diamond chest from the Iron Chests Mod causes Neotech to use a large % of the CPU and thus slows down/freezes a server.

Forge: forge-1.8.9-11.15.1.1755-universal

Sponge: spongeforge-1.8.9-1732-3.1.0-BETA-1164

**Comment by pauljoda** [comment]
Interesting. I had planned on doing some new methods for the pipes so that will probably get moved forward. Thanks for the detailed report

**Comment by pauljoda** [comment]
Could you try the latest build on Jenkins and let me know if that helped at all? http://teambrmodding.com:8080/

**Comment by Dyonovan** [comment]
Should be fixed now that we changed pipes around again
