### ISSUE TITLE
Gold Fluid Tank holds less then reported

### ISSUE THREAD

**Issue by SudzBud** [TeamBR-Modding/NeoTech#180]
What Version of NeoTech are you using:1.8.9-2.3.9

If possible, did you break and replace the block:Yes multiple times

Gold fluid tank in inventory shows 16000 mb, but when placed in the world it only holds 8000 mb, the same as iron tank. This tank was upgraded from an empty iron tank. Then refilled with a full iron tank of oil. I just now cheated in a new tank and it holds in world correct amount. Both tanks look identical in inventory, but when placed in world the upgraded one still only holds 8000 mb.

**Comment by SudzBud** [comment]
I can't recreate it again with cheated in mats. I am guessing this has been fixed in the latest version, but the tank was originally created a few updates ago.

Thanks,
Bud

**Comment by pauljoda** [comment]
Yes this was an old issue. Past version's tag might not line up with current methods. New ones should be fine
