### ISSUE TITLE
Crafting a higher teir net launcher upgrades all current net launchers in your inventory to that higher teir

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#182]
What Version of NeoTech are you using: NeoTech-1.8.9-2.3.7

If possible, did you break and replace the block: No block to break/replace

Please Pastebin.com the crash Report and put link here:No crash report, just upgrading of item

Title says it all.. Let me know if you need anything else. I relogged, used them, tried to charge/discharge but they really did have the new, higher tier charge.

**Comment by Dyonovan** [comment]
Fixed in next release
