### ISSUE TITLE
interfering neotech and biome o plenty on the server

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#183]
What Version of NeoTech are you using:
NeoTech-1.8.9-2.3.9
BiomesOPlenty-1.8.9-3.0.0.1886
If possible, did you break and replace the block:
...
Please Pastebin.com the crash Report and put link here:
In the server console I see:
http://pastebin.com/ADkxZpwf

Server does not crashed.

Related bug on the SpongeForge: https://github.com/SpongePowered/SpongeForge/issues/560

**Comment by Dyonovan** [comment]
Seems to be the same issue as #162 

Waiting for a reply from BOP https://github.com/Glitchfiend/BiomesOPlenty/issues/698
