### ISSUE TITLE
Duplication of Axe in Electric Logger

### ISSUE THREAD

**Issue by flipwalker42** [TeamBR-Modding/NeoTech#184]
What Version of NeoTech are you using:2.3.9

If possible, did you break and replace the block:Yes

Using FTB:Unstable with an enchanted Manasteel axe if I middle click to sort the inventory it duplicates the manasteel axe with enchants included into the main inventory and leaves the original in the axe slot. I have a video of it in action if Youtube will ever finish processing it.

**Comment by pauljoda** [comment]
Relog and see if it is still there. It could be a bug with the inventory sorting method you are using. Inventory Tweaks is known for doing this

**Comment by flipwalker42** [comment]
I've relogged, broken the block, replaced it, and still able to replicate. If you think it's not an issue with Neotech then I"ll go post it on the inventory mod's list, just thought I'd try here first. :-)

**Comment by pauljoda** [comment]
I appreciate that. Go ahead and open one there and see if they have any
input.

**Comment by pauljoda** [comment]
Closing for now, don't think it's us
