### ISSUE TITLE
CrusherRecipeRegistry Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [TeamBR-Modding/NeoTech#185]
What Version of NeoTech are you using: (NeoTech-1.8.9-2.3.7.jar)

If possible, did you break and replace the block: Server restarted fine after the crash but will crash again a few minutes later

Please Pastebin.com the crash Report and put link here: http://pastebin.com/n9DuD8M5

**Comment by pauljoda** [comment]
Delete config directory and let it regenerate. If the issue persists return to comment here and we will reopen

**Comment by cauliflower69** [comment]
Thanks
