### ISSUE TITLE
Liquid duplication bug (pipe)

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#187]
What Version of NeoTech are you using:
2.39
If possible, did you break and replace the block:
yes, did fix not updating input/output settings
Please Pastebin.com the crash Report and put link here:
No crash. 

The issue is that if I pump a liquid (was using hydraulicraft oil) into a TC smeltery (via the drain) the liquid gets almost trippled 64 buckets became 189 buckets. Extracting the liquid does not dupe the liquid. I used a Diamond Tank, Fluid interface pipe and TC smeltery. 

Other issue was that I have to break and replace liquid interface pipes if I change the input/output settings. It does not work otherwise.

Pumping liquids into a smeltery with other pipes works without issues.

Kind regards

**Comment by pauljoda** [comment]
Can you try with the latest version of bookshelf and neotech from here? http://teambrmodding.com:8080/

**Comment by ghost** [comment]
I tried it with the latest version.
Fixed the issue!
Great!
