### ISSUE TITLE
[1.8.9] thirteen things to fix, One request and a Six Suggested, "version 2.4.3-B138"

### ISSUE THREAD

**Issue by mario-88ce** [TeamBR-Modding/NeoTech#188]
What Version of NeoTech are you using:   
- Nanotech  --->  ̶2̶.̶4̶.̶1̶-̶B̶1̶3̶3̶   -  2.4.3-B138
- Bookshelf  --->   ̶2̶.̶3̶.̶6̶-̶B̶3̶0̶  -  2.3.7-B31
- McMultiPart  ---> 1.0.8
- Forge --->  ̶1̶1̶.̶1̶5̶.̶1̶.̶1̶7̶6̶5̶   - 11.15.1.1794

If possible, did you break and replace the block: yes

---

Request:

I created a code for the Italian language I do not know if I did well and I can not create a file , the code and done on pastebin taking the original English if you can give him a look and include it in the build if it's good I'll be happy .

Lang iT: http://pastebin.com/iR7dbMJm

---

Suggested:

1)  ̶s̶o̶ ̶t̶h̶a̶t̶ ̶t̶h̶e̶ ̶l̶i̶q̶u̶i̶d̶ ̶p̶r̶o̶d̶u̶c̶t̶s̶ ̶m̶a̶y̶ ̶a̶l̶s̶o̶ ̶b̶e̶ ̶c̶o̶l̶l̶e̶c̶t̶e̶d̶,̶ ̶t̶r̶a̶n̶s̶p̶o̶r̶t̶e̶d̶ ̶,̶ ̶a̶n̶d̶ ̶i̶n̶s̶e̶r̶t̶e̶d̶ ̶i̶n̶ ̶t̶h̶e̶ ̶m̶a̶c̶h̶i̶n̶e̶s̶ ̶n̶o̶t̶ ̶o̶n̶l̶y̶ ̶w̶i̶t̶h̶ ̶t̶u̶b̶e̶s̶ ̶b̶u̶t̶ ̶a̶l̶s̶o̶ ̶w̶i̶t̶h̶ ̶b̶u̶c̶k̶e̶t̶s̶ ̶

1a) Now the liquid product , either take with buckets from machinery but still you can not enter with dried

2) with the pump when washing or water pump it follows a random pattern , and if it replaces the block of lava or water below them stops pumping is advisable to make sure that the block below them is the last to be pumped

3)  ̶a̶r̶e̶s̶ ̶s̶o̶ ̶t̶h̶a̶t̶ ̶t̶h̶e̶ ̶t̶a̶n̶k̶ ̶c̶a̶n̶ ̶b̶e̶ ̶t̶a̶k̶e̶n̶ ̶w̶i̶t̶h̶ ̶t̶h̶e̶i̶r̶ ̶c̶o̶n̶t̶e̶n̶t̶s̶,̶ ̶i̶t̶ ̶c̶a̶n̶ ̶b̶e̶ ̶m̶o̶v̶e̶d̶ ̶t̶o̶ ̶r̶e̶p̶o̶s̶i̶t̶i̶o̶n̶

4) Council to create a guide , " book written in minecraft " , which explains the use of the machines arias but especially :

Mob Stand
net Launcher
Mob Net
attractor

That all 'now can not figure out how to use them would also be easier for other players that use the mod for the first time dto that network are not tutorials on the various components of the mod .

5) I suggest to improve Symbols of armor upgrades that are not very clear what should be updated on a specific piece.

6) I suggest far so that the crucible can also dissolve the plates of various metals " gold , iron , diamond " so as to be able to recover if not the entire amount but a minimum part of mteriale used.

7) I suggest to create a tank that can be connected to its own similar between worlds , as I put a tank that receives lava in the nether and its similarly receives the lava in the normal world

---

To Correct:

12) The buckets which contained the mettalli liquids have their name but they have another acronym: item.foge.bucketFilled.name
I have no other mods installed , and I have the latest version of Forge installed so I do not have conflicts or cant version of forge

12a) Screen:
![nome secchi sballato](https://cloud.githubusercontent.com/assets/17567264/13727896/6301bc4a-e905-11e5-9282-3780a1df19e3.jpg)

13) Raw Coal can not be inserted in the crucible

17)  After using the enhancement for the light to pick, when you turn off the excavated area remains lit

18) When I click the G button to turn on / off the various power-ups , there are no more icons and names that make me see what I'm turning on / off This happens only if I have the electric pickaxe in hand to turn on / off her skills. This only happens if the pick there is more of an update that you can turn on or off , if any schermat the only one you see.

18a) Screen: 
![senza piccone](https://cloud.githubusercontent.com/assets/17567264/13727888/118ca1a4-e905-11e5-9404-670df989e837.jpg)
![immagine](https://cloud.githubusercontent.com/assets/17567264/13843735/cf81c864-ec35-11e5-9073-0313c7beb743.jpg)
![con piccone](https://cloud.githubusercontent.com/assets/17567264/13727889/19529844-e905-11e5-9b47-86d9a3ff01c2.jpg)

19)  Electrical boots consume energy only a few times, and if they use consume only 23 MB and then get stuck at 24,977 MB

24) The solidifier when there is a fluid that does not have the lingot mode or nugget mode works just as in error ( 22 ) , this time not consume liquid but consumes energy.

24a) Screen:
![immagine](https://cloud.githubusercontent.com/assets/17567264/13826941/56605840-ebba-11e5-9dad-5323ef6037a6.jpg)

28) If connect three generators boosted to the maximum and then 160 production RF one , with a total of 480 RF output , to an RF storage , it will have incoming from 160 RF to 200 RF, and not 480 RF  as it should be.

29) If I put a block of obsidian in the crucible should not give me the exact amount of liquid obsidian of a block ? because if the amount of obsidian which gives me 36MB try to solidify again is not the amount of a block

30) According to crash when using pipes with the quantity and speed of extraction Mass at most of a box to another , and I place the object in case the game crashes and I can no longer come into the world

30a) Report: http://pastebin.com/xWum9z8r

32) The automatic light electric pickaxe does not work

33) elettric pump does not accept energy.

34) the solidifier not solidifies obsidian.

35) The electric sword it takes energy from the batteries and do the storage.

---

Correct

1)  ̶I̶n̶ ̶t̶h̶e̶ ̶i̶n̶t̶e̶r̶f̶a̶c̶e̶ ̶o̶f̶ ̶t̶h̶e̶ ̶t̶u̶b̶e̶s̶ ̶i̶n̶ ̶t̶h̶e̶ ̶d̶e̶s̶c̶r̶i̶p̶t̶i̶o̶n̶ ̶o̶f̶ ̶t̶h̶e̶ ̶c̶o̶l̶o̶r̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶i̶n̶p̶u̶t̶ ̶a̶n̶ ̶t̶h̶e̶ ̶o̶u̶t̶p̶u̶t̶,̶ ̶t̶h̶e̶ ̶d̶e̶s̶c̶r̶i̶p̶t̶i̶o̶n̶ ̶i̶s̶ ̶i̶n̶ ̶f̶a̶c̶t̶ ̶r̶e̶v̶e̶r̶s̶e̶d̶ ̶f̶r̶o̶m̶ ̶t̶h̶a̶t̶ ̶b̶l̶u̶e̶ ̶i̶s̶ ̶t̶h̶e̶ ̶o̶u̶t̶p̶u̶t̶,̶ ̶a̶n̶d̶ ̶t̶h̶e̶ ̶o̶r̶a̶n̶g̶e̶ ̶i̶s̶ ̶t̶h̶e̶ ̶i̶n̶p̶u̶t̶,̶ ̶i̶s̶ ̶t̶h̶e̶ ̶o̶p̶p̶o̶s̶i̶t̶e̶.̶ (Correct)

2)  ̶T̶h̶e̶ ̶u̶p̶d̶a̶t̶e̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶p̶i̶c̶k̶ ̶e̶l̶e̶t̶t̶r̶i̶c̶o̶d̶e̶l̶ ̶'̶ ̶e̶x̶c̶a̶v̶a̶t̶i̶o̶n̶ ̶a̶r̶e̶a̶ ̶i̶s̶ ̶n̶o̶t̶ ̶w̶o̶r̶k̶i̶n̶g̶ ̶t̶h̶e̶ ̶p̶i̶c̶k̶ ̶j̶u̶s̶t̶ ̶d̶i̶g̶ ̶a̶ ̶w̶e̶l̶l̶ ̶i̶f̶ ̶t̶h̶e̶ ̶'̶ ̶a̶r̶e̶a̶ ̶b̶l̶o̶c̶k̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶3̶x̶3̶,̶ ̶5̶x̶5̶ ̶a̶n̶d̶ ̶t̶h̶e̶ ̶o̶t̶h̶e̶r̶s̶    (correct)

3)  ̶I̶ ̶m̶e̶l̶t̶e̶d̶ ̶t̶h̶e̶ ̶s̶t̶e̶e̶l̶,̶ ̶a̶n̶d̶ ̶o̶n̶c̶e̶ ̶t̶h̶a̶t̶ ̶i̶s̶ ̶d̶o̶n̶e̶ ̶t̶h̶e̶ ̶I̶ ̶t̶r̶a̶n̶s̶f̶e̶r̶r̶e̶d̶ ̶i̶n̶t̶o̶ ̶t̶h̶e̶ ̶c̶e̶n̶t̶r̶i̶f̶u̶g̶e̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶r̶e̶ ̶g̶a̶v̶e̶ ̶m̶e̶ ̶t̶h̶e̶ ̶t̶w̶o̶ ̶l̶i̶q̶u̶i̶d̶s̶ ̶:̶ ̶l̶i̶q̶u̶i̶d̶ ̶c̶o̶a̶l̶ ̶a̶n̶d̶ ̶i̶r̶o̶n̶ ̶l̶i̶q̶u̶i̶d̶ ̶w̶h̶e̶n̶ ̶I̶ ̶a̶t̶t̶a̶c̶h̶e̶d̶ ̶t̶h̶e̶ ̶t̶u̶b̶e̶s̶ ̶t̶o̶ ̶t̶r̶a̶n̶s̶p̶o̶r̶t̶ ̶i̶t̶ ̶i̶n̶ ̶t̶w̶o̶ ̶d̶i̶f̶f̶e̶r̶e̶n̶t̶ ̶t̶a̶n̶k̶ ̶I̶ ̶c̶r̶a̶s̶h̶e̶d̶ ̶t̶h̶e̶ ̶g̶a̶m̶e̶   (correct)

4)  ̶w̶h̶e̶n̶ ̶t̶h̶e̶ ̶s̶t̶e̶e̶l̶ ̶m̶e̶l̶t̶ ̶b̶y̶ ̶c̶e̶n̶t̶r̶i̶f̶u̶g̶a̶l̶ ̶l̶i̶q̶u̶i̶d̶ ̶c̶o̶a̶l̶ ̶g̶o̶e̶s̶ ̶i̶n̶ ̶t̶h̶e̶ ̶t̶a̶n̶k̶ ̶w̶h̶e̶n̶ ̶i̶t̶ ̶i̶s̶ ̶c̶o̶n̶n̶e̶c̶t̶e̶d̶ ̶a̶s̶ ̶t̶h̶e̶ ̶l̶i̶q̶u̶i̶d̶ ̶i̶r̶o̶n̶ ̶d̶i̶s̶a̶p̶p̶e̶a̶r̶s̶  (correct)

5)  ̶B̶y̶ ̶c̶e̶n̶t̶r̶i̶f̶u̶g̶a̶l̶ ̶w̶h̶e̶n̶ ̶y̶o̶u̶ ̶d̶i̶v̶i̶d̶e̶ ̶t̶h̶e̶ ̶b̶r̶o̶n̶z̶e̶ ̶a̶n̶d̶ ̶c̶o̶l̶l̶e̶a̶g̶u̶e̶s̶ ̶t̶o̶ ̶t̶a̶n̶k̶ ̶i̶t̶ ̶g̶o̶e̶s̶ ̶i̶n̶ ̶t̶h̶e̶ ̶t̶i̶n̶ ̶t̶a̶n̶k̶ ̶b̶r̶o̶n̶z̶e̶ ̶r̶e̶m̶a̶i̶n̶s̶ ̶i̶n̶ ̶c̶e̶n̶t̶r̶i̶f̶u̶g̶e̶ ̶a̶n̶d̶ ̶o̶n̶c̶e̶ ̶s̶h̶e̶ ̶g̶o̶t̶ ̶b̶r̶o̶n̶z̶e̶ ̶2̶8̶8̶M̶B̶ ̶c̶e̶n̶t̶r̶i̶f̶u̶g̶e̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶s̶p̶i̶n̶ ̶m̶o̶r̶e̶   (correct)

6)  ̶O̶b̶s̶i̶d̶i̶a̶n̶ ̶l̶i̶q̶u̶i̶d̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶e̶n̶t̶e̶r̶ ̶i̶n̶t̶o̶ ̶t̶h̶e̶ ̶c̶e̶n̶t̶r̶i̶f̶u̶g̶e̶  (Correct)

7)  ̶t̶h̶e̶ ̶l̶a̶v̶a̶ ̶g̶e̶n̶e̶r̶a̶t̶e̶d̶ ̶b̶y̶ ̶t̶h̶e̶ ̶m̶e̶l̶t̶i̶n̶g̶ ̶o̶f̶ ̶c̶o̶b̶b̶l̶e̶s̶t̶o̶n̶e̶ ̶o̶r̶ ̶s̶t̶o̶n̶e̶ ̶c̶a̶n̶ ̶n̶o̶t̶ ̶b̶e̶ ̶m̶o̶v̶e̶d̶ ̶e̶v̶e̶n̶ ̶t̶r̶y̶i̶n̶g̶ ̶t̶o̶ ̶p̶u̶t̶ ̶i̶n̶ ̶a̶ ̶t̶a̶n̶k̶ ̶a̶n̶d̶ ̶i̶n̶ ̶a̶l̶l̶o̶y̶e̶r̶ ̶i̶n̶s̶t̶e̶a̶d̶ ̶w̶i̶t̶h̶ ̶t̶h̶e̶ ̶b̶u̶c̶k̶e̶t̶ ̶a̶n̶d̶ ̶w̶i̶t̶h̶ ̶t̶h̶e̶ ̶p̶u̶m̶p̶ ̶c̶a̶n̶ ̶b̶e̶ ̶i̶n̶s̶e̶r̶t̶e̶d̶ ̶i̶n̶ ̶t̶h̶e̶ ̶t̶a̶n̶k̶  (correct)

8)  ̶l̶i̶q̶u̶i̶d̶ ̶o̶b̶s̶i̶d̶i̶a̶n̶ ̶c̶r̶e̶a̶t̶e̶d̶ ̶i̶n̶ ̶a̶l̶l̶o̶y̶e̶r̶ ̶c̶a̶n̶ ̶n̶o̶t̶ ̶b̶e̶ ̶m̶o̶v̶e̶d̶ ̶i̶n̶ ̶s̶o̶l̶i̶d̶i̶f̶i̶e̶r̶  (correct)

9)  ̶b̶r̶o̶n̶z̶e̶ ̶c̶r̶e̶a̶t̶e̶d̶ ̶i̶n̶ ̶a̶l̶l̶o̶y̶e̶r̶ ̶o̶n̶c̶e̶ ̶i̶n̶ ̶s̶o̶l̶i̶d̶i̶f̶i̶e̶r̶ ̶c̶a̶n̶ ̶n̶o̶t̶ ̶e̶x̶c̶e̶e̶d̶ ̶5̶7̶6̶M̶B̶ ̶s̶t̶o̶r̶a̶g̶e̶  (correct)

10)  ̶I̶r̶o̶n̶ ̶d̶u̶s̶t̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶g̶o̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶c̶r̶u̶s̶h̶e̶r̶ ̶t̶o̶ ̶t̶h̶e̶ ̶f̶u̶r̶n̶a̶c̶e̶ ̶t̶h̶r̶o̶u̶g̶h̶ ̶t̶h̶e̶ ̶p̶i̶p̶e̶s̶ ̶t̶o̶ ̶o̶j̶e̶c̶t̶s̶ ̶(̶i̶s̶ ̶n̶o̶t̶ ̶a̶ ̶p̶r̶o̶b̶l̶e̶m̶ ̶b̶e̶c̶a̶u̶s̶e̶ ̶t̶h̶e̶ ̶t̶u̶b̶e̶ ̶i̶f̶ ̶t̶h̶e̶ ̶t̶u̶b̶e̶ ̶I̶ ̶c̶o̶n̶n̶e̶c̶t̶ ̶t̶h̶e̶ ̶c̶r̶u̶s̶h̶e̶r̶ ̶t̶o̶ ̶a̶ ̶b̶o̶x̶ ̶o̶r̶ ̶a̶ ̶h̶o̶p̶p̶e̶r̶ ̶t̶o̶ ̶t̶h̶e̶ ̶i̶r̶o̶n̶ ̶p̶o̶w̶d̶e̶r̶ ̶g̶o̶e̶s̶ ̶t̶h̶e̶r̶e̶ ̶a̶n̶d̶ ̶i̶s̶ ̶t̶h̶e̶n̶ ̶t̶a̶k̶e̶n̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶f̶u̶r̶n̶a̶c̶e̶)̶  (correct)

11)  ̶E̶l̶e̶c̶t̶r̶i̶c̶ ̶h̶e̶l̶m̶e̶t̶ ̶o̶n̶ ̶y̶o̶u̶ ̶c̶a̶n̶ ̶n̶o̶t̶ ̶p̶o̶s̶t̶ ̶u̶p̶d̶a̶t̶e̶s̶
̶ ̶ ̶ ̶ ̶ ̶ ̶o̶n̶ ̶e̶l̶e̶c̶t̶r̶i̶c̶ ̶p̶a̶n̶t̶s̶ ̶c̶a̶n̶ ̶n̶o̶t̶ ̶p̶o̶s̶t̶ ̶u̶p̶d̶a̶t̶e̶s̶
̶ ̶ ̶ ̶ ̶ ̶ ̶o̶n̶ ̶e̶l̶e̶c̶t̶r̶i̶c̶a̶l̶ ̶b̶o̶o̶t̶s̶ ̶y̶o̶u̶ ̶c̶a̶n̶ ̶o̶n̶l̶y̶ ̶e̶n̶t̶e̶r̶ ̶t̶h̶e̶ ̶"̶f̶a̶l̶l̶ ̶r̶e̶s̶i̶s̶t̶ ̶u̶p̶g̶r̶a̶d̶e̶"̶
̶ ̶ ̶ ̶ ̶ ̶ ̶o̶n̶ ̶e̶l̶e̶c̶t̶r̶i̶c̶ ̶C̶h̶e̶s̶t̶p̶l̶a̶t̶e̶ ̶w̶e̶ ̶j̶u̶s̶t̶ ̶g̶o̶ ̶t̶h̶e̶ ̶a̶g̶g̶i̶o̶r̶n̶m̶e̶n̶t̶i̶ ̶ ̶"̶j̶e̶t̶p̶a̶c̶k̶ ̶u̶p̶g̶r̶a̶d̶e̶"̶ ̶a̶n̶d̶ ̶ ̶"̶g̶l̶i̶d̶e̶ ̶u̶p̶g̶r̶a̶d̶e̶"̶   (in update , watch suggestion 5)

14)  ̶t̶h̶e̶ ̶u̶p̶d̶a̶t̶e̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶p̶i̶c̶k̶ ̶"̶l̶i̶g̶h̶t̶"̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶w̶o̶r̶k̶ ̶y̶o̶u̶ ̶c̶a̶n̶ ̶p̶u̶t̶ ̶i̶t̶ ̶n̶o̶ ̶l̶i̶g̶h̶t̶ ̶w̶h̶e̶n̶ ̶y̶o̶u̶ ̶d̶i̶g̶, s ̶h̶e̶d̶s̶ ̶l̶i̶g̶h̶t̶ ̶o̶n̶l̶y̶ ̶i̶f̶ ̶I̶ ̶u̶s̶e̶ ̶t̶h̶e̶ ̶n̶i̶g̶h̶t̶ ̶v̶i̶s̶i̶o̶n̶ ̶e̶n̶h̶a̶n̶c̶e̶m̶e̶n̶t̶ ̶t̶u̶r̶n̶e̶d̶ ̶o̶n̶ ̶a̶n̶d̶ ̶t̶h̶e̶n̶ ̶o̶f̶f̶ ̶,̶ ̶o̶r̶ ̶i̶f̶ ̶I̶ ̶u̶s̶e̶ ̶t̶h̶e̶ ̶e̶n̶h̶a̶n̶c̶e̶m̶e̶n̶t̶ ̶e̶x̶c̶a̶v̶a̶t̶i̶o̶n̶ ̶a̶r̶e̶a̶ ̶a̶c̶t̶i̶v̶a̶t̶e̶d̶ ̶a̶n̶d̶ ̶d̶e̶s̶p̶i̶t̶e̶ ̶t̶h̶i̶s̶ ̶I̶ ̶s̶t̶i̶l̶l̶ ̶f̶u̶l̶l̶y̶ ̶a̶c̶t̶i̶v̶e̶ ̶a̶p̶p̶r̶o̶a̶c̶h̶ ̶t̶o̶ ̶t̶h̶e̶ ̶r̶o̶c̶k̶ ̶b̶e̶f̶o̶r̶e̶ ̶i̶t̶ ̶l̶i̶g̶h̶t̶s̶ ̶u̶p̶ ̶e̶v̶e̶r̶y̶t̶h̶i̶n̶g̶  (Correct)

15)  ̶e̶l̶e̶c̶t̶r̶i̶c̶a̶l̶ ̶b̶o̶o̶t̶s̶ ̶d̶o̶ ̶n̶o̶t̶ ̶c̶o̶n̶s̶u̶m̶e̶ ̶e̶n̶e̶r̶g̶y̶ ̶u̶s̶i̶n̶g̶ ̶t̶h̶e̶i̶r̶ ̶s̶k̶i̶l̶l̶s̶  (correct)

16)  ̶A̶f̶t̶e̶r̶ ̶u̶s̶i̶n̶g̶ ̶n̶i̶g̶h̶t̶ ̶v̶i̶s̶i̶o̶n̶ ̶,̶ ̶w̶h̶e̶n̶ ̶y̶o̶u̶ ̶t̶u̶r̶n̶ ̶o̶f̶f̶ ̶t̶h̶e̶ ̶e̶x̶c̶a̶v̶a̶t̶e̶d̶ ̶a̶r̶e̶a̶ ̶r̶e̶m̶a̶i̶n̶s̶ ̶l̶i̶t̶  (correct)

20)  ̶T̶h̶e̶ ̶e̶l̶e̶c̶t̶r̶i̶c̶ ̶c̶r̶u̶c̶i̶b̶l̶e̶ ̶,̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶r̶e̶c̶e̶i̶v̶e̶ ̶m̶o̶r̶e̶ ̶e̶n̶e̶r̶g̶y̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶c̶r̶e̶a̶t̶i̶v̶e̶ ̶R̶F̶ ̶ ̶s̶t̶o̶r̶a̶g̶e̶   (Correct)

21)  ̶T̶h̶e̶ ̶p̶u̶m̶p̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶r̶e̶c̶e̶i̶v̶e̶ ̶e̶n̶e̶r̶g̶y̶ ̶f̶r̶o̶m̶ ̶C̶r̶e̶a̶t̶i̶v̶e̶ ̶R̶F̶ ̶S̶t̶o̶r̶a̶g̶e̶ ̶i̶n̶ ̶t̶h̶e̶ ̶n̶e̶t̶h̶e̶r̶   (correct)

22)  ̶i̶f̶ ̶i̶n̶ ̶s̶o̶l̶i̶d̶i̶f̶i̶e̶r̶ ̶b̶y̶ ̶m̶i̶s̶t̶a̶k̶e̶ ̶y̶o̶u̶ ̶d̶o̶ ̶g̶e̶t̶ ̶a̶ ̶l̶i̶q̶u̶i̶d̶ ̶t̶h̶a̶t̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶h̶a̶v̶e̶ ̶t̶h̶e̶ ̶f̶o̶r̶m̶ ̶o̶f̶ ̶b̶u̶l̶l̶i̶o̶n̶ ̶,̶ ̶a̶s̶ ̶t̶h̶e̶ ̶o̶b̶s̶i̶d̶i̶a̶n̶ ̶,̶ ̶a̶n̶d̶ ̶i̶s̶ ̶i̶n̶s̶e̶r̶t̶e̶d̶ ̶l̶i̶n̶g̶o̶t̶ ̶m̶o̶d̶e̶ ̶,̶ ̶t̶h̶e̶ ̶s̶o̶l̶i̶d̶i̶f̶i̶e̶r̶ ̶w̶o̶r̶k̶ ̶,̶ ̶t̶r̶y̶ ̶a̶l̶s̶o̶ ̶t̶o̶ ̶m̶a̶k̶e̶ ̶t̶h̶e̶ ̶i̶n̶g̶o̶t̶ ̶a̶n̶d̶ ̶c̶o̶n̶s̶u̶m̶e̶s̶ ̶l̶i̶q̶u̶i̶d̶ ̶a̶n̶d̶ ̶o̶u̶t̶g̶o̶i̶n̶g̶ ̶t̶h̶e̶r̶e̶ ̶i̶s̶ ̶n̶o̶t̶h̶i̶n̶g̶.̶  (correct)

23)  ̶T̶h̶e̶ ̶l̶i̶q̶u̶i̶d̶ ̶i̶n̶s̶e̶r̶t̶e̶d̶ ̶i̶n̶ ̶t̶a̶n̶k̶:̶ ̶i̶r̶o̶n̶,̶ ̶g̶o̶l̶d̶,̶ ̶d̶i̶a̶m̶o̶n̶d̶ ̶a̶n̶d̶ ̶c̶r̶e̶a̶t̶i̶v̶e̶ ̶o̶n̶c̶e̶ ̶s̶a̶v̶e̶d̶ ̶a̶n̶d̶ ̶t̶u̶r̶n̶e̶d̶ ̶o̶f̶f̶ ̶t̶h̶e̶ ̶g̶a̶m̶e̶ ̶w̶h̶e̶n̶ ̶y̶o̶u̶ ̶f̶a̶l̶l̶ ̶a̶r̶e̶ ̶g̶o̶n̶e̶ ̶a̶n̶d̶ ̶i̶f̶ ̶y̶o̶u̶ ̶t̶r̶y̶ ̶t̶o̶ ̶i̶n̶s̶e̶r̶t̶ ̶a̶n̶o̶t̶h̶e̶r̶ ̶o̶n̶e̶ ̶o̶r̶ ̶s̶p̶r̶e̶a̶d̶ ̶l̶i̶q̶u̶i̶d̶ ̶t̶h̶a̶t̶ ̶w̶a̶s̶ ̶t̶h̶e̶r̶e̶ ̶b̶e̶f̶o̶r̶e̶ ̶i̶t̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶g̶o̶ ̶t̶o̶ ̶m̶o̶s̶t̶ ̶8̶0̶0̶0̶m̶b̶ ̶a̶s̶ ̶a̶l̶s̶o̶ ̶s̶a̶i̶t̶h̶ ̶@̶s̶h̶o̶r̶t̶y̶b̶s̶d̶ ̶i̶n̶ ̶t̶h̶i̶s̶ ̶p̶o̶s̶t̶ ̶#̶2̶1̶2̶ (Correct)

25)  ̶T̶h̶e̶ ̶d̶i̶a̶m̶o̶n̶d̶ ̶t̶a̶n̶k̶,̶ ̶h̶a̶s̶ ̶t̶h̶e̶ ̶w̶r̶o̶n̶g̶ ̶c̶a̶p̶a̶c̶i̶t̶y̶ ̶l̶i̶m̶i̶t̶.̶ (Correct)

26)  ̶c̶r̶e̶a̶t̶i̶v̶e̶ ̶R̶F̶ ̶s̶t̶o̶r̶a̶g̶e̶,̶ ̶i̶f̶ ̶y̶o̶u̶ ̶b̶r̶e̶a̶k̶ ̶i̶t̶ ̶,̶ ̶a̶n̶d̶ ̶t̶h̶e̶n̶ ̶r̶e̶p̶o̶s̶i̶t̶i̶o̶n̶e̶d̶ ̶d̶o̶e̶s̶ ̶n̶o̶t̶ ̶w̶o̶r̶k̶,̶ ̶i̶f̶ ̶I̶ ̶l̶e̶a̶v̶e̶ ̶t̶h̶e̶ ̶g̶a̶m̶e̶ ̶a̶n̶d̶ ̶r̶e̶t̶u̶r̶n̶ ̶w̶o̶r̶k̶s̶ ̶a̶g̶a̶i̶n̶ ̶a̶ ̶'̶ ̶l̶a̶s̶t̶ ̶t̶i̶m̶e̶.̶  (Correct)

27)  ̶V̶e̶r̶s̶i̶o̶n̶,̶ ̶2̶.̶4̶.̶1̶-̶B̶1̶2̶8̶,̶ ̶I̶ ̶c̶a̶n̶ ̶n̶o̶t̶ ̶e̶n̶t̶e̶r̶ ̶t̶h̶e̶ ̶w̶o̶r̶l̶d̶ ̶c̶r̶a̶s̶h̶e̶s̶ ̶a̶f̶t̶e̶r̶ ̶d̶e̶l̶e̶t̶i̶n̶g̶ ̶f̶i̶r̶s̶t̶ ̶t̶h̶e̶ ̶c̶o̶n̶f̶i̶g̶u̶r̶a̶t̶i̶o̶n̶ ̶f̶i̶l̶e̶s̶.̶  (Correct)

31)   ̶T̶h̶e̶ ̶e̶l̶e̶c̶t̶r̶o̶m̶a̶g̶n̶e̶t̶ ̶i̶n̶ ̶a̶d̶d̶i̶t̶i̶o̶n̶ ̶t̶o̶ ̶a̶t̶t̶r̶a̶c̶t̶i̶n̶g̶ ̶t̶h̶e̶ ̶o̶b̶j̶e̶c̶t̶s̶ ̶n̶o̶w̶ ̶a̶l̶s̶o̶ ̶a̶t̶t̶r̶a̶c̶t̶s̶ ̶c̶r̶e̶e̶p̶e̶r̶ (implementation)

---

@pauljoda , @Dyonovan  you read a little bit of what I'm writing ? XD

**Comment by pauljoda** [comment]
For 11, at the moment those are the only upgrades I've implemented for the armor. The armor is still VERY early stages. At the moment, we are just playing around with the system to make sure it is stable before expanding into further upgrades. Feel free to leave suggestions for upgrades, I plan on wrapping the vanilla potion effects for the armor and removing the effect display. So things like speed, jump boost, regen, etc will be implemented at some point. Thanks for the very up to date thread though, helps us keep things working

**Comment by JupiterJoe** [comment]
For 12 and 12a have been reported already in #196 
For 31 this is a feature explained [in this video](https://youtu.be/VeDT01tpWuM?t=31m42s)

**Comment by mario-88ce** [comment]
Well dear @JupiterJoe except that my post I created long before you from what you can see ^^ but then my post is a kind of diary for what you will have to correct it in the future I delete things just correct trim bugs and add the ones that are new , when it will settle the 12 to delete :)
