### ISSUE TITLE
Electric centrifuge doesn't output molten tin

### ISSUE THREAD

**Issue by Colgaldy** [TeamBR-Modding/NeoTech#189]
What Version of NeoTech are you using:2.4.0a

If possible, did you break and replace the block:Yes

Please Pastebin.com the crash Report and put link here:N/A
In my experience when converting dirty molten tin to molten tin in the electric centrifuge for the thermal binder the centrifuge will output the lava through pipes but not the molten tin, is this a known issue?

**Comment by pauljoda** [comment]
Is it producing the tin? If it is producing it and not extracting on the pipes it must be a pipe issue

**Comment by pauljoda** [comment]
Actually, I think I know exactly what this issue is. Let me see what I can do
