### ISSUE TITLE
Crash with v2.4.0a

### ISSUE THREAD

**Issue by jrpoints** [TeamBR-Modding/NeoTech#190]
What Version of NeoTech are you using:2.4.0a

If possible, did you break and replace the block:no time because of crash

Please Pastebin.com the crash Report and put link here:http://pastebin.com/YKGaSeLT

Not sure if multipart or your crash but it seems diamond tanks in this world are tesselating?
Might be able to go in and mcedit them out. But for now I'm just going to go back to older version.

**Comment by pauljoda** [comment]
Are you using architecture craft?
