### ISSUE TITLE
[Request] IMC Support for the Fertilizer Blacklist

### ISSUE THREAD

**Issue by TehNut** [TeamBR-Modding/NeoTech#192]
So I can do `FMLInterModComms.sendMessage("neotech", "blacklistFertilizer", "mymod:myBlock");` instead of having to include 3 extra deps in my workspace (Neotech, Bookshelf, and MCMP) to blacklist a single block.

I was going to do this with the initial PR that added the blacklist, but never got around to it. Now that everything has moved fully over to Scala, I don't even know how to do it, else I would.

**Comment by pauljoda** [comment]
Yeah no problem
