### ISSUE TITLE
Unable to use Electric Crucible

### ISSUE THREAD

**Issue by zepheris** [TeamBR-Modding/NeoTech#195]
What Version of NeoTech are you using: neotech-1.8.9-2.4.0a
If possible, did you break and replace the block: Yes

Its not crashing, but I'm unable to use the Electric Crucible to melt tin as its not allowing me to insert the ore. I've tried to insert ore blocks, ingots, dusts, and blocks of tin. I suspect its a conflict with a mod I have installed. Below is a screenshot that shows Tinkers' Construct when I hover over the dirty molten bucket of tin.

![image](https://cloud.githubusercontent.com/assets/4251071/13485377/7189be78-e0c4-11e5-9753-0c0d70a7c1b8.png)

Note: I can melt Iron and Stone with no issues.

I'm not sure how I can fix this. Any ideas?

**Comment by Dyonovan** [comment]
Delete the NeoTech config directory and restart mc. It will re create itself.

Going to close as I'm pretty sure this will fix it, but if not just reopen and ill take a look.
