### ISSUE TITLE
Molten metals buckets have weird name

### ISSUE THREAD

**Issue by JupiterJoe** [TeamBR-Modding/NeoTech#196]
NeoTech 2.4.0a

![2016-03-03_20 02 42](https://cloud.githubusercontent.com/assets/17516080/13505803/2a66db0e-e17b-11e5-9fe6-f7afcf86c362.png)

**Comment by Dyonovan** [comment]
Looks like another mod is making buckets and overwriting ours. What other mods do you have installed?

**Comment by JupiterJoe** [comment]
Forge 1764
bookshelf 2.3.5
buildcraft 7.2.0-pre12
buildcraft compat 7.2.0-pre12-compat1
iron backpacks 2.0.5
Waila 1.6.0-B3
MCMultipart 1.0.7
JEI 2.28.6

**Comment by pauljoda** [comment]
This seems to be a forge issue. Please try the latest version

**Comment by JupiterJoe** [comment]
with only bookshelf, multipart, neotech on latest forge (11.15.1.1764) issue still exists

**Comment by pauljoda** [comment]
What language are you using?

**Comment by JupiterJoe** [comment]
default en-us
somehow my forge install does not have lang entry for filled forge bucket
it does work from dev environment

**Comment by pauljoda** [comment]
That is strange. Might be a forge issue then

**Comment by pauljoda** [comment]
I'm closing this for now as there really isn't much we can do to fix it, something is wrong with the forge you are using
