### ISSUE TITLE
Crucible Processing When Another Liquid Is present

### ISSUE THREAD

**Issue by Darkosto** [TeamBR-Modding/NeoTech#199]
What Version of NeoTech are you using: 1.8.9-2.4.0a

If possible, did you break and replace the block: No

Hello! I've run across an issue today, while liquid "Dirty Gold Ore" was in my Crucible waiting to export, the copper ore began processing and using power. Once it finished the progress, it restarted and kept going. This seems to happen when any type of liquid is in the buffer and another type of ore is in the slot to be liquefied.

https://sx.artdude.uk/hotlink-ok/darkosto/oqBt-e9440-1457068184.png

I tested it with another set of ores and ran into the same issue: 

https://sx.artdude.uk/hotlink-ok/darkosto/0rws-66aec-1457068414.png

Thanks for looking at this :)

**Comment by pauljoda** [comment]
Well that isn't supposed to happen. Thought I had checks in place for this. I will do some work on this tomorrow.  Thanks for the report

**Comment by mario-88ce** [comment]
if I can I intrude in 2.0.4a - B90 version of this issue of the exchange of fluids names there it may be some mod that conflicts ? I am using a version of minecraft with only the mod installed nanotech

**Comment by pauljoda** [comment]
Aha, yep seems I forgot to do a fluid match on the canProcess, it was getting caught on the final process method but not during checks. I'll fix that real quick and push a fix
