### ISSUE TITLE
Lag Issue in game causes Powdered Gold in Electric Furnace to vanish

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#20]
I had an issue where the game would lag so much that I would have to manually quit the game and when I come back all the powdered gold I collected from the crusher just vanished except for the powdered gold inside a chest and my inventory.

**Comment by Dyonovan** [comment]
Should be fixed in rewrite. Initial release later today

**Comment by DatrixTHLK** [comment]
Thanks for response. I feel like I have to say this incase someone decides to tell me off for being insensitive to the mod author because of their over-sensitivity.
