### ISSUE TITLE
Gold Fluid Tank size wrong when placed

### ISSUE THREAD

**Issue by shortybsd** [TeamBR-Modding/NeoTech#200]
What Version of NeoTech are you using:
NeoTech-1.8.9-2.4.0a
If possible, did you break and replace the block:
Yes.
Please Pastebin.com the crash Report and put link here:
N/A

When hovering over a gold fluid tank it shows it will hold 16 buckets, once placed it reverts back to only 8 buckets worth max.

**Comment by Dyonovan** [comment]
Duplicate #197 

Already fixed for next release: Thanks for the report though
