### ISSUE TITLE
Color blindness

### ISSUE THREAD

**Issue by Zhaulus** [TeamBR-Modding/NeoTech#202]
What Version of NeoTech are you using: version included in unstable .36

I find it difficult to tell the difference between smooth stone and your new lead ore, perhaps a deeper colour. More difficult in darker areas

**Comment by pauljoda** [comment]
This is something I've noticed as well. Not hard to fix I'll get to it eventually I promise

**Comment by Zhaulus** [comment]
Thank you, mod is coming along nicely
