### ISSUE TITLE
Crash working with Molten Tin 2.4.1

### ISSUE THREAD

**Issue by Towsty** [TeamBR-Modding/NeoTech#203]
What Version of NeoTech are you using:
    2.4.1

If possible, did you break and replace the block:
    Not possible, world crashes as chunks containing issues are loaded

Please Pastebin.com the crash Report and put link here:
    Crash Report: http://pastebin.com/nFNDxbAR
    Server Log: https://drive.google.com/file/d/0B4UhGIFXzCO6SjV3amIxekZNdnc/view?usp=sharing

I've been trying to use the Thermal Binder but was having issues getting the Tin into it in SMP. 
I went into creative, put down a binder, and a centrifuge, and attempted to move some dirty molten tin from a tank into the centrifuge using the fluid pipes. As soon as the fluid moves to the centrifuge the world crashes.

The reason I did this in creative was because just tin ore, and tin ingots in the crucible was not working either. I've tried resetting the recipes, and I've tested this on a fresh world as well. Resetting the recipes seems to remove all Neotech fluid from pipes and containers so I am able to load things back up, but still unable to process the tin.

**Comment by Dyonovan** [comment]
Try deleting the Neotech config directory and let it recreate itself

**Comment by Towsty** [comment]
Did that, it removes the liquid which allows the chunk to load again, but the error persists. Any other thoughts?

**Comment by pauljoda** [comment]
Try the latest on jenkins

**Comment by Towsty** [comment]
Just tried the latest from Jenkins, (B99) updated bookshelf to the latest from jenkins as well and the crash when moving the tin into the centrifuge is fixed. Oddly enough, even after I deleted the configs again it doesn't seem like tin is registered in the crucibles recipe json at all (B99 or release version from curse). I added it to the json and all is well. 

Thanks,

**Comment by Towsty** [comment]
I may have spoke too soon, is there a version of clean (or whatever not dirty tin will be) tin that is even accessible? There does not seem to be one in the creative menu and running it through the centrifuge only seems to make lava.

**Comment by pauljoda** [comment]
Can you post a list of mods you have installed as well as the latest FML console log? Not sure why you are having this issue

**Comment by Towsty** [comment]
Sorry for the drive shares, they're just too big for pastebin/chrome or the like, makes my comp freak out.

Server Log: https://drive.google.com/file/d/0B4UhGIFXzCO6OWl6WkdFRGRlX3M/view?usp=sharing
Client Log: https://drive.google.com/file/d/0B4UhGIFXzCO6UU5UNjJpSk5FajA/view?usp=sharing

<details> 
<summary>

Mod List</summary>


AuraCascade-592.jar
Bagginses-1.8.9-2.1.5b.jar
BaseMetals-1.7.3.jar
bdlib-1.10.0.23-mc1.8.9.jar
BetterAchievements-1.8.9-0.1.1.jar
BetterThanBunnies-1.8.9-1.0.1.jar
BiomesOPlenty-1.8.9-3.0.0.1894-universal.jar
BloodMagic-1.8.9-2.0.0-253-ss.jar
Bookshelf-API-1.8.9-2.3.6-B13.jar
Botania.r1.8-248-MC1.8-0.6.1.jar
buildcraft-7.2.0-pre11.jar
BuildingBricks-1.8.9-1.3.2.jar
Chameleon-1.8.9-0.2.1.jar
Charset-0.2.1-945baf5589832f727c42cf77.jar
Chisel-MC1.8.9-0.0.2.6.jar
chiselsandbits-mc1.8.9-v1.8.11.jar
CompassCoords-1.8.9-0.2.6.jar
ComputerCraft1.78.jar
craftingtweaks-mc1.8.9-3.0.41.jar
CraftTweaker-Customized-1.8.8-3.0.1.jar
CustomMainMenu-MC1.8.9-2.0.jar
DynamicSurroundings-1.8.9-2.0.3.2.jar
E-Flux-1.8.9-1.0Alpha.106.jar
ElecCore-1.8.9-1.4.228.jar
ElectricAdvantage-1.1.1.jar
EnderTanks-1.8.9-1.2.1.jar
ezstorage-1.8.9-1.2.4.jar
FastLeafDecay-1.8-1.6.jar
flatcoloredblocks-mc1.8.9-v1.6.jar
FTBLib-1.8.9-2.0.2.jar
FTBUtilities-1.8.9-2.0.2.jar
Furnus-1.8.9-1.7.jar
generators-0.9.19.3-mc1.8.9.jar
graves-1.8.9-b39-universal.jar
hopperducts-mc1.8.8-1.4.6.jar
HydCraft-1.8.9-3.1.65-universal.jar
Ice-1.1.2.jar
IGW-Mod-1.8.9-1.2.3-3-universal.jar
intangible-1.8.9-0.0.23.jar
inventorysorter-1.8.9-0.7.4+26.jar
InventoryTweaks-1.60-beta-33.jar
ironchest-1.8.9-6.0.125.770.jar
JEIAddons_1.8.9-0.12.0.57.jar
jei_1.8.9-2.28.1.162.jar
journeymap-1.8.8-5.1.3-unlimited.jar
JustEnoughResources-1.8.9-0.3.4.jar
k4lib-1.8.9-1.0.16-universal.jar
LLOverlayReloaded-1.0.4-mc1.8.8.jar
Mantle-1.8.9-0.7.jar
mcjtylib-1.8.9-1.8.1beta6.jar
MCMultiPart-1.0.7-universal.jar
MmmMmmMmmMmm-1.9b.jar
Morpheus-1.8.9-2.0.58.jar
MouseTweaks-2.6.0-mc1.8.9.jar
NeoTech-1.8.9-2.4.1-B99.jar
OptiFine_1.8.9_HD_U_H2.jar
OreDictionaryConverter-1.7.2.jar
PlayerRugs-1.8.8-1.2.0.jar
PneumaticCraft-1.8.9-1.13.6-universal.jar
PowerAdvantage-1.5.1.jar
ProgressiveAutomation-1.8.9-1.6.34.jar
Psi-beta-14.jar
quantumflux-1.8.9-2.0.0.jar
RandomThings-MC1.8.9-3.6.2.jar
RebornCore-1.8.9-1.4.3.20-universal.jar
ResourceLoader-MC1.8.8-1.4.jar
rftools-1.8.9-4.22beta18.jar
ShetiPhianCore-1.8.9-3.1.0.jar
simpleretrogen-1.8.9-2.2.2+3.jar
SteamAdvantage-1.5.2.jar
StorageDrawers-1.8.9-2.4.1.jar
StorageNetwork-1.8.9-1.7.2.jar
TConstruct-1.8.9-2.0.2.jar
TechReborn-1.8.9-0.7.11.61-universal.jar
Thaumcraft-1.8.9-5.1.6.jar
ThaumicInfusion-1.8.9-4.8.jar
Waila-1.6.0-B3_1.8.8.jar
Wawla-1.4.7-1.8+.jar 
</details>

**Comment by pauljoda** [comment]
Can you try with just our mod and bookshelf? There may be a mod messing with our metals

**Comment by Towsty** [comment]
Definitely is something conflicting, everything works fine with just your mods. I'll see if I can't find out what, thanks for the help.
