### ISSUE TITLE
item interface not connecting to any modded furnace Only vanilla

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#204]
What Version of NeoTech are you using:

2.4.1

If possible, did you break and replace the block:
yes many times

updates and now the interface pipse don't show a graphic so you have to guess which side your setting things to use 

they no longer connect to my mod furnus or any other furnas except vanilla

**Comment by JupiterJoe** [comment]
furnus mod does not use IItemHandler capability system from Forge yet.
NeoTech uses this system to connect item pipes to inventories.
Tell furnus mod dev to use IItemHandler capability it will solve your problem.

**Comment by tiarnia** [comment]
its not just the furnus mod other mods have furnaces too none of them work i am currently testing to see if they connect to other modded machines 

the issue with the gui is not helping because i cant see the pipe direction
