### ISSUE TITLE
when i try to connect to my server

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#205]
What Version of NeoTech are you using:
2.4.1
If possible, did you break and replace the block:
no
Please Pastebin.com the crash Report and put link here: http://pastebin.com/MhpNbd2G

**Comment by pauljoda** [comment]
Seems to be a strange loading order issue. I'll go ahead and put in some extra checks just to be safe though I'm not sure how this could even create a NPE. Better safe than sorry
