### ISSUE TITLE
Tile.fluidgenerator.tryinput

### ISSUE THREAD

**Issue by Phonavis** [TeamBR-Modding/NeoTech#206]
What Version of NeoTech are you using: 2.4.0a

If possible, did you break and replace the block: Well...

Please Pastebin.com the crash Report and put link here:
http://pastebin.com/dpgkEKFa

Description:
I attempted to input lava from an ender tank and that's what happened, and yes it has happened multiple times, each time corrupting the world.

**Comment by pauljoda** [comment]
It seems a mod is allowing for a null resource to be sent, strange but I suppose it should be checked. Put in a catch just to be safe. Try the latest on jenkins if you want to see if that fixed it
