### ISSUE TITLE
Ticking Block Entity Server Crash

### ISSUE THREAD

**Issue by MisterShawn** [TeamBR-Modding/NeoTech#208]
What Version of NeoTech are you using: 1.8.9-2.4.1

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: http://pastebin.com/raw/ZHHYtyjT

**Comment by pauljoda** [comment]
This has been fixed in a later commit. Download the latest versions from Jenkins if you need a new build https://github.com/TeamBR-Modding/NeoTech/commit/f49db695bf2e86bdd4c0b88a5a692a3680db3135
