### ISSUE TITLE
Server Tick Loop

### ISSUE THREAD

**Issue by MisterShawn** [TeamBR-Modding/NeoTech#209]
What Version of NeoTech are you using: 1.8.9-2.4.1-B113

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: http://pastebin.com/raw/SXCqxd1J

I was told to download from the Jenkins because my previous crash was already fixed, but now I have a new crash. I wouldn't normally post a bug report on an unreleased version, but I'm stuck with a server that won't start and users who'd like to play.

**Comment by Dyonovan** [comment]
Did you also install the latest version of Bookshelf from Jenkins?

**Comment by MisterShawn** [comment]
I did not. Sorry about that.
