### ISSUE TITLE
Game crashes due to NPE when tesselating NeoTech's "BlockPipeBasicItem"

### ISSUE THREAD

**Issue by mahashel** [TeamBR-Modding/NeoTech#21]
I have been using version 1.6 of this mod extensively over the past few weeks on MC1.8(Forge) without issue until I started using item pipes.  At this point I have both basic and advanced pipes in my game, which began routinely crashing, as described below.  (Null Pointer Exception while tesselating basic item pipe)
Every crash log references this same NPE in the stack trace.
(Mods loaded: Forge/FML, fluxducts, progressiveAutomation, and neoTech)

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 7/17/15 7:31 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
    at com.dyonovan.neotech.common.blocks.pipe.item.BlockPipeBasicItem.drawExtras(BlockPipeBasicItem.java:39)
    at com.dyonovan.neotech.client.modelfactory.models.ModelPipe.func_177550_a(ModelPipe.java:122)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178258_b(BlockModelRenderer.java:119)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:44)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:34)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:178)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:120)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:882)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1267)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.dyonovan.neotech.common.blocks.pipe.item.BlockPipeBasicItem.drawExtras(BlockPipeBasicItem.java:39)
    at com.dyonovan.neotech.client.modelfactory.models.ModelPipe.func_177550_a(ModelPipe.java:122)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178258_b(BlockModelRenderer.java:119)

-- Block model being tesselated --
Details:
    Block: neotech:basicItemPipe
    Block location: World: (202,64,251), Chunk: (at 10,4,11 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Using AO: false
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:44)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:34)

-- Block being tesselated --
Details:
    Block type: ID #240 (tile.neotech:basicItemPipe // com.dyonovan.neotech.common.blocks.pipe.item.BlockPipeBasicItem)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (202,64,251), Chunk: (at 10,4,11 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:178)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:120)
    at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:882)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1267)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['mahashel'/10739, l='MpServer', x=200.50, y=64.77, z=267.98]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -80.00,64.00,92.00 - World: (-80,64,92), Chunk: (at 0,4,12 in -5,5; contains blocks -80,0,80 to -65,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 133005026 game time, 136361411 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 110 total; [EntityPlayerSP['mahashel'/10739, l='MpServer', x=200.50, y=64.77, z=267.98], EntityPig['Pig'/10752, l='MpServer', x=180.81, y=85.00, z=238.63], EntityItem['item.item.egg'/10753, l='MpServer', x=185.94, y=85.00, z=240.06], EntityBat['Bat'/10755, l='MpServer', x=222.65, y=26.30, z=256.17], EntityBat['Bat'/10756, l='MpServer', x=232.42, y=26.19, z=251.01], EntitySkeleton['Skeleton'/10757, l='MpServer', x=221.56, y=62.30, z=248.34], EntityBat['Bat'/10759, l='MpServer', x=210.75, y=25.10, z=286.75], EntitySquid['Squid'/10760, l='MpServer', x=219.40, y=62.53, z=295.20], EntitySquid['Squid'/10761, l='MpServer', x=213.06, y=56.97, z=296.60], EntitySquid['Squid'/10762, l='MpServer', x=222.92, y=61.28, z=285.77], EntitySquid['Squid'/10763, l='MpServer', x=215.16, y=61.00, z=273.13], EntityCreeper['Creeper'/10764, l='MpServer', x=201.50, y=11.00, z=239.50], EntityCreeper['Creeper'/10765, l='MpServer', x=238.50, y=10.00, z=270.50], EntitySquid['Squid'/10766, l='MpServer', x=161.69, y=54.16, z=274.72], EntityCreeper['Creeper'/10767, l='MpServer', x=167.81, y=90.00, z=253.84], EntityCow['Cow'/10768, l='MpServer', x=174.75, y=85.00, z=241.03], EntityCow['Cow'/10769, l='MpServer', x=173.44, y=85.00, z=243.63], EntityCow['Cow'/10770, l='MpServer', x=173.44, y=85.00, z=241.13], EntityChicken['Chicken'/10771, l='MpServer', x=186.78, y=85.00, z=238.19], EntityItem['item.item.egg'/10772, l='MpServer', x=186.59, y=85.00, z=238.72], EntityPig['Pig'/10773, l='MpServer', x=178.44, y=85.00, z=238.44], EntityPig['Pig'/10774, l='MpServer', x=181.50, y=85.00, z=243.84], EntityChicken['Chicken'/10775, l='MpServer', x=184.00, y=85.00, z=238.19], EntityChicken['Chicken'/10776, l='MpServer', x=185.72, y=85.00, z=244.19], EntityEnderman['Enderman'/10777, l='MpServer', x=233.50, y=16.00, z=250.50], EntityBat['Bat'/10778, l='MpServer', x=222.83, y=27.23, z=245.99], EntitySkeleton['Skeleton'/10779, l='MpServer', x=227.50, y=23.00, z=283.50], EntitySkeleton['Skeleton'/10780, l='MpServer', x=240.03, y=31.00, z=281.41], EntitySkeleton['Skeleton'/10781, l='MpServer', x=225.34, y=28.00, z=277.09], EntitySkeleton['Skeleton'/10782, l='MpServer', x=236.13, y=28.00, z=276.59], EntitySkeleton['Skeleton'/10783, l='MpServer', x=238.50, y=28.00, z=276.50], EntitySkeleton['Skeleton'/10784, l='MpServer', x=217.50, y=25.00, z=296.50], EntityBat['Bat'/10785, l='MpServer', x=227.13, y=23.55, z=290.55], EntityBat['Bat'/10786, l='MpServer', x=219.34, y=23.10, z=293.75], EntityMinecartEmpty['entity.MinecartRideable.name'/10787, l='MpServer', x=166.16, y=74.06, z=233.50], EntityCow['Cow'/10788, l='MpServer', x=173.44, y=85.00, z=239.53], EntityCow['Cow'/10789, l='MpServer', x=174.69, y=85.00, z=238.44], EntityZombie['Zombie'/10790, l='MpServer', x=236.50, y=18.00, z=296.50], EntityBat['Bat'/10791, l='MpServer', x=219.66, y=25.21, z=289.63], EntityBat['Bat'/10792, l='MpServer', x=238.72, y=19.48, z=271.45], EntityCreeper['Creeper'/10793, l='MpServer', x=236.50, y=19.00, z=299.50], EntityZombie['Zombie'/10794, l='MpServer', x=237.50, y=18.00, z=296.50], EntitySquid['Squid'/10795, l='MpServer', x=234.84, y=58.50, z=294.00], EntitySkeleton['Skeleton'/10796, l='MpServer', x=192.50, y=23.00, z=210.50], EntityBat['Bat'/10797, l='MpServer', x=199.49, y=12.17, z=194.50], EntityZombie['Zombie'/10798, l='MpServer', x=147.84, y=87.00, z=244.44], EntitySkeleton['Skeleton'/10799, l='MpServer', x=189.50, y=14.00, z=213.50], EntitySpider['Spider'/10800, l='MpServer', x=221.81, y=21.00, z=211.00], EntitySkeleton['Skeleton'/10801, l='MpServer', x=223.47, y=21.00, z=210.28], EntityZombie['Zombie'/10802, l='MpServer', x=222.97, y=21.00, z=212.44], EntitySquid['Squid'/10804, l='MpServer', x=211.84, y=50.88, z=209.66], EntitySkeleton['Skeleton'/10805, l='MpServer', x=248.47, y=28.00, z=247.88], EntitySkeleton['Skeleton'/10806, l='MpServer', x=254.50, y=24.00, z=253.50], EntitySkeleton['Skeleton'/10807, l='MpServer', x=255.09, y=23.00, z=279.47], EntitySpider['Spider'/10808, l='MpServer', x=162.44, y=19.00, z=306.25], EntityBat['Bat'/10809, l='MpServer', x=221.05, y=16.06, z=207.31], EntityBat['Bat'/10810, l='MpServer', x=224.72, y=25.10, z=208.78], EntitySquid['Squid'/10811, l='MpServer', x=232.81, y=49.13, z=214.00], EntityBat['Bat'/10812, l='MpServer', x=240.59, y=28.10, z=233.75], EntityEnderman['Enderman'/10813, l='MpServer', x=268.50, y=15.00, z=271.50], EntityZombie['Zombie'/10814, l='MpServer', x=263.50, y=31.00, z=257.50], EntitySkeleton['Skeleton'/10815, l='MpServer', x=256.50, y=24.00, z=256.50], EntityZombie['Zombie'/10816, l='MpServer', x=265.50, y=31.00, z=259.50], EntityZombie['Zombie'/10817, l='MpServer', x=257.50, y=24.00, z=256.50], EntityCreeper['Creeper'/10818, l='MpServer', x=179.50, y=29.00, z=202.50], EntityBat['Bat'/10819, l='MpServer', x=185.14, y=29.55, z=195.57], EntityZombie['Zombie'/10821, l='MpServer', x=263.28, y=15.26, z=276.28], EntityZombie['Zombie'/10822, l='MpServer', x=270.06, y=45.00, z=280.59], EntitySkeleton['Skeleton'/10823, l='MpServer', x=159.50, y=19.00, z=309.50], EntitySkeleton['Skeleton'/10824, l='MpServer', x=156.94, y=19.00, z=307.47], EntitySpider['Spider'/10825, l='MpServer', x=145.50, y=74.00, z=211.50], EntitySpider['Spider'/10826, l='MpServer', x=148.50, y=74.00, z=208.50], EntityBat['Bat'/10827, l='MpServer', x=135.51, y=16.09, z=228.75], EntityZombie['Zombie'/10828, l='MpServer', x=129.56, y=80.00, z=239.75], EntityZombie['Zombie'/10829, l='MpServer', x=142.34, y=80.00, z=236.34], EntitySquid['Squid'/10830, l='MpServer', x=138.38, y=56.88, z=302.13], EntitySquid['Squid'/10831, l='MpServer', x=138.03, y=58.81, z=311.78], EntitySkeleton['Skeleton'/10832, l='MpServer', x=133.50, y=79.00, z=213.50], EntityZombie['Zombie'/10833, l='MpServer', x=155.50, y=74.00, z=200.50], EntitySquid['Squid'/10835, l='MpServer', x=248.69, y=53.44, z=207.94], EntitySquid['Squid'/10836, l='MpServer', x=247.69, y=57.81, z=211.44], EntityChicken['Chicken'/10838, l='MpServer', x=277.72, y=62.53, z=263.94], EntitySkeleton['Skeleton'/10839, l='MpServer', x=271.50, y=18.00, z=310.50], EntitySquid['Squid'/10841, l='MpServer', x=262.91, y=47.22, z=316.47], EntitySquid['Squid'/10842, l='MpServer', x=263.00, y=50.59, z=316.66], EntitySkeleton['Skeleton'/10844, l='MpServer', x=184.69, y=35.00, z=343.47], EntityCreeper['Creeper'/10845, l='MpServer', x=176.31, y=36.00, z=341.00], EntitySkeleton['Skeleton'/10852, l='MpServer', x=217.50, y=29.00, z=346.50], EntityCreeper['Creeper'/10853, l='MpServer', x=120.47, y=25.00, z=296.63], EntitySkeleton['Skeleton'/10856, l='MpServer', x=278.50, y=18.00, z=299.44], EntitySkeleton['Skeleton'/10857, l='MpServer', x=272.84, y=20.00, z=298.50], EntitySkeleton['Skeleton'/10858, l='MpServer', x=234.13, y=26.00, z=346.41], EntitySkeleton['Skeleton'/10859, l='MpServer', x=233.69, y=25.00, z=347.47], EntitySkeleton['Skeleton'/10861, l='MpServer', x=153.31, y=74.00, z=193.25], EntityZombie['Zombie'/10944, l='MpServer', x=216.50, y=16.00, z=208.50], EntityZombie['Zombie'/10946, l='MpServer', x=211.50, y=18.00, z=327.50], EntityZombie['Zombie'/10949, l='MpServer', x=195.50, y=35.00, z=207.50], EntityItem['item.item.egg'/10957, l='MpServer', x=183.38, y=85.00, z=243.91], EntitySkeleton['Skeleton'/10740, l='MpServer', x=206.50, y=16.00, z=261.50], EntityItem['item.tile.stoneSlab.stone'/10741, l='MpServer', x=207.72, y=76.00, z=267.78], EntityBat['Bat'/10742, l='MpServer', x=223.26, y=28.03, z=245.94], EntitySquid['Squid'/10743, l='MpServer', x=216.99, y=61.47, z=274.77], EntityZombie['Zombie'/10744, l='MpServer', x=170.97, y=39.00, z=256.41], EntityCow['Cow'/10745, l='MpServer', x=174.31, y=85.00, z=242.44], EntityPig['Pig'/10746, l='MpServer', x=178.44, y=85.00, z=242.78], EntityChicken['Chicken'/10747, l='MpServer', x=184.94, y=85.00, z=244.78], EntityChicken['Chicken'/10748, l='MpServer', x=184.88, y=85.00, z=243.00], EntityPig['Pig'/10749, l='MpServer', x=178.44, y=85.00, z=244.53], EntityChicken['Chicken'/10750, l='MpServer', x=183.25, y=85.00, z=238.97], EntityPig['Pig'/10751, l='MpServer', x=179.59, y=85.00, z=243.91]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 170858960 bytes (162 MB) / 467804160 bytes (446 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1491 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1491.jar) 
    UCHIJA  Forge{11.14.3.1491} [Minecraft Forge](forge-1.8-11.14.3.1491.jar) 
    UCHIJA  fluxducts{1.0.2} [Flux Ducts](fluxducts-mc1.8-1.0.2.jar) 
    UCHIJA  neotech{1.6} [NeoTech](NeoTech-1.8-1.6.jar) 
    UCHIJA  progressiveautomation{1.6.15} [Progressive Automation](ProgressiveAutomation-1.8-1.6.15.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GTX 680/PCIe/SSE2'
    Launched Version: 1.8-Forge11.14.3.1491
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 680/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.06, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [ModernHD 1.8.1.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by mahashel** [comment]
Bueller?
I am coming up on my 500th game crash due to this issue.  Roughly 1/10th of all game launches are successful.  The remaining 9/10 are not.  Nasty.
I will have to abandon this mod if there's no resolution planned for this problem.  Sad, since this mod enables construction of some very intricate machinery for those of us running MC 1.8.
Feel free to contact me if more data is required.  I have hundreds of crashlogs for all kinds of configs that exhibit this issue.  (fast/slow servers, fast/slow clients, AMD/NVidia clients, Win/Linux, basic/advanced pipes, different versions of MC & Forge, different combinations of mods & texture packs, etc, etc..)  
Seriously, I've been trying everything to get this running and am looking for feedback.  Toughing it out longer than I normally would since this mod still appears to be the only one for MC1.8 that includes item pipes.  If there's no fix, then I need to attempt to replace everything with hopper pipes. (I sure hope not)

**Comment by Dyonovan** [comment]
Should be fixed in rewrite. Initial release later today. There will not be pipes in initial release
