### ISSUE TITLE
Crash on load after changing Config Options

### ISSUE THREAD

**Issue by Darkosto** [TeamBR-Modding/NeoTech#210]
What Version of NeoTech are you using: 1.8.9-2.4.1

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: 
http://pastebin.com/08GjA7Hn
http://pastebin.com/pbqAR5vj

This is going to seem very strange, so I'll do my best to explain what happened on my end. 

At first I thought this crash happened because I reverted to an older version of Tinkers to alleviate another separate issue. I also changed the amount of RF the electromagnet could hold. I loaded the pack up and it crashed on load. I assumed this was happening because Neotech registered a fluid from the newer tinkers version and it was still in the configs. So, I deleted my configs and reloaded. The pack then loaded just fine.

I went back into the configs and fixed some of the entries, Electromagnet back to 5000rf, update notification off, turning off ore gen and got the same crash. I even manually changed the electromagnet back to 25k rf and still got the crash. So, I deleted the configs again and the pack loads just fine. 

For testing, I only changed the electromagnet rf and left the rest to default and the crash happened again.

Edit: As soon as I thought I figured out the crash: 

After leaving the electromagnet RF alone and changing some other config options: Fluid world generation, copper, tin, silver, and lead world generation I got the same crash: http://pastebin.com/vY9LjJW2

So, it seems as though the issue is on my end. I'm now able to change electromagnet RF but need to leave world gen on to stop the crash from happening. 

Thanks for reading my novel! :D

**Comment by Dyonovan** [comment]
Issue is on our end. Working on fix now

**Comment by Dyonovan** [comment]
Keep Fluid Generation to true. As we dont generate fluids in world anyways, it doesnt matter.

I am also removing that option next update as its redundant.
