### ISSUE TITLE
Suggestion: Keybind to disable Electric Armor - Jetpack

### ISSUE THREAD

**Issue by smithy1294** [TeamBR-Modding/NeoTech#211]
What Version of NeoTech are you using: 2.4.1

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: N/A

Just a suggestion to add a keybind to toggle the jetpack as it gets really difficullt/annoying to jump 1 high with it on.

Thanks

**Comment by Dyonovan** [comment]
Already added for next release :)
