### ISSUE TITLE
Iron & Gold Fluid Tank deletes fluid in tank when leaving area in version 1.8.9-2.4.1

### ISSUE THREAD

**Issue by shortybsd** [TeamBR-Modding/NeoTech#212]
What Version of NeoTech are you using:
1.8.9-2.4.1
If possible, did you break and replace the block:
Yes
Please Pastebin.com the crash Report and put link here:
N/A

When placing down an iron fluid tank and putting any type of liquid in it, in this example we used lava. If you teleport away then come back the tank will be empty. The gold tank does this as well, haven't tested the diamond one yet.

**Comment by DDzwiedziu** [comment]
Same here, with the same version (latest FTB Unstable). Just this happens on loading a game.

**Comment by GemSlate** [comment]
Same with diamond tank. Running 2.4.1 as well (FTB Unstable)

**Comment by pauljoda** [comment]
This is fixed in the next update

**Comment by Twisted-Code** [comment]
Oh good, it's fixed (we think) :D :+1:
