### ISSUE TITLE
Fluid interface pipes are pushing null fluidstacks

### ISSUE THREAD

**Issue by bdew** [TeamBR-Modding/NeoTech#213]
If a fluid interface pipe is connected to a tank that doesn't allow draining and it returns null from drain(...) you should check that and not call fill(...) on other tanks with it.

I'm ensuring there's a null check everywhere in my mods, but it will probably cause issues for others as well. And the call is pointless.

**Comment by pauljoda** [comment]
No problem, recently rewrote the whole thing and forgot to readd that. Thanks for the help
