### ISSUE TITLE
Suggestion:Inter-dimensional transport.

### ISSUE THREAD

**Issue by blockbreaker1361** [TeamBR-Modding/NeoTech#214]
I am using the most recent version of Neotech. I have scanned through the rest of the issues and do not see anything mentioning this, so I decided to ask. How about a block similar to a Tesseract or Dimensional Transceiver to transport power, liquids and items over endless distances, even across dimensions? That would be extremely useful.

**Comment by pauljoda** [comment]
I have plans for this

**Comment by pauljoda** [comment]
This is going on the backburner with EIO updated and TE coming out soon. Might revisit in the future
