### ISSUE TITLE
Electric centrifuge won't process if the second tank has something

### ISSUE THREAD

**Issue by Buuz135** [TeamBR-Modding/NeoTech#215]
If you empty the first tank but the second tank has some lava, the Electric Centrifuge will stop processing.

![](https://i.gyazo.com/6f87f1334afba1e45939a872617060f4.png)

**Comment by pauljoda** [comment]
This is on purpose at the moment. Didn't really want to write all the complex logic that would slow stuff down so I kept it like that. I mean I can add that, but the registry calls are already our most intensive code as it is.

**Comment by Dyonovan** [comment]
Added ability to select tank output
