### ISSUE TITLE
bronze required to craft alloyer. alloyer required to craft bronze. (outside mod required to progress)

### ISSUE THREAD

**Issue by Xogue** [TeamBR-Modding/NeoTech#218]
What Version of NeoTech are you using: 2.4.1

If possible, did you break and replace the block: N/A
## Please Pastebin.com the crash Report and put link here: N/A

No Crash. Unless I am mistaken, there doesnt seem to be a way to craft bronze in the mod except the alloyer. but bronze is required to craft the alloyer.  seems you shouldnt require access to a different mod (i used tinker's) to get bronze the first time.

If it is possible to get bronze before getting the alloyer. seems it should be easier to find out how.

**Comment by Dyonovan** [comment]
3 copper dust and 1 tin dust in a crafting table should give you bronze.
