### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by catzs** [TeamBR-Modding/NeoTech#22]
This mod is amazing. One of the f‏irst 1.8 tech mods to have actual content. I just have a few suggestions:
1. Recipes
The recipes for the machines in this mod seem far too cheap, only requiring redstone, iron and cobblestone, all of which I obtained
in 20 minutes of creating my world. Perhaps make the electric crusher(which is far too cheap for ore doubl‌ing) require more RF and
more crafting, perhaps gears/wire or something similar. The electric smelter should be a similar recipe, but perhaps including coal
blocks. The electric miner is far too early game. Gate it behind a complicated tech machine that creates the components for the miner. Make the new machine require diamonds(or emeralds), tin and coppers, as well as the new crafting items. The generators should require more materials as well, perhaps a burning coil or something
2. Power
The newly implemented RF is a great addition to the Modded 1.8 Minecraft Game. But RF in Neotech is far too easy to obtain. Just one coal creates enough power to crush and smelt a number of items, and lava is very easy to get. Perhaps make the lava buckets only usable in the fluid generator(no idea what that does) and halve the RF production that the generators create. Adding new and interesting generators would also be a cool feature-valuable generators, solar panels, biomass generators, etc. Don't try and replicate other mods features, expand and add on to them so when TE&IC2 come out for 1.8, your mod won't get forgotten. 
3. Compatibility
One suggestion I have is to make more of the recipes available in NEI(Not Enough Items), like the dust and powdered ores. This will make people new to modding more open and understanding of the things Neotech has to ofAfer. Making the RF more compatibile with Flux Ducts & Progressive Automation is another good idea.
4. Guide Book
Making a guide book similar to Botania's Lexica Botania, or Thaumcraft's Thaumonomicon would help people understand the things your mod has to offer.
5. Crafting Mechanics
Having everything be crafted in a GUI, or Crafting Table can get boring. Maybe make of the items only be craftable in world, like
in a special multiblock structure, that you click in the items and watch them be created for you. This makes the player more interactive with the game and not sucked into a GUI. Also introduce some sort of machine that crafts crafting components for you, that are only craftable in that machine.
6. New Machines
Instead of copying Thermal Expansion, Buildcraft, IndustrialCraft 2 EXP, Extra Utilities, Ender IO and Mekanism, create and implement
your own ideas that make your mod unique. Perhaps introduce a specific machine to turn diamonds into emeralds with a bunch of power, or pump that only works when supplied with wood or water, or a miner that only mines cobblestone and dirt until upgraded to mine specific ores. Instead of following the power creep(TE,EIO,Mekanism&XU) you can stay behind with your own interesting mechanics unique to your own mod.
Anyway, keep working on this new and great mod.

**Comment by pauljoda** [comment]
Closing for now, We have taken your suggestions and mapped them on our Trello board. Thank you for the feedback and feel free to suggest more as the new version is developed
