### ISSUE TITLE
Electric alloyer accepts fluid that it can't alloy with the fluid already in there.

### ISSUE THREAD

**Issue by ewanm89** [TeamBR-Modding/NeoTech#221]
Electric alloyer accepts fluid that it can't alloy with the fluid already in there.

There is also no way of extracting fluid again, leaving the only option to break the block losing all the stored RF and all of both fluids that have accidentally ended up in the alloyer.

**Comment by Dyonovan** [comment]
We will do something to fix that

**Comment by pauljoda** [comment]
I am unable to replicate it, can you pastebin your alloyer recipe registry located in your config directory and provide a screenshot of it accepting wrong fluids?

**Comment by ewanm89** [comment]
Both the fluids in question are valid in some kind of alloy, Just not the and alloy between those 2. [Youtube video showing this](http://www.youtube.com/watch?v=lkOYJrJCGKU) sorry microphone is so quiet, will need to fix that.

**Comment by ewanm89** [comment]
Here is the alloyerRecipes.json: 
`[
  {
    "fluidOne": "water:125",
    "fluidTwo": "lava:125",
    "fluidOut": "obsidian:36"
  },
  {
    "fluidOne": "iron:144",
    "fluidTwo": "carbon:144",
    "fluidOut": "steel:144"
  },
  {
    "fluidOne": "copper:432",
    "fluidTwo": "tin:144",
    "fluidOut": "bronze:576"
  }
]`

**Comment by pauljoda** [comment]
Yep I see the issue now. I'll see what I can do about that

**Comment by Dyonovan** [comment]
You can now remove fluids from alloyer

**Comment by Ramh5** [comment]
I can't find the way to empty it, playing with version 1.10.2
