### ISSUE TITLE
Chunk Loader crashes client when chunk also loaded with FTBUtils

### ISSUE THREAD

**Issue by Iapyx** [TeamBR-Modding/NeoTech#227]
What Version of NeoTech are you using: 2.4.1

If possible, did you break and replace the block: Crashes instantly on load, had to delete block in MCEdit

Please Pastebin.com the crash Report and put link here: http://pastebin.com/cpUEpMrP

**Comment by ghost** [comment]
On a couple of FTB videos there were remarks that the FTB chunk loading didn't play nicely with other chunk loaders, that's why the Railcraft loaders were disabled in Infinity Evolved.

**Comment by pauljoda** [comment]
Yeah their chunkloader is kinda messy. Not sure if there is a way around that as we are doing things the correct way, we are even identifying our chunk loader by our mod, if they are loading the ticket as well something very wrong is going on. Send the issue their way and see what they say
