### ISSUE TITLE
Net Launcher STILL crashes upon crafting in TC Crafting table

### ISSUE THREAD

**Issue by ArtOfCombat** [TeamBR-Modding/NeoTech#228]
What Version of NeoTech are you using: 2.4.1

If possible, did you break and replace the block: N/A - Crafting issue

Please Pastebin.com the crash Report and put link here: http://pastebin.com/5DW3NteY

**Comment by ArtOfCombat** [comment]
Tested normal table - still crashes.

**Comment by Dyonovan** [comment]
Fixed for next release
