### ISSUE TITLE
Input/Output tooltip the wrong way around?

### ISSUE THREAD

**Issue by Renadarain** [TeamBR-Modding/NeoTech#229]
Forge 1764
Neotech 2.4.1
Minecraft 1.8.9

In this video https://www.youtube.com/watch?v=f1JMSGmg9IU at 2.23 the tooltips for the input/output are blue=in, orange=out and green=both.  This is the same as TE.

When trying to output power from a solar panel to an Advanced RF Storage machine the tooltips on the pipes are reversed.  Blue is output, orange is input. 

Which is the correct one?

Regards,
Renada

**Comment by mario-88ce** [comment]
righteous ones are orange = output , Blue = input

**Comment by Renadarain** [comment]
Thanks :) 

I don't know what I'm doing wrong then but no matter which way I set them I can't get them to output lava from the Ex Nihilo 2 crucible into the iron fluid tank

**Comment by mario-88ce** [comment]
You used the right tube " liquid " is the output of the machine is at the entrance of the tank? 
example:
crucible ---- > tube for liquids with output ---- > tank
or:
crucible --- > Pipe for liquids with output --- > base pipe --- > pipe for liquids with input --- > tank

**Comment by Renadarain** [comment]
I've just tested this with two iron tanks and fluid interface pipes connecting them and it extracts from one tank and inserts into the other perfectly.

For some reason it doesn't want to do this with the crucibles but it used to work in previous versions.

![2016-03-17_14 28 03](https://cloud.githubusercontent.com/assets/3536320/13849347/af5bd396-ec4d-11e5-8b52-10f97e20038d.png)

**Comment by pauljoda** [comment]
It requires 100mb minimum to extract, do those each have that much in them?

**Comment by pauljoda** [comment]
Also, the tool tip has been changed to "extract/insert" to remove confusion

**Comment by Renadarain** [comment]
Yes they have 100mb and more

![2016-03-17_20 41 03](https://cloud.githubusercontent.com/assets/3536320/13860638/57524f84-ec81-11e5-836e-95621bbda1b9.png)

**Comment by Renadarain** [comment]
I'm not sure why this was closed. Is there an answer or is it a bug with Chisel?

The above picture shows the crucibles contain more than 100mb

**Comment by Renadarain** [comment]
Apologies - it's Ex Nihilo 2 not Chisel

**Comment by pauljoda** [comment]
Have you tried pumping from all different sides? Perhaps they changed their behavior

**Comment by Renadarain** [comment]
Yes! They work fine with zooooom pipes and buildcraft pipes. Haven't tried ExtraUtils2 because Tema only has item ducts right now.  Also the item pipes from Neotech work perfectly dropping cobblestone into the top of the crucible.  It's only the fluid ones that it doesn't like.  

I'm still on 2.4.1 because 2.4.2 and 2.4.3 throws an error on the server and chucks you out but I'll post that in another thread so as not to get them all mixed up.
