### ISSUE TITLE
Dense Ores & Electric Pickaxe

### ISSUE THREAD

**Issue by popemichael** [TeamBR-Modding/NeoTech#230]
What Version of NeoTech are you using: 1.8.9 - FTB Unstable

If possible, did you break and replace the block: This does not apply

Please Pastebin.com the crash Report and put link here:

http://pastebin.com/RLyADqxK

How to recreate: Using an electric Pickaxe with cobalt mining upgrade, fortune, and speed upgrade, 1 area upgrade, elite battery:break a dense ore block directly.

You can break the dense ore with the area upgrade, just don't mine it directly

**Comment by mario-88ce** [comment]
Cobalt mining update? Where did you get this update? I have installed the latest version of the mod and this update to the electric pickaxe there I

**Comment by popemichael** [comment]
@mario-88ce I crafted it. the recipe should be in JEI. I'm at work, so I can't screen shot it.

With all of the upgrades, a trashbag set to cobble, strip mining becomes a zen experience.

**Comment by mario-88ce** [comment]
you can just give me the recipe to create it ? I even jets in there I have this update so do not know how to do : /

**Comment by pauljoda** [comment]
This is a bug with dense ores, please post there
