### ISSUE TITLE
Massive lag issues with Chunk Loaders in version 1.8.9-2.4.1

### ISSUE THREAD

**Issue by shortybsd** [TeamBR-Modding/NeoTech#232]
What Version of NeoTech are you using:
v2.4.1 for MC 1.8.9 running on Forge 1764
(Multiplayer)

If possible, did you break and replace the block:
Yes

Please Pastebin.com the crash Report and put link here:
N/A

Server constantly spams overloaded and TPS goes down to 2 with no one on server, break all NeoTech chunk loaders and lag all goes away. I have the VisualVM .nps snapshot of the lag issues regarding chunk loaders if needed.

**Comment by pauljoda** [comment]
Can you post an example of what the console is spamming?

**Comment by shortybsd** [comment]
The server spams "[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2240ms behind, skipping 44 tick(s)
"
Here is the VisualVM graph showing the chunk loader pulling over 50% cpu usage with only one player on, no where near the other players chunk loader. 
https://www.dropbox.com/s/qkv8qwnd146gsos/Screenshot%202016-03-18%2017.00.28.png?dl=0

**Comment by pauljoda** [comment]
Hmm. This is interesting. I'll have to look into this as it shouldn't be causing issues like this

**Comment by ruifung** [comment]
Is there any particular reason why the chunk loaders have to forceChunk every tick?

And clearly (ticket.maxDepth > 0 && ticket.requestedChunks.size() > ticket.maxDepth) is returning true often enough that the calls to forceChunk also call unforceChunk... which is apparently creating a copy of some kind of Map...

**Comment by pauljoda** [comment]
They should only force chunk if the chunk is not loaded

**Comment by ruifung** [comment]
but if that's the case... why would it need to be calling it every tick? It's happening often enough for jvisualvm to show it as consuming a significant amount of CPU time.

**Comment by Dyonovan** [comment]
I found the reason and will be releasing a fix for 1.8.9 later today
