### ISSUE TITLE
Crash piping from centrifuge to smeltery

### ISSUE THREAD

**Issue by jco2641** [TeamBR-Modding/NeoTech#233]
What Version of NeoTech are you using:
1.8.9-2.4.1

If possible, did you break and replace the block:
Not possible.  World crashes immediately on load

Please Pastebin.com the crash Report and put link here:
http://pastebin.com/94dpQtC7

I don't know if the 'fault' is with your mod or the other.  If its not something you can fix I'm happy to report it to the other mod.

The setup:

No upgrades in any pipe.

Input side of neotech pipe:  Neotech centrifuge with molten gold and lava inside.
Fluid input pipe set to extract from centrifuge

Output side of pipe:
Fluid endpoint connected to smeltery drain. Output only mode.  Blacklist lava.
Fluid endpoint connected to smeltery tank. Output only mode.  Whitelist lava.

The crash occurred immediately upon setting the fluid endpoint pipe to pull from the centrifuge.
The entity location of the crash is the input side fluid interface pipe.

**Comment by Dyonovan** [comment]
This is wierd as the crash report is pointing to tinkers construct,.

**Comment by pauljoda** [comment]
Pipes will no longer be supported in Neotech from here on out, closing for this reason
