### ISSUE TITLE
Crash on 1.9

### ISSUE THREAD

**Issue by kwpugh** [TeamBR-Modding/NeoTech#236]
What Version of NeoTech are you using: NeoTech-1.9-3.0.0.jar
Forge: 1782
If possible, did you break and replace the block: no

Please Pastebin.com the crash Report and put link here:

Crash report:  http://pastebin.com/raw/0fmVM4Eh

**Comment by pauljoda** [comment]
Forge updated and broke everything, use an older forge until we can update please

**Comment by kwpugh** [comment]
can't use older forge, other mods already gone there.   Will wait until next release of Neo.

Thank you.

**Comment by pauljoda** [comment]
Grab the builds from here http://teambrmodding.com:8080/
