### ISSUE TITLE
Blocks mined by Electric Pickaxe with AOE active don't drop experience

### ISSUE THREAD

**Issue by Gotolei** [TeamBR-Modding/NeoTech#237]
NeoTech Version: 1.8.9-2.4.1 (Modpack: The Pioneers R.5)

https://gfycat.com/JollySoreDeermouse
Specific pickaxe stats: http://i.imgur.com/tBbI3By.png

**Comment by pauljoda** [comment]
Yep that would happen. Totally missed that. Dyonovan will get on that tomorrow
