### ISSUE TITLE
1.9 crash

### ISSUE THREAD

**Issue by Majestyc2k1** [TeamBR-Modding/NeoTech#238]
What Version of NeoTech are you using: 3.0

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: [http://pastebin.com/8sUq5WaR]

Using Curse Launcher. Crashed when loading Profile.

**Comment by pauljoda** [comment]
Try the latest builds on jenkins. Forge updated and moved some classes and we have it fixed there

**Comment by pauljoda** [comment]
http://teambrmodding.com:8080/

**Comment by Majestyc2k1** [comment]
Still getting a crash:

[http://pastebin.com/z0x3KdnK]

What version of Forge do you recommend?

**Comment by Dyonovan** [comment]
Make sure your using the lastest forge, and NeoTech, Bookshelf from Jenkins, and MCMultipart from curse. Should be fixing all these issues today
