### ISSUE TITLE
Electric Alloyer Ticking Block Entity

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [TeamBR-Modding/NeoTech#239]
[crash-2016-03-22_00.28.01-server.txt](https://github.com/TeamBR-Modding/NeoTech/files/183656/crash-2016-03-22_00.28.01-server.txt)

What Version of NeoTech are you using: (read the crash report)

If possible, did you break and replace the block:

Please Pastebin.com the crash Report and put link here:

**Comment by Dyonovan** [comment]
Delete the NeoTech config directory and let it recreate
