### ISSUE TITLE
My quibbles with pipes and upgrades

### ISSUE THREAD

**Issue by dominx** [TeamBR-Modding/NeoTech#240]
What Version of NeoTech are you using:
2.4.1 
I'm playing FTB Unstable.

I'll try to stick mostly to interface/usability here. 

Pretty please, just let me right click the interface pipe to access the gui. Having to use the wrench is annoying extra hoop to jump that adds nothing. Also no other mod that I remember does that so I find myself trying again and again to just right click the pipe. Changing it to what is pretty much standard behaviour would also free the wrench-right click to do something useful. It would be great to be able to use that to change the IO config. Having to open the gui, open the tab, rotate the thing gets tedious fast.

Which brings me to the IO config. It's very easy to get lost in rotation. I open the gui, open the tab, try to rotate, find that I don't know how it is oriented now, have to close and reopen to orient myself. EIO does the right thing here providing the crucial context by showing the neighbouring blocks. Also, please provide the config option to inverse the meanings of left/right click. I'm very used to EIO and constantly get it wrong.

Too many tabs. Fully upgraded pipe has 6 tabs. 3 of them could be easily fit into the main gui window without much of clutter. As it is to change or just view the redstone, extraction mode or frequency I need an extra click each time. If they were just buttons in the main window I could do that straight. As a bonus there could be a mouseover tooltip saying what upgrade is needed to have that functionality if it's not installed.

Fluid sorting. While building ore processing setup I've found that setting up fluid sorting is a pain. The liquid quantities don't add up to whole buckets which itself is a good thing; it's compatible with Tinkers and makes setting up the system more interesting. But with being unable to bucket liquids in and out of machines setting up the filters is painful. I have set up a pipe and a tank, possibly get not the liquid that I want in case of centrifuge, bucket from the tank, set the filter, and set up pipe yet again to drain the stuff back into system, because even if I save the filled bucket for future use, there some stuff still in the tank. Note that being unable to bucket fluids in or out of machine itself is not a bad thing. TE does that, but there 4 or 10 items add up neatly to the whole bucket. It would be nice to have a pipette or something like that to be able to select fluids for sorting. 

The upgrade system is opaque.

Mystery motherboards. The motherboards all look the same, if I have a few in my inventory to see what I have I have to mouse over one, squint at indistinctive text, mouse over another one, another one, and then back the first one because I already forgot the first one. They are unstackable so if I have a few for some pipes and some for the machines it makes that even worse.

There is disconnect between the names and looks of upgrades and their function. A hard drive in machine enlarges energy storage, in pipes upgrades the speed I think. I cannot remember at the moment what expansion does where and I have read the help tab many times. All that makes little sense thematically which makes it hard to remember and the upgrade system is unforgiving. Having things named speed, storage, efficiency upgrades might be boring but is at least very clear. Also I've seen suggestions for upgrades doing some other things and it seems to me I would be difficult to have them in the upgrade system as it is.

This is not just an interface thing but the upgrade system seems a bit harsh. An old motherboard with few upgrades or a botched one is just trash. And processors cost diamonds. How about being able to add more stuff an already filled motherboard or being able to disassemble it back into parts?

I hope I don't sound too whiny, it was not my intention.

**Comment by pauljoda** [comment]
I like the feedback. A lot of what you are saying I'm thinking about solutions for. The ability to modify motherboards is something that I need to work on. When refactoring the abilities of the thermal binder, in my haste I forgot those features. It was supposed to be able to add and modify but that ended up not happening. We have plans for that. 

I'll keep these in mind as I go. Thanks for the feedback

**Comment by pauljoda** [comment]
Pipes are being removed for the time, might be their own mod eventually
