### ISSUE TITLE
[1.9] - NeoTech Crash

### ISSUE THREAD

**Issue by Lanse505** [TeamBR-Modding/NeoTech#241]
What Version of NeoTech are you using:
1.9 - 3.0.0-B21 from Jenkins

If possible, did you break and replace the block:
This is a Load-up crash

Please Pastebin.com the crash Report and put link here:
http://puu.sh/nPMeB/45abe19e37.txt

**Comment by Dyonovan** [comment]
You also need to update Bookshelf from jenkins

**Comment by Lanse505** [comment]
Good to remember xD
