### ISSUE TITLE
Crah when loadimg world aufter upgrade from 1.8.9-2.4.1 to 1.8.9-2.4.3

### ISSUE THREAD

**Issue by dhalek** [TeamBR-Modding/NeoTech#246]
What Version of NeoTech are you using: 1.8.9-2.4.3

If possible, did you break and replace the block: Minecraft crashes before I can break anything

http://pastebin.com/79SN0GUG

This crash happend when I try to load my world. That means Minecraft starts to the menu and when I select my world and click on "Play selected world" it crashes. With 1.8.9-2.4.1 it just runs fine. 2.4.2 introduced the crash and 2.4.3 still has it.

**Comment by Renadarain** [comment]
I have the same issue. http://pastebin.com/d3ih1k2y

Minecraft: 1.8.9
Forge: both 1764 and 1964
Neotech: 2.4.2 / 2.4.3

Minecraft loads but on entering the server you're thrown straight out again.  Like the guy above, works fine in 2.4.1

**Comment by Renadarain** [comment]
Thank you, this fixed it :)
