### ISSUE TITLE
1.9 loading error: java.lang.NoClassDefFoundError: BlockPipeSpecial

### ISSUE THREAD

**Issue by 4rz0** [TeamBR-Modding/NeoTech#247]
What Version of NeoTech are you using:
NeoTech-1.9-3.0.0-B27.jar
Bookshelf-API-1.9-3.0.0-B22.jar
Forge 12.16.0.1802

If possible, did you break and replace the block:
Nope, loading error

Please Pastebin.com the crash Report and put link here:
http://paste.ubuntu.com/15483001/

**Comment by Dyonovan** [comment]
You need to have mcmultipart installed. Will need to add that back in as a requirement

**Comment by 4rz0** [comment]
Thanks, resolved.
