### ISSUE TITLE
[1.8.9] Server Crash: Attaching EnderIO conduit to output side of Centrifuge

### ISSUE THREAD

**Issue by Periphera** [TeamBR-Modding/NeoTech#248]
version 1.8.9-2.4.1-B#121

Placing an EnderIO energy conduit on an output side of a Centrifuge caused a server crash (required rollback).

http://pastebin.com/uuySxcLV

(I know you have updated since, but maybe this bug wasn't addressed)

**Comment by pauljoda** [comment]
Ender IO may be using the old RF API, I'll have to check

**Comment by pauljoda** [comment]
Resolved in latest versions in 1.10.2
