### ISSUE TITLE
[1.9] Item Dupe

### ISSUE THREAD

**Issue by KennyBurch** [TeamBR-Modding/NeoTech#249]
Minecraft 1.9
Forge 1800
Bookself API 3.0.0B22
NeoTech 1.9 3.0.0

When breaking a Basic RF storage block two copies are dropped.

**Comment by Dyonovan** [comment]
Can you pick the second one up into your inventory?

**Comment by KennyBurch** [comment]
Upon retesting...

3 blocks appear to spawn when the Basic RF storage block is broken. Two of them I can pick up..the third I cannot.

**Comment by pauljoda** [comment]
Does your console provide any information when breaking the block?

**Comment by KennyBurch** [comment]
Nothing is stated on the console, but the same thing happens when breaking the advanced and elite versions of RF storage blocks too. None of the other machines have I ran into this with yet.

**Comment by pauljoda** [comment]
Ok, thanks for the info. Things are kinda wonky with player interaction in 1.9 so we are watching to see if the issue is on our end. It probably is, but when forge updated many things with block interaction changed some a few things just don't work yet

**Comment by KennyBurch** [comment]
Understood, I'm running forge 1800 because that was one I had downloaded that still worked with Neotech (and bloodmagic).  Also just found that the tanks, (both iron and gold) duplicate when broken...but those for some reason do not give the phantom(false client side only) third drop.

I'll update again once a build for the new forge is released.

**Comment by pauljoda** [comment]
Go to the home of this github and click the build passing button in the
description. That will take you to our Jenkins where you can download the
latest neotech and bookshelf. I think we updated. Unless that is what you
are using and in that case forge messed up things again

**Comment by KennyBurch** [comment]
I wasn't having luck with forge 1811 using Bookshelf B22 and NeoTech B31.  Instead of chasing it down I'll just wait a bit for the next release to come out.  Thanks for the quick responses and suggestion though.  Its been a fun morning learning how to use github.
