### ISSUE TITLE
Electric Furnace turns wood into Coal

### ISSUE THREAD

**Issue by P3bbl3s** [TeamBR-Modding/NeoTech#25]
So far I have tested Oak, Spruce, Birch, Jungle woods, all with the same effect, instead of turning into charcoal they turn into coal, also it will not allow for more than 1 coal in the output (no stacking).

Tested in both Survival and Creative, using a furnace generator with an electric furnace next to each other.

I have used the electric furnace to turn various dusts into "ingots" and they stacked as expected, wood seems to be broken.

**Comment by Dyonovan** [comment]
Fixed in rewrite. Should have an initial release today
