### ISSUE TITLE
[1.8.9] Tesselating block model

### ISSUE THREAD

**Issue by MisterShawn** [TeamBR-Modding/NeoTech#250]
What Version of NeoTech are you using:
Both 1.8.9-2.4.4 and 1.8.9-2.4.1
If possible, did you break and replace the block:
N/A
Please Pastebin.com the crash Report and put link here:
http://pastebin.com/raw/FLX7KC58

I updated all the mods in my pack and was getting this crash, so I downgraded back to 2.4.1 when the crash didn't happen. However, it happened again. I read a similar crash on the closed issues and removed Architecture craft. Still happening.

Note: I also downgraded BookshelfAPI from 2.3.7 to 2.3.6 as well.

**Comment by pauljoda** [comment]
Seems to be an issue with elecore. Would you mind posting that over on his issue tracker?

**Comment by MisterShawn** [comment]
I posted and the dev's response:
"Well, I just link through, so unfortunately it's their issue, nothing I can do about it :("
