### ISSUE TITLE
[1.8.9] Pump problems

### ISSUE THREAD

**Issue by Majestyc2k1** [TeamBR-Modding/NeoTech#251]
FOR 1.9 VERSION: IF YOU HAVE THIS CRASH IT IS FORGE, DON'T POST: 
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/TRSRTransformation

What Version of NeoTech are you using: 1.8.9-2.4.4

If possible, did you break and replace the block: yes

Please Pastebin.com the crash Report and put link here:

Having trouble getting liquid out of the Pump. I have it in the Nether to pump lava. It has sufficient power (WAILA verified), but can't get the lava out of the Pump and into a tank. I tried both an NT iron tank and a Ender Tank from that mod. I tried putting the tanks directly on the Pump, and with fluid pipes. I'm also using a chunk loader I had it working in previous versions of NT.

**Comment by Majestyc2k1** [comment]
I also tried it in Overworld on water. I had a solar panel for power and fluid pipes into an iron tank. Nothing.

**Comment by pauljoda** [comment]
Tanks are borked. Not sure why. This will require me reevaluating the entire thing as for some reason it just doesn't work now. I wasn't really happy with it anyway and I intend to give it a proper work at some point soon. Thanks for the report and let me know if you find anything else

**Comment by Majestyc2k1** [comment]
Copy

**Comment by Gunner76th** [comment]
This bug appears to be similar to the one I posted here: https://github.com/TeamBR-Modding/NeoTech/issues/265
It would appear that the pump is not outputting its fluid even if a tank is not used (IE fluid interface pipe connected straight to the pump). Was the pump intended to have a tank on it in order for it to work, or should it be working with just power and a fluid interface pipe? 

Also, while speaking about the pump, would it be possible to give it a GUI to be able to install upgrades similarly to all of the other machines? Processors to increase the rate in which it sucks in a source block, Harddrives to increase the number of source blocks pulled in (with a max of 2-4), and control to set a side for automatic output.

**Comment by Kriptikz** [comment]
This bug seems to have appeared when NeoTech was updated from version 2.4.1 to version 2.4.2.      I tested versions 2.4.1 to 2.4.4 and all versions beyond 2.4.1 have the pump not working. Hope this helps.

**Comment by pauljoda** [comment]
Pump is being removed
