### ISSUE TITLE
[1.8.9] Pipe model in I/O Config missing.

### ISSUE THREAD

**Issue by benten2000** [TeamBR-Modding/NeoTech#254]
In my 1.8.9 modpack I have Neotech-1.8.9-2.4.4 and was noticing when you go to configure and pipe in the I/O Config tab the middle pipe model was missing (just a blue default cube)

So I made a fresh 1.8.9 install with just NeoTech and added my other mods one at a time to see what was causing it and found for some reason BetterFoliage would cause this to happen.

Just curious what could cause a none foliage based thing like a pipe model on a gui tab disappear.

**Comment by pauljoda** [comment]
It is possible they are doing some changes to the block renderer the are causing my render to be translated wrong or just not working. I've seen a lot of mods injecting or replacing vanilla code to get some older access back and it tends to cause issues for the rest of us. I'll look into it

**Comment by pauljoda** [comment]
Removing pipes
