### ISSUE TITLE
Server crash with Centrifuge auto-outputting to TConstruct casting table without cast 

### ISSUE THREAD

**Issue by tod** [TeamBR-Modding/NeoTech#255]
This crash happened as soon as I placed a Tinker's Construct casting table below a Centrifuge that was set to auto output to that side. I didn't have time to place the ingot cast before the server crashed. The world now crashes on startup. Sorry if this is an older version, but it's what is in the FTB Unstable pack.

What Version of NeoTech are you using:
NeoTech-1.8.9-2.4.1 (from ftb-unstable)

If possible, did you break and replace the block:
No, the server crashes on startup

Please Pastebin.com the crash Report and put link here:
http://pastebin.com/w6P68Wyr

**Comment by Dyonovan** [comment]
Crash log says the crash is coming from tinkers.

**Comment by bonii-xx** [comment]
You guys are trying to fill with a null. You shouldn't do that.

**Comment by pauljoda** [comment]
My bad, we are updating to capabilities anyway so I'll go through and clear those out

**Comment by pauljoda** [comment]
Fixed with last push
