### ISSUE TITLE
NoSuchMethodError during startup

### ISSUE THREAD

**Issue by LlubNek** [TeamBR-Modding/NeoTech#257]
NeoTech crashes during initialization with a NoSuchMethodError exception.

What Version of NeoTech are you using:
NeoTech-1.9-3.0.0.jar

If possible, did you break and replace the block:
not relevant

Please Pastebin.com the crash Report and put link here:
http://pastebin.com/aRCHk45a

**Comment by Dyonovan** [comment]
Forge has changed things again. Working on the fix as we speak. Should be out in 30 mins or so. Version will be 3.0.2
