### ISSUE TITLE
[1.9] Ticking Entity error on entering world with JEI enabled

### ISSUE THREAD

**Issue by Melakion** [TeamBR-Modding/NeoTech#258]
http://pastebin.com/WrYec1TK

Can create a world fine with only Bookshelf and Neotech, but with JEI it crashes upon entering the world.

Forge{12.16.0.1813} [Minecraft Forge](forge-1.9-12.16.0.1813-1.9-universal.jar)
bookshelfapi{3.0.1} [Bookshelf](Bookshelf-API-1.9-3.0.1.jar)
JEI{3.1.2.172} [Just Enough Items](jei_1.9-3.1.2.172.jar)
neotech{3.0.2} [NeoTech](NeoTech-1.9-3.0.2.jar)

**Comment by Dyonovan** [comment]
Yea. trying to figure out what the hell is going on. Thanks for the heads up

**Comment by Dyonovan** [comment]
Ok finally tracked it down. pushing version 3.0.2 to curse now.
