### ISSUE TITLE
Server Crash [unrecoverable] when using emerald pipe to push molten iron to alloyer from crucible

### ISSUE THREAD

**Issue by acesaver** [TeamBR-Modding/NeoTech#259]
http://paste.ubuntu.com/15554666/

I had a crucible melting down iron, wanted to pipe the iron into the alloyer so i went to hookup a BuildCraft Emeral Fluid pipe to the two machines when this crash happened

**Comment by acesaver** [comment]
Using NeoTech version 1.8.9-2.4.1 which is what comes with the FTB Unstable pack

**Comment by Dyonovan** [comment]
Already been fixed in new versions
