### ISSUE TITLE
[1.9] Crash when placing a RF storage block

### ISSUE THREAD

**Issue by medsal15** [TeamBR-Modding/NeoTech#261]
FOR 1.9 VERSION: IF YOU HAVE THIS CRASH IT IS FORGE, DON'T POST: 
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/TRSRTransformation

What Version of NeoTech are you using: 3.0.3

If possible, did you break and replace the block: It appears to work when I relaunch minecraft

Please Pastebin.com the crash Report and put link here: http://pastebin.com/yck6FdjW

I appear to be missing CofhLib, is there a link for 1.9?

**Comment by Dyonovan** [comment]
It looks like someone is trying to use an old API for RF. I looked through the mod list and couldnt see anything. Do you know if any of those mods use rf?
