### ISSUE TITLE
1.9 Dimensional Crate issues

### ISSUE THREAD

**Issue by Melakion** [TeamBR-Modding/NeoTech#262]
Neotech 1.9 3.0.3

Dimensional Crate is not removed from inventory when placed. Here is my latest.log, at the end you can see what happens when you place a crate. http://pastebin.com/HLvFTDHS

When I broke an extra one that I had placed, I crashed. Here is the crash report.
http://pastebin.com/vCqATECp

**Comment by Melakion** [comment]
Also the item count display updates when putting items in, but not when taking them out

**Comment by Dyonovan** [comment]
This is an issue that was happening in 1.8.9 as well. 

https://github.com/Glitchfiend/BiomesOPlenty/issues/698

Opened a new issue with BoP

https://github.com/Glitchfiend/BiomesOPlenty/issues/728
