### ISSUE TITLE
[1.9] Crash at startup, NeoTech + Tinkers = boom

### ISSUE THREAD

**Issue by kwpugh** [TeamBR-Modding/NeoTech#266]
What Version of NeoTech are you using: NeoTech-1.9-3.0.3.jar, Bookshelf API 1.9-3.0.2 and Forge 1813

If possible, did you break and replace the block: crash at startup

Please Pastebin.com the crash Report and put link here: http://pastebin.com/raw/JE8wVZ8A

This seems to occur when Tinker's Construct is enabled.   NeoTech works fine when Tinkers is disabled and Tinkers works fine when NeoTech is disabled, but when to together, boom.

**Comment by Prophious** [comment]
same issue, same versions as well... maybe item id's are over lapping?

**Comment by ArMoReDfUrY** [comment]
same here. 
i did notice this during the load cycle. it was all the molten_*
[ 
Dangerous alternative prefix tconstruct for name molten_copper, invalid registry invocation/invalid name?

Dangerous alternative prefix neotech for name molten_copper, invalid registry invocation/invalid name?
]

**Comment by pauljoda** [comment]
No I missed a null check. It has been fixed with the latest build on Jenkins
