### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#268]
FOR 1.9 VERSION: IF YOU HAVE THIS CRASH IT IS FORGE, DON'T POST: 
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/TRSRTransformation

so it might be forge again but its different than what you posted so...
What Version of NeoTech are you using:1.9-3.0.3

If possible, did you break and replace the block:

Please Pastebin.com the crash Report and put link here; [http://pastebin.com/pTuz1cRy](http://pastebin.com/pTuz1cRy)

**Comment by Dyonovan** [comment]
Its been fixed. You can use the latest from jenkins. I will push an actual release to curse tomorrow

http://teambrmodding.com:8080

Just make sure you update both neotech and bookshelf if you grab it from there
