### ISSUE TITLE
NeoTech-1.9-3.0.3 crashes 1.9 client build 1816 on startup

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#269]
http://paste.ee/p/tAgxy

**Comment by Lanse505** [comment]
Can confirm this happens for me too :P
http://puu.sh/o0GLl/f3d907f595.txt

**Comment by Lanse505** [comment]
This happens on forge 1816, 1815, 1814, 1813.

Using:
Bookshelf-API-1.9-3.0.2
NeoTech-1.9-3.0.3

**Comment by Dyonovan** [comment]
Already fixed. You can use the latest here http://teambrmodding.com:8080 (make sure you update bookshelf as well) or wait till I push an official release later today
