### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Lavaflow** [TeamBR-Modding/NeoTech#27]
I've just updated to NT 2.01 from 1.6, and I'm now getting a crash on startup(pastebin crash log: http://pastebin.com/HUFBUP6q). I do have bookshelves API v2.00.

**Comment by Dyonovan** [comment]
There is an issue with 2.0.1 (which is why I just removed it from curse)

I should have a fixed release later today. Just trying to get something completed before I do a release
