### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by blockbreaker1361** [TeamBR-Modding/NeoTech#275]
I am using the latest version of your mod with the latest version of Forge, as most mods are now calling for it. I deleted the config and attempted to load. It gets through preinit, but once it gets to init, It crashes. Here's the crash report.
http://pastebin.com/BLcL9txC

**Comment by Dyonovan** [comment]
Can't seem to replicate with forge 1836.

Also, can you pastebin the full crash log including added mods.

**Comment by blockbreaker1361** [comment]
Here's the info you asked for
http://pastebin.com/eePUcmJR

**Comment by Dyonovan** [comment]
Fixed in 3.0.5

**Comment by blockbreaker1361** [comment]
Thank you very much. :)
