### ISSUE TITLE
Motherboard upgrades and batteries

### ISSUE THREAD

**Issue by Renadarain** [TeamBR-Modding/NeoTech#276]
MC 1.9
Forge 1816 - 1837
Neotech 1.9.3.0.4

Upgrades for the motherboard and also the batteries do not show up in JEI but do show up in the creative tabs, therefore cannot be created as there are no recipes.

Regards,
Renada

**Comment by pauljoda** [comment]
Unable to replicate, must be a strange issue with your setup
