### ISSUE TITLE
[1.8.9] interface pipes not "interfacing"

### ISSUE THREAD

**Issue by mblob** [TeamBR-Modding/NeoTech#277]
What Version of NeoTech are you using:
2.4.4
If possible, did you break and replace the block:
yes

```
Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-8b23bcf
SpongeForge: DEV
Minecraft Forge: 11.15.1.1808
```

Energy interface pipe does not interface with buildcraft engines, advanced generator(bdew) flux generator port(rf dedicated output).

Fluid interface don't work either.

Hydraulic craft is too buggy to be certain but its not working either(rf pressure pumps). These pumps works (not so well :) ) with bc kinesis pipes.

It connect without trouble to any rf tools machine.

I'll take a look tomorrow at pneumaticraft. 

It seems it's connecting and working well on faces of blocks but got problems with "ports".

![2016-04-08_03 38 16](https://cloud.githubusercontent.com/assets/967684/14371896/3d363310-fd3c-11e5-89e9-3e3b664364ae.png)
![2016-04-08_03 39 44](https://cloud.githubusercontent.com/assets/967684/14371900/405257a4-fd3c-11e5-96be-0267b73d8ec7.png)
![2016-04-08_03 33 09](https://cloud.githubusercontent.com/assets/967684/14371903/46c1b77e-fd3c-11e5-8734-0543fcf71a43.png)

I'am maybe doing something wrong.

**Comment by JCMais** [comment]
Hi! I have the same version with Minecraft 1.9, using the fluids pipe to connect a Pressure Pipe pump to an Advanced Generator Syngas Producer is not working.

**Comment by tlitookilakin** [comment]
Same here, the pipes in 1.9 are connecting to things but seem incapable of transfering anything. At first I thought it might be a redstone thing, but no matter what I do, the pipes will not transfer anything.

**Comment by pauljoda** [comment]
Pipes are now gone, issue invalid
