### ISSUE TITLE
Fluid Tank Dupe

### ISSUE THREAD

**Issue by Darkosto** [TeamBR-Modding/NeoTech#278]
What Version of NeoTech are you using: 1.9 3.0.5 

Forge Version: 1858

If possible, did you break and replace the block: Yes

When Shift-right clicking the Iron fluid tank with a neotech wrench, you can dupe the tank instead of picking up the original tank: https://sx.artdude.uk/hotlink-ok/darkosto/H2xA-33fb7-1460097079.png

**Comment by Cherry** [comment]
This same bug seems to occur with all interface pipes too: [Screenshot](https://jross.me/l/tyfwi) (Same Forge and NeoTech version as above).

**Comment by pauljoda** [comment]
This should be fixed in the latest version
