### ISSUE TITLE
Multiple "Dangerous alternative prefix neotech" warning during mod init.

### ISSUE THREAD

**Issue by mblob** [TeamBR-Modding/NeoTech#279]
What Version of NeoTech are you using:
2.2.4

```
Minecraft: 1.8.9
SpongeAPI: 4.1.0-SNAPSHOT-8b23bcf
SpongeForge: DEV
Minecraft Forge: 11.15.1.1808
```

If possible, did you break and replace the block:
not related

Lots of 
[Server thread/WARN] [FML/neotech]: \* Dangerous alternative prefix neotech for name molten_bronze, invalid registry invocation/invalid name?
During mod init.

Dunno if its important.

Please Pastebin.com the crash Report and put link here:

[fml-server-latest.log.txt](https://github.com/TeamBR-Modding/NeoTech/files/210043/fml-server-latest.log.txt)

**Comment by pauljoda** [comment]
Doesn't seem important, just weird tinkers interaction
