### ISSUE TITLE
Severe FPS degradation with JEI

### ISSUE THREAD

**Issue by Cherry** [TeamBR-Modding/NeoTech#280]
NeoTech version: 1.9-3.0.5
JEI version: 1.9-3.2.8.182
Forge version: 12.16.0.1857

Replication steps:
- Startup any world with JEI + NeoTech installed, and navigate to the page in JEI with NeoTech items. Note the drastic FPS drop.

Tested on my, albeit rather outdated machine:
- Standard world FPS: https://jross.me/l/goa3c (~150fps)
- JEI with Vanilla items: https://jross.me/l/jc798 (~70fps)
- JEI with NeoTech + Vanilla items: https://jross.me/l/7g156 (~20fps)
- JEI with just NeoTech items displayed: https://jross.me/l/unm6o (~20fps)

Current video settings: https://jross.me/l/fou1b, though changing these seems to have absolutely no affect on this issue.

I was able to reproduce the issue on my laptop too, though the difference there wasn't nearly as noticeable. Let me know if there's any further information I can provide.

**Comment by mezz** [comment]
Please try the same thing with JEI closed (Control-O) and lots of NeoTech items in your inventory. Then compare your fps to an inventory full of vanilla items. That way we can find out it JEI is part of the issue or not.

**Comment by Cherry** [comment]
Complete set of tests in a new world:
- Standard world FPS: https://jross.me/l/kl21g (~140fps)
- Inventory full of random Vanilla items: https://jross.me/l/3y1gi (~100fps)
- Inventory full of random NeoTech items: https://jross.me/l/1d7l2 (~60fps)
- JEI + Vanilla: https://jross.me/l/vm984 (~70fps)
- JEI + NeoTech: https://jross.me/l/aym3n (~20fps)

**Comment by mezz** [comment]
Thanks. It looks like the slowdown is due to rendering NeoTech items, JEI makes the problem worse because it shows way more items.

**Comment by pauljoda** [comment]
The issue has to do with some of my new baked models. When the models changed in 1.9 I thought I was caching models but it seems to not be doing so. I'll have to investigate as more than likely I'm doing something silly
