### ISSUE TITLE
MC 1.9, NT 3.0.5 - Chunk Loader only keeps the chunk it's in loaded, regardless of setting

### ISSUE THREAD

**Issue by beanzen** [TeamBR-Modding/NeoTech#282]
What Version of NeoTech are you using:
NeoTech 1.9 - 3.0.5
Forge 12.16.0.1858

The Chunk Loader block only keeps the single chunk it's located in loaded, regardless of the setting in the GUI. I have specifically tested for this with both crops and machines, with the Chunk Loader settings changed to each of the possible levels, and machines do not function and crops do not grow unless they are in the same chunk as the chunk loader, even if "1 around" or "2 around", etc are selected in the Chunk Loader GUI. 

If possible, did you break and replace the block:
Yes, no change to the problem.

Please Pastebin.com the crash Report and put link here:
No crash, so no crash report.

**Comment by pauljoda** [comment]
The issue may have been with data syncing, would you be able to test with the latest versions of Neotech and Bookshelf on our Jenkins?

**Comment by pauljoda** [comment]
From testing, seems to be fixed
