### ISSUE TITLE
Electric armor consumes multiple battery upgrades but only one is effective

### ISSUE THREAD

**Issue by dreness** [TeamBR-Modding/NeoTech#284]
What Version of NeoTech are you using: NeoTech-1.8.9-2.4.4

If possible, did you break and replace the block: N/A (I have not used a previous version, and the items in question were all crafted recently)

Please Pastebin.com the crash Report and put link here: No crash report!

After looking for documentation on how to install upgrades on electric gear and not finding any, I had to cheat and look at the source. While doing that, I learned that electric armor accepts a battery upgrade! Cool! Unfortunately I stopped reading once I figured out which speciality upgrades apply to which gear slots, and didn't continue reading to learn how the RF upgrades work. Turns out, they will happily consume more than one battery, even though the power cap is only raised for the first RF upgrade. I tried several batteries at once and also a single battery at a time (all Advanced batteries), and the cap was raised only once to 100k. Maybe this is why battery upgrades don't count against the upgrade limit...

Perhaps I can still apply an 'elite' battery upgrade?! Hmm! I gotta go :)

**Comment by pauljoda** [comment]
The upgrades were intended to be you can swap the battery in to a new one, overwriting the old one. So you can only have one at a time
