### ISSUE TITLE
Daimond fluid tank has capacity of 16 buckets when placed down

### ISSUE THREAD

**Issue by OPlurker1005** [TeamBR-Modding/NeoTech#286]
What Version of NeoTech are you using: 1.9-3.0.5

If possible, did you break and replace the block: yes

I made a diamond, filled it with lava and the tank only holds 16,000 mb when placed down. When I picked it up and look at in it my inventory it showed 16,000/64,000 mb.

**Comment by MrTubzy456** [comment]
I can give some more insight into this as I just came across this in 1.9-3.0.6. And I ran into it in the Pioneers modpack but, I wasn't exactly sure what had happened.

I took an iron tank and filled it with lava and emptied it. Then I upgraded it to a gold tank. After upgrade, it would still only hold 8 buckets.

**Comment by quasarea** [comment]
Same issue as MrTubzy456 describes, the Pioneers pack, affects also diamond tanks. Actually I ended up with 5 of them holding 16buckets, switched to creative and added 2 from command line, those two after filling fixed all others, and now all have 64b
