### ISSUE TITLE
Internal server error when breaking a dimensional crate

### ISSUE THREAD

**Issue by shortybsd** [TeamBR-Modding/NeoTech#289]
When breaking a dimensional crate it kicks the client with 'Internal server error' then server gives error from pastebin below. When you log back in, the crate is duped.

What Version of NeoTech are you using:
NeoTech-1.9-3.0.5
Forge Version: 1.9-12.16.0.1862-1.9
If possible, did you break and replace the block:
Yes.
Please Pastebin.com the crash Report and put link here:
http://pastebin.com/1dggsXmV

**Comment by JCMais** [comment]
Same here: https://gist.github.com/JCMais/10afdd6629d7b4fb2c2b9b32af0c345d

Probably related to: https://github.com/TeamBR-Modding/NeoTech/issues/262

Following https://github.com/Glitchfiend/BiomesOPlenty/issues/728, I [updated BoP](http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/) and it fixed the crash when breaking.

But now it crashes when getting the dropped item. Same error. Commented about it here: https://github.com/Glitchfiend/BiomesOPlenty/issues/698#issuecomment-217538257

**Comment by pauljoda** [comment]
Dim storage removed
