### ISSUE TITLE
[1.8] Centrifuge tank outputs not working consistently

### ISSUE THREAD

**Issue by Gotolei** [TeamBR-Modding/NeoTech#290]
1.8.9-2.4.4

Pink outputs from the second (right) tank, even though it highlights the first tank in the gui.
Vice-versa for yellow.

E: or at least that what I think is happening? The whole thing is really janky and inconsistent when it comes to outputting, seems every time I want to empty the tanks I have to click through the config and cycle the relevant face to make it actually happen.

**Comment by pauljoda** [comment]
There is one color that defines all outputs, and then a separate color for each individual. If you have one side set to all output, and one to single, it will only show the both in the gui. This is how TE did it and what we based our system off of. If you have a specific instance it is not working please provide screenshots with your explanation as it is hard to visualize what you are saying

**Comment by Gotolei** [comment]
Yeah now that I go to reproduce it it ofc is working swimmingly. Once it's running a job it chugs along without incident (like its current task of three stack's worth of dirty silver), it's just getting it started and finished that's annoying. Using the individual outputs fwiw.
I'll see if I can catch it misbehaving again, but it'll be a while.
