### ISSUE TITLE
[1.9] Upgraded Electric Pickaxe causes client side RF Storage item entities

### ISSUE THREAD

**Issue by Melakion** [TeamBR-Modding/NeoTech#291]
What Version of NeoTech are you using: NeoTech-1.9-3.0.5 - Forge 1865

Looking at RF Storage with Upgraded Electric Pickaxe in hand causes client side item entities to shoot out everywhere.   http://imgur.com/ILOIbff

Verified in a test world with only NeoTech, JEI and Waila installed.

Electric Pickaxe, upgraded with 5 \* fortune, 2 \* area, Obsidian, Shovel, and Speed upgrades. Look at RF Storage with the pick in hand. 

Tried to do a 2nd one step by step to see which particular upgrade was causing it but couldn't get it to reoccur with the 2nd pick, but is reproducible with one pick.

**Comment by pauljoda** [comment]
This is a small issue with forge we are waiting for a fix for. Might be fixed by now but essentially forge is broken

**Comment by garath77** [comment]
I'm also seeing this issue using the latest version of Forge [1.9-12.16.1.1900]. Oddly enough, I only see the issue when I'm using an Electric Pickaxe with an AOE upgrade on it. My original had Shovel, Fortune 3 and Mining Speed 2 with no issues. Then I added AOE 2, Lighting and ST, and the issue started. I created a new one, no issues, put AOE on it, and the issue started again.

**Comment by pauljoda** [comment]
Can't seem to replicate it in latest release. Closing unless brought up again
