### ISSUE TITLE
[1.9] Crash upon placing RF storage

### ISSUE THREAD

**Issue by ProthosMP** [TeamBR-Modding/NeoTech#292]
What Version of NeoTech are you using:
Neotech 1.9-3.0.5
forge-12.16.0.1865
Bookshelf-API-1.9-3.0.4
## If possible, did you break and replace the block:

Please Pastebin.com the crash Report and put link here:
[crash](http://pastebin.com/vNdauWQk)

**Comment by pauljoda** [comment]
One of the mods you have installed is using the old non official rf api. We use the official one. This is not an issue on our point. Please find the mod not using the official api and ask them to fix it. I think progressive automation had that issue at some point

**Comment by ProthosMP** [comment]
Oeps! You are right. It was extrautillities..
Sorry for the spam.
