### ISSUE TITLE
Electric Logger + forest

### ISSUE THREAD

**Issue by Stabington** [TeamBR-Modding/NeoTech#293]
What Version of NeoTech are you using:
1.9-3.0.5

So, I just made the unfortunate choice of placing my electric logger next to a forest.
One of the trees in the farm grew, and the leaves merged with the leaves of one of the trees in the forest... then the machine proceeded to chop down large parts of the forest.

Think it might need a cap on how far it goes

**Comment by pauljoda** [comment]
There is a cap, its just very large. Long live chaos
