### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rcistano** [TeamBR-Modding/NeoTech#295]
What Version of NeoTech are you using: 1.8.9

I would like to request a multi-block structure. RF storage bank. The bigger it is the more it holds. You can also maybe create a fluid storage. Maybe even a wireless block or feature to wireless transport rf, fluid or items.

**Comment by pauljoda** [comment]
This will be implemented in Modular Systems. I wouldn't want to write the same thing twice

**Comment by rcistano** [comment]
Modular Systems isn't supporting 1.8.9
