### ISSUE TITLE
[1.9] [Suggestion] Jetpack and Elytra upgrades too cheap?

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamBR-Modding/NeoTech#296]
I've been playing with the 1.9 version recently and noticed one thing about suit upgrades.

Some of them might be way too cheap? Like flight for  feather and gunpowder? Or Elytra update. I personally think they should require bit more effort to get materials for. (Some other mods allow flight after you kill wither for example)

**Comment by pauljoda** [comment]
For sure, the armor/tools are far from done. The textures/recipes and all that need attention. We are still in the functionality stage at the moment. So enjoy cheap stuff for a bit

**Comment by dreness** [comment]
Glad to hear you say this, I have been wrestling with this a little myself :)

**Comment by pauljoda** [comment]
I'm closing this for now as the recipes will be opened up for discussion when it is closer to complete
