### ISSUE TITLE
Pipe from alloyer to TC Smeltery -> crash

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#297]
What Version of NeoTech are you using:
2.4.1 on FTB Unstable 3.0.42 (SSP, most recent, no changes)

I attempted to connect the electric alloyer to a Tinkers' Construct Smeltery (to make a steel hammer head) and once I told the NeoTech pipe to pull from the alloyer the game crashed. Attempts to reload almost work. The game will load to the pause menu (when it's in the background), but freeze or crash on attempting to resume.

I attempted to update NeoTech to 2.4.4, but the game doesn't finish loading. There is some gibberish text or garbled symbols on the dirt background with no buttons or anything.

If possible, did you break and replace the block:
N/A

Please Pastebin.com the crash Report and put link here:
The original crash: http://pastebin.com/1213cd9f
Reload crash: http://pastebin.com/1SntEsTt

Failed attempt to update's loading log (if it helps)
http://pastebin.com/Kkfvf4Fy

**Comment by pauljoda** [comment]
Pipes are no longer implemented
