### ISSUE TITLE
Electromagnet attracts creepers

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#298]
What Version of NeoTech are you using:
2.4.1 on FTB Unstable 3.0.42 (SSP, most recent, no changes)

My NeoTech electromagnet began attracting creepers and skeletons. It didn't always happen, but I was able to observe the mobs being dragged through the water under my base, seen them fly towards me and got hit in the back of the head by an exploding creeper I didn't even see. :)

**Update**: It's definitely reproducible. I created a creative world and gave myself an electromagnet, creative rf battery, and creeper spawn eggs. I just flew around the map a few blocks off the ground dragging the creepers behind me. Nothing else I tried was dragged. (Perhaps the skeleton I saw earlier was being pushed by the creeper.)

If possible, did you break and replace the block:
N/A

Please Pastebin.com the crash Report and put link here:
N/A

**Comment by pauljoda** [comment]
This is not a bug. It is intentional. I'm a little evil I guess. It attracts projectiles like arrows and ghast/blaze fireballs, lit tnt, creepers, exp, items and I believe that it is. Eventually I'll add an upgraded version that just does items and such but for now I enjoy the chaos

**Comment by ghost** [comment]
"Balance!"

**Comment by ghost** [comment]
Evil! :) I think maybe the creeper's a bit too much. Knowing you're going to get pummeled by skeletons and ghasts is a trade off. Choosing to take the ring off when using TNT becomes a matter of being careful. All the hings the ring attracts are items of some kind that are only acted on by game physics. Having a creeper sucked into the back of your head on the other hand... Kind of not worth it.
