### ISSUE TITLE
[1.9] Pipe dup'ing with NeoTech wrench

### ISSUE THREAD

**Issue by kwpugh** [TeamBR-Modding/NeoTech#299]
What Version of NeoTech are you using: NeoTech-1.9-3.0.6.jar

If possible, did you break and replace the block: shift-click with the NeoTech wrench on a single, placed pipe, the pipe stays in place but an additional pipe is produced.

Please Pastebin.com the crash Report and put link here: no crash report

**Comment by ibhoe** [comment]
same issue and it dupe's tanks as well i have a vid of it happining https://www.twitch.tv/ibhoe/v/62985685

**Comment by ProsperCraft** [comment]
Have the same issue

**Comment by DanWehr** [comment]
May be worth noting that this appears to only happen with item/fluid/energy pipes. Regular pipes are removed correctly without duplication when shift-right-clicked.

**Comment by pauljoda** [comment]
Pipes have been removed
