### ISSUE TITLE
RF Incompatibility

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#3]
Your mod is now incompatible with Progressive Automation and Flux Ducts. They'll connect to your mod and vice versa, but your mod will not power them.

**Comment by kreezxil** [comment]
And now an actual server crashing situation replete with bug reports in regards to this.
"neotech crashing server when being interfaced to fluxducts"
server crash report: http://pastebin.com/BtE8ycgq
server fml latest: http://pastebin.com/ygB9Y6mS

**Comment by Dyonovan** [comment]
Until (which isnt going to happen from what I can tell) CoFH makes an official API for 1.8, I am going to call this mod dead as to many mods are trying to implement there own versions of RF.

**Comment by kreezxil** [comment]
In other words you have given up on neotech?

-----Original Message-----

**Comment by kreezxil** [comment]
Also would like to point out something you might be missing. By waiting on the RF API to be officially ported you are essentially ensuring that no one will use your mod for long. Right now as it stands, you bring to the table what is missing in technology because of the fact that the RF API is not officially ported and by continuing development you will ensure that when the times come your following for NeoTech will be far greater than the ones in Industrial Craft, Build Craft, Thermal Expansion and possibly Tinker's Construct.

However, wait for that port, and those four big four will most likely instantly port over within a week afterwards and introduce tons of new features in the process. But you won't be ready for it because you decided to wait.

Just thought I would tell you about that angle.

If you are giving up that is fine. I can accept that.

**Comment by Dyonovan** [comment]
Its not a matter of being bigger then the other mods. I actually dont care about that. Nothing has changed on NeoTech end, so it has to be due to a change on the other mods end. We believe we are using the RF API the way it should be for the changes to ForgeDirection in 1.8. Unless the other Mods can agree on using and sticking to one implementation of the API, every time a mod decides to change there implementation means we have to go through and figure out the change and implement it. There needs to be 1 implementation of it.

**Comment by kreezxil** [comment]
As it stands you're one three mod authors using an RF API. If this is Al that it would take to keep you working on Neotech then which implementation would you like me to relay to Vanhal and Fyberoptic?

-----Original Message-----

**Comment by kreezxil** [comment]
Well, I found a solution. And if anyone tries to point this out again in regards to flux ducts. Just tell them they don't need flux ducts. Turns out your cable feeds Progressive Automation machines just fine. My only issue with it and it is so minor now is that your cable does not show that is connected to Progressive Automation machines although those machines have no issues with drawing from it and I suspect adding to it.

That all said, I still wish you would continue development on the mod despite everything.

**Comment by MtnDrew** [comment]
Yes please continue. As of right now, and probably for a while, you are the only ore doubling mod in 1.8

**Comment by kreezxil** [comment]
Actually he isn't. There is Techstack's Heavy Machinery Mod, which will double ore too. The only difference is you have to use large machines and a bit of more involved process to do it. Another mod that doubles ore is Progressive Automation by Dr. Cyano. You can find both of the links to those mods on my website at http://www.kreezcraft.com and a whole lot more.
