### ISSUE TITLE
[1.9-3.0.6] Odd redstone control behavior with item pipe

### ISSUE THREAD

**Issue by DanWehr** [TeamBR-Modding/NeoTech#301]
What Version of NeoTech are you using:
1.9-3.0.6

I noticed this issue in a more complicated setup, then built a smaller test case. Two chests connected with an item pipe, using the left chest as output to the right one. Motherboard with control upgrade added to pipe for redstone control. Pipe also set to allow any item through.

My understanding is that a pipe set to "high" will only work if it is receiving a redstone signal. If it's set to low it won't work if it is receiving a redstone signal. 

Using "high", partial strength signals don't seem to activate the pipe (one space of dust between lever and pipe) so I figured it required a max strength signal to work. Placing a lever directly beside the pipe would function as expected. At the same time though, using a redstone repeater besides the pipe to create a max strength signal would not activate the item transfer.

I think a bit of that weirdness is happening with the "low" setting as well. I had one case for a moment where a partial strength signal would not stop an item pipe, but I did not check at the time to see if a full strength signal would stop it (if so, the same lever/repeater difference from above may also be at play).

**Comment by MaPePeR** [comment]
This is also happening with Fluids and its very annoying.

**Comment by MaPePeR** [comment]
I think the problem is, that the pipe only accepts a weak redstone signal, when the dust is below the pipe.

**Comment by pauljoda** [comment]
Pipes are no longer implemented
