### ISSUE TITLE
Crash at startup on 1.9 / 1.9-3.0.6 / forge-1.9-12.16.0.1865

### ISSUE THREAD

**Issue by dreness** [TeamBR-Modding/NeoTech#302]
What Version of NeoTech are you using: NeoTech-1.9-3.0.6-dev

Forge version: forge-1.9-12.16.0.1865

If possible, did you break and replace the block: n/a

Crash report: http://pastebin.com/WVDi593e

**Comment by Dyonovan** [comment]
Delete the neotech config directory and let it recreate. See if that fixes it

**Comment by dreness** [comment]
Tried that, but I think I'm getting the same crash: http://pastebin.com/b492PCap

**Comment by dreness** [comment]
Incidentally neotech works fine for me in 1.8.9, but I'm trying to get to 1.9. I did make a new minecraft directory for the 1.9 tests.

**Comment by dreness** [comment]
Boom! Same as https://github.com/TeamBR-Modding/NeoTech/issues/76

Somehow I ended up with a -dev version and didn't notice that this was a problem. I downloaded "NeoTech-1.9-3.0.6.jar" and no more crashy :)
