### ISSUE TITLE
Suggestion [Energy Packs]

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#303]
I know this very Thermal Expansion like but , would it be possible to add some sort of "capacitor" to power armor , tools and other mods item that would require it. (e.x. powered wrench)

**Comment by OH-Herobrine** [comment]
The batteries work like that, im pretty sure, said something like that in the spotlight videos they uploaded

**Comment by ghost** [comment]
im an idiot sorry.
