### ISSUE TITLE
Crash when placing down Dim crate

### ISSUE THREAD

**Issue by b0bst3r** [TeamBR-Modding/NeoTech#304]
What Version of NeoTech are you using: NeoTech-1.9-3.0.6

If possible, did you break and replace the block: It didn't place the block down.

Please Pastebin.com the crash Report and put link here: http://pastebin.com/YUa2eNVp

Forge 1865

**Comment by ChilledDayz** [comment]
I have the same problem, If you need the crash report I can post later. Only seed to happen after I installed malissis doors.

**Comment by SDUBZ** [comment]
ive noticed it crashes when shift right clicking to pick up crate also

**Comment by pauljoda** [comment]
This block is removed
