### ISSUE TITLE
Dimensional crate tries to set facing to down when looking up.

### ISSUE THREAD

**Issue by stephen-dahl** [TeamBR-Modding/NeoTech#305]
What Version of NeoTech are you using: 1.9.0-3.0.6
If possible, did you break and replace the block: yes
Please Pastebin.com the crash Report and put link here: http://pastebin.com/ZqQJ1sbN

I placed a dimensional crate while looking up. stack indicates that it tried to set the facing of the block to down which is not a valid value. Probably easily fixed by ignoring Y when detecting what direction the block should face so that it will always come out as a side and not up or down.

**Comment by stephen-dahl** [comment]
Correction, still setting facing to down no matter what direction I look

**Comment by pauljoda** [comment]
This block is removed and no longer in the mod
