### ISSUE TITLE
[1.9] Electric Pump doesn't work.

### ISSUE THREAD

**Issue by Ermen07** [TeamBR-Modding/NeoTech#306]
What Version of NeoTech are you using: NeoTech-1.9-3.0.6

If possible, did you break and replace the block: Yes

Please Pastebin.com the crash Report and put link here: No crash report

**Comment by pauljoda** [comment]
No it does not

**Comment by ikkonoishi** [comment]
*smacks face.

I just spent 20 minutes messing with pipe settings going "What am I doing wrong?" Looks like Operation Dry Pigmen is going to have to be on hold for a while.

**Comment by pauljoda** [comment]
Pump is being removed
