### ISSUE TITLE
[1.9-3.0.6] Electric pickaxe area upgrade does not work.

### ISSUE THREAD

**Issue by DanWehr** [TeamBR-Modding/NeoTech#310]
What Version of NeoTech are you using: 1.9-3.0.6

If possible, did you break and replace the block: Not relevant.

I have attempted to add the AoE upgrade to an electric pickaxe, first to a 3x3 area and then a 5x5 area. In both cases the pickaxe still only mines a single block at a time.

This pickaxe also has cobalt, silk touch, speed, and shovel upgrades, if that's relevant.

**Comment by kjj194** [comment]
Make sure to check your keybinds and use the neotech tool config button to turn on the option.

**Comment by pauljoda** [comment]
Yes, enable using the keybind, is off by default
