### ISSUE TITLE
[1.9] [3.0.6] Net launcher loses nets..

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamBR-Modding/NeoTech#312]
I noticed if you simply click net launcher with net in your inventory, it wont shoot it but it simply consumes power and net disappears..

**Comment by sandalle** [comment]
I'm seeing this as well using http://www.technicpack.net/modpack/extreme-19-mega-pack.827977 version 4.3.1 (NeoTech 1.9-3.0.6 on Forge 12.16.1.1901) in SMP (server with clients connecting, running same version of Extreme 1.9 Mega Pack).
