### ISSUE TITLE
Crash n World loading

### ISSUE THREAD

**Issue by canitzp** [TeamBR-Modding/NeoTech#316]
The mod does crash while loading my singleplayerworld. i see the same crash on a server but after restarting them everything works fine

What Version of NeoTech are you using:
Forge: 1887
NeoTech: 1.9-3.0.6

If possible, did you break and replace the block:
No

Please Pastebin.com the crash Report and put link here:
http://paste.ee/p/NycGz

**Comment by pauljoda** [comment]
Info missing

**Comment by canitzp** [comment]
What exacly do you mean with Info missing. I writet every detail I know. A list of my mods can you see in the crash-report

**Comment by canitzp** [comment]
Okay I see. The link is broken. I fix it later today
