### ISSUE TITLE
Phantom Glass, Void Glass and Rock Climbing Wall not appearing in JEI

### ISSUE THREAD

**Issue by eslachance** [TeamBR-Modding/NeoTech#318]
What Version of NeoTech are you using: 2.4.4 on 1.8.9.
Mod pack: The Pioneers (Curse)

I'm on "The Pioneers" mod pack from Curse which, to my knowledge, does not change any recipes for any mods. I've verified that I indeed have NeoTech-1.8.9-2.4.4.jar (which is I believe the latest version).

Neither the Phantom Glass, Void Glass or Rock Climbing Wall appear in my JEI when searching for them by name. However, I can actually craft the item as long as I know the recipe, and if I hit R on the item after crafting, it does show me the recipe as a "Crafting Table" recipe. 

Screenshot, if that's any use to you: 
![2016-05-09_01 10 25](https://cloud.githubusercontent.com/assets/643344/15104219/055d676a-1583-11e6-85e3-b8e03c1fa8ea.png)

**Comment by pauljoda** [comment]
Must be an issue with the pack, verified to work
