### ISSUE TITLE
pipes crashing multiplayer server

### ISSUE THREAD

**Issue by beyondthewall** [TeamBR-Modding/NeoTech#32]
i added item pipes (extract, insert and white pipes) to my world and when the first item hit the extraction pipe the server crashed (it didn't as long there were no items in the pipe). the same setup worked in singleplayer though.

**Comment by Dyonovan** [comment]
Need a copy of the crash log. Please use pastebin

**Comment by beyondthewall** [comment]
of course. what was i thinking. :)
here the server crash log: http://pastebin.com/raw.php?i=yjSpvBvj

**Comment by beyondthewall** [comment]
btw. i just tested it and this also happens with energy pipes (but only when there runs energy through)

**Comment by mahashel** [comment]
+1
Was going to post my crashlog, but it's virtually identical to the one shared by beyondthewall.
I am super-excited that you guys are rewriting NeoTech.  It's a great mod.  Let me know if there's anything you need me to test in greater detail.

**Comment by Watchful1** [comment]
Another one for me. Similar log

http://pastebin.com/iZYKLhVF

**Comment by mahashel** [comment]
I've been working around this multiplayer NeoTech crash for a couple months now by playing strictly in singleplayer mode.
Last week i wanted to play around with shaders and other graphical sweeteners so I installed OptiFine. Suddenly i started seeing this same pipe tessellation/ticking block crash again, despite being in singleplayer mode. It appears that I cannot use OptiFine while NeoTech is active, even in singleplayer.

**Comment by Dyonovan** [comment]
Sorry for the long delay in fixing this. Finally am able to get back to NeoTech. There is a strange issue with java on linux, that for some reason, Javax isnt installed as part of the java package. I think I have a fix for it which I am working on now.
