### ISSUE TITLE
[1.9-3.0.6] Phantom Glass suggestion, logger compatibility question

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#320]
What Version of NeoTech are you using: 1.9-3.0.6

If possible, did you break and replace the block:N/A

Please Pastebin.com the crash Report and put link here:N/A

I was just wondering if there were any plans for further integration with other mods. Specifically with the Logger. I'm using Biomes O Plenty and the logger doesn't accept any saplings except the vanilla ones. It does fine harvesting them, but it will not accept them into the planting area, so I have to plant them manually for it to work.
EDIT: I found out that the issue with compatibility with BOP is on their end, not yours.

Also, would it be possible to modify the phantom glass to allow a horse that a player is riding through it?

Thanks for all your hard work on this, it has quickly become one of my favorite mods!

**Comment by pauljoda** [comment]
The horse thing is actually a really good idea. I'm going to add that
