### ISSUE TITLE
Please don't lose my progress when there's no power

### ISSUE THREAD

**Issue by eslachance** [TeamBR-Modding/NeoTech#321]
So there's this _one_ thing that really irks me in this mod, which I'm otherwise falling in love with: The fact that progress is lost when the machine drains of all power. I understand the need for a little bit of a challenge keeping up with power demands in a network, but no other power mod (and, indeed, not even Vanilla furnaces!) lose progress when fuel or power runs out. This makes some progress into the game much more difficult - for instance, using the Thermal Binder to add upgrades to machines, or the crucible to melt down items.

I've had instances, because of this, where the alloy machine went into a loop because there wasn't enough stored power to provide for it in my power cell, so I had to disconnect it and wait for my cell to fill up before reconnecting it and proceed. 

Perhaps a configuration file option or a command? I'd love that...

**Comment by jriwanek** [comment]
No other? Electric Advantage does it as does IC2 IIRC, As for vanilla furnaces, If there's not enough fuel to complete a task, it'll start rewinding too.

**Comment by eslachance** [comment]
Hmm, maybe I'm just used to the "mainstream" tech mods but... IC2 doesn't reset (it slows down with low power, pauses with no power), TE didn't reset in 1.7 (ditto), neither did EnderIO.

You're correct about Vanilla furnaces rewinding, and I just tested Electric Advantage, and it will also slowly rewind when it loses power. 

Which still makes NeoTech the _only_ mod that I know of that will completely reset 95% of progress on any action down to 0% for lack of power for more than a tick or so (I haven't tested this extensively). This is also compounded by the fact that the "round-robin" Power Interface pipes are... inferior to every other power system I've seen with the only exception of Buildcraft's Kinesis pipes IMHO.

Like I said this is probably my _only_ gripe about this whole system. I agree with just about everything except this hard reset - losing hundreds of thousands of RF just because power failed at the last second on a motherboard binding action in the Thermal Binder is just... painful. And unnecessary.

**Comment by jriwanek** [comment]
Oh, I'm not saying it's a _bad_ gripe, I was just pointing out the error (Mod devs tend to be happier with suggestions when you're right on the money I've found)

**Comment by VaiN474** [comment]
I have to agree with eslachance. I did not expect this and lost a lot of fuel early game because of it being stuck in a loop. Not cool. At the very least I would expect machines to build up enough buffer to complete a full operation before starting, and/or pause the progress when power runs out.

**Comment by pauljoda** [comment]
As a middle ground, I will not make it reset, but start working in reverse when out of power. I hope this is fair
