### ISSUE TITLE
[1.9-3.0.6] Item interface pipes do not extract with Whitelist

### ISSUE THREAD

**Issue by Bamrak** [TeamBR-Modding/NeoTech#322]
What Version of NeoTech are you using:
3.0.6

When interfacing with the logger and modular systems, when the whitelist is used the pipes will not transfer items.  If you use no filter or a blacklist the pipes function under identical conditions. 

Example: I was attempting to extract saplings from the modular storage and send it to to the furnace generator via item pipes but if you use the whitelist, nothing happens. If you switch to blacklist items begin exporting.

**Comment by pauljoda** [comment]
Pipes are not in the mod anymore
