### ISSUE TITLE
Fluid Dupe Glitch

### ISSUE THREAD

**Issue by blakerdog** [TeamBR-Modding/NeoTech#323]
What Version of NeoTech are you using:
NeoTech 1.9 3.0.6
If possible, did you break and replace the block:
Yes I broke the block and replaced it.

When I shift right-click a Fluid Tank of any tier it drops another one and doesn't destroy the fluid tank that I clicked. I was able to reliably repeat this glitch with all tiers of fluid tanks.

Gif for reference: https://giphy.com/gifs/t2doOo6tkWwG4

**Comment by cauliflower69** [comment]
This is the same for pipes

**Comment by pauljoda** [comment]
Issue resolved in next release
