### ISSUE TITLE
JEI Crash (At least when looking up the electric sword).

### ISSUE THREAD

**Issue by Insufficient-Charge** [TeamBR-Modding/NeoTech#324]
What Version of NeoTech are you using:
3.0.6, on Curse Forge
If possible, did you break and replace the block:
There is no block
Please Pastebin.com the crash Report and put link here:
http://pastebin.com/i6eWS6mW

I installed Neotech in my world, and immediately went to look up a recipe. I crashed when I randomly clicked on the electric sword recipe in JEI. I've tried clicking on a few other things from Neotech but most of the machines are working just fine.

**Comment by pauljoda** [comment]
Must have been version issues. Resolved in latest versions of each
