### ISSUE TITLE
Control Upgrade prevents crafting of redstone torch

### ISSUE THREAD

**Issue by athenashavoc** [TeamBR-Modding/NeoTech#325]
What Version of NeoTech are you using: 1.9-3.0.6

If possible, did you break and replace the block: n/a

Please Pastebin.com the crash Report and put link here: n/a

**Comment by VaiN474** [comment]
This is the issue that lead me here. I can understand accidental conflicts with other mods, but please ensure your recipes don't conflict with vanilla ones.

For the Control Upgrade I'd suggest using a recipe with redstone and a lever instead of a stick.

**Comment by pauljoda** [comment]
Recipes are not final, this is one I never thought about until done. Will be changed
