### ISSUE TITLE
Wrong ore/material into Crusher crashes me

### ISSUE THREAD

**Issue by onestacked** [TeamBR-Modding/NeoTech#326]
What Version of NeoTech are you using: 19-3.0.6

If possible, did you break and replace the block: Yes also new world didn't fix it ether

Please Pastebin.com the crash Report and put link here: http://pastebin.com/gR10eXjE

Puting something inside a crusher that has no recipe minecraft crashes it dont matter if through pipes or the GUI

**Comment by GiantTreeLP** [comment]
The same happens on 1.8.9-2.4.4.

Server crashes immidiately after joining.  
Logs got deleted while restoring the backup, though.

**Comment by pauljoda** [comment]
Reloading the json files should help solve this issue, clean install works with no issues on server and client
