### ISSUE TITLE
[1.9 3.0.6] Logger and Item Pipes

### ISSUE THREAD

**Issue by TrickDescent** [TeamBR-Modding/NeoTech#328]
What Version of NeoTech are you using:1.9-3.0.6

If possible, did you break and replace the block: Yes, changed nothing.

Please Pastebin.com the crash Report and put link here: Not a crash, but the item pipes are trying to extract the axe from the logger. However, it cannot actually grab the axe, making the pipe get stuck and refuse to pull anything else out of the logger until there is no more axe in the axe slot. The shear slot is having the same issue.

**Comment by pauljoda** [comment]
Pipes have been removed
