### ISSUE TITLE
Feature Request - Disable Server Movement Check

### ISSUE THREAD

**Issue by dannydjdk** [TeamBR-Modding/NeoTech#331]
What Version of NeoTech are you using: 1.9-3.0.6

When running on a server, it is not possible to fly fast with the NeoTech Elytra upgrade because of a vanilla Minecraft issue which prevents players from moving too fast on servers (Reported here: https://bugs.mojang.com/browse/MC-90062). The result is a spammed server log and worse, the player gets pulled back to a previous location which make flying with the Elytra upgrade very painful, annoying and dangerous. There is a vanilla gamerule called disableElytraMovementCheck which apparently fixes this issue for the vanilla Elytra, but it does not seem to help with the NeoTech Elytra upgrade (or boats, horses, TNT cannons or anything else for that matter).

Mojang does not seem to be interested in addressing this anytime soon. It would be great if there were a way to add support for this gamerule to the NeoTech Elytra upgrade. Even better, NeoTech would be a super hero if it could provide an option to disable this asinine "feature" of vanilla Minecraft entirely.

**Comment by pauljoda** [comment]
We simply emulate the Elytra, if the server is having issue with that then that is out of our hands and the responsibility of mojang. Disable the flight check in your server config and the issue should be resolved.
