### ISSUE TITLE
Game crash with Optifine when placing rock climbing wall

### ISSUE THREAD

**Issue by acokeaday** [TeamBR-Modding/NeoTech#332]
What Version of NeoTech are you using: 
NeoTech-1.9-3.0.6
Forge 1.9

If possible, did you break and replace the block:
Place a rock clmbing wall block and the game crashes

Narrowed down to Optifine 
OptiFine_1.9.0_HD_U_B2 / OptiFine_1.9.0_HD_U_B3

Removed all mods and added one by one testing each mod by entering game and placing a rock climbing wall. (Mod list below.)

game only crashed with Optifine in client. 

Please Pastebin.com the crash Report and put link here:

Error report 
http://pastebin.com/S05smGrz

Mods used:
ArmorPlus1.12.2(1.9)
Bagginses-1.9-2.3.0b
BloodMagic-1.9-2.0.0-38
Bookshelf-API-1.9-3.0.4
Chameleon-1.9-2.1.3
Chisel-MC1.9-0.0.4.14
chiselsandbits-9.18
Harvest-1.9-1.0.1-3
InventoryTweaks-1.61-dev-49
ironchest-1.9-6.0.133.777
jei_1.9-3.3.3.200
journeymap-1.9-5.2.0b1-unlimited
Mantle-1.9-0.9.4
NeoTech-1.9-3.0.6
OptiFine_1.9.0_HD_U_B2
Quark-beta-18
Ruins-1.9
Ruins-1.9-sources
StorageDrawers-1.9-3.1.6
TConstruct-1.9-2.2.2
UpdateCheckerMod-1.9
UpdateCheckerMod-1.9-sources
VillageInfoMod-1.9-8
Waila-1.7.0-B2_1.9
WailaHarvestability-mc1.9-1.1.7

**Comment by pauljoda** [comment]
We have seen an issue like this before, but it is not on the end of our renderer. Closing for now unless I find it is our fault
