### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vVwd** [TeamBR-Modding/NeoTech#333]
I tried to get the crucible to melt glowstone into molten glowstone without much succes. I tried pointing the config to substratum fluid glowstone, causing the mod to crash. I blame myself for this one, kinda expected it to happen. It does acccept glowstone, redstone & ender pearls as an input item, there is no valid output item for it that works. I am the latest version for 1.9.

What I would like to suggest is a couple more possible outputs: liquid glowstone, redstone and pearl for the alloys made out of 3 items. Possibly other outputs maybe, might have missed some. Maybe a 3rd slot to the alloy smelter so alloys like lumium, signalum & enderidium can be made?

**Comment by pauljoda** [comment]
This is up to the user to use the config to add. It may take a few guesses to find the name but we do support user added recipes
