### ISSUE TITLE
Item interface pipe not checking getCapability

### ISSUE THREAD

**Issue by raoulvdberge** [TeamBR-Modding/NeoTech#336]
Hi, I have a small question about the interface pipes.

[Why do you expect a destination tile to implement IItemHandler?](https://github.com/TeamBR-Modding/NeoTech/blob/1.9/src/main/scala/com/dyonovan/neotech/pipes/tiles/item/ItemInterfacePipe.scala#L201)

Shouldn't you be using `getCapability` there? Thanks.

**Comment by pauljoda** [comment]
This was during the period where not all mods had implemented the capability system. We were trying to handle all cases. Either way, this is now invalid as the pipes are gone
