### ISSUE TITLE
Pump Isnt Working 1.8.9

### ISSUE THREAD

**Issue by DrSmCraft** [TeamBR-Modding/NeoTech#339]
What Version of NeoTech are you using: NeoTech-1.8.9-2.4.4

If possible, did you break and replace the block:Yes

Please Pastebin.com the crash Report and put link here: No Crash.

I was testing with the electric pump. I added power and a tank, but It wasn't pumping anything. I tested it with all kinds of liquids especially water and lava to no avail. The liquid isnt being replaced with stone. Please fix this bug. Thank you.

**Comment by derSchotte** [comment]
I have the same bug in NeoTech-1.9-3.0.6 for Minecraft 1.9 / Forge 1900

**Comment by pauljoda** [comment]
Pump is being removed
