### ISSUE TITLE
1.9-3.0.6 - Crash on startup

### ISSUE THREAD

**Issue by OhiraKyou** [TeamBR-Modding/NeoTech#341]
NeoTech-1.9-3.0.6

Crash occurs either on startup or shortly thereafter. Happens consistently only with NeoTech installed. I have not placed a NeoTech block or spawned any in my inventory (and haven't had time to due to the crash). This is on an existing superflat world.

Here's the crash report: http://pastebin.com/yu5aRMa3
And, here is the log from MultiMC: [NeoTech crash](https://github.com/TeamBR-Modding/NeoTech/files/287562/NeoTech.crash.with.JEI.txt)

**Comment by pauljoda** [comment]
Not our mod, some other mod is overwritting the client rendering. Check the better foliage mod
