### ISSUE TITLE
Game Crashes Steel JEI Recipe

### ISSUE THREAD

**Issue by acokeaday** [TeamBR-Modding/NeoTech#344]
What Version of NeoTech are you using:
Neotech 1.9
If possible, did you break and replace the block:
Game crashes each time i review Steel recipe in JEI
Please Pastebin.com the crash Report and put link here:

[crash-2016-05-31_01.22.27-client.txt](https://github.com/TeamBR-Modding/NeoTech/files/289926/crash-2016-05-31_01.22.27-client.txt)

**Comment by pauljoda** [comment]
Fixed in latest bookshelf
