### ISSUE TITLE
Duping Interface Pipes

### ISSUE THREAD

**Issue by RaineAndrews** [TeamBR-Modding/NeoTech#345]
What Version of NeoTech are you using: 1.9 3.0.6

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: N/A

Sneak right-clicking with a neotech wrench on an energy interface pipe results in 2 popping out of it, leaving the original there.  This dupes interface pipes!

**Comment by TigersFangs** [comment]
What Version of NeoTech are you using: 1.9.4-3.1.0 on MC 1.10.2

If possible, did you break and replace the block: N/A

Please Pastebin.com the crash Report and put link here: N/A

I would like to add that this is still a thing and it is ALL interface pipes, not just the energy ones. Structure pipes work properly, but sneak right-clicking on any of the three interface pipes(Item, Fluid, Energy) will give you and infinite amount of pipes that just shoot off in all directions. You can do this forever and end up with stacks and stacks of them.

**Comment by pauljoda** [comment]
Fixed in latest version, also pipes are gone
