### ISSUE TITLE
Item interface pipe pulls from incorrect slots in RFTools Crafter

### ISSUE THREAD

**Issue by jkneuf** [TeamBR-Modding/NeoTech#346]
What Version of NeoTech are you using:1.9-3.0.6

If possible, did you break and replace the block: Yes

Please Pastebin.com the crash Report and put link here: N/A

I'm not sure if this is a NeoTech issue or an RFTools issues. I set up the RFTools Tier 3 Crafter powered by a NeoTech energy pipe with an interface pipe inserting on one side and extracting on the other side. The energy and insert pipes work great, but the extract pipe, no matter which side it is attached to, tries to pull from the crafting recipe area inside the Crafter instead of the export area.

**Comment by pauljoda** [comment]
Pipes are no longer implemented
