### ISSUE TITLE
Alloyer problems

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#348]
What Version of NeoTech are you using:3.0.6

If possible, did you break and replace the block:not yet, because I don't want to lose the contents

I accidentally put molten iron in both imputs of the alloyer it doesn't know what to do with it, but I can't figure out how to get anything back out. I've tried buckets and tanks, as well as fluid interface pipe. Is this an issue or am I doing something wrong?

**Comment by pauljoda** [comment]
There is currently no way to pull fluids out, in the future we will find some way to allow
