### ISSUE TITLE
energy system seems to be broken

### ISSUE THREAD

**Issue by Venom1987** [TeamBR-Modding/NeoTech#349]
What Version of NeoTech are you using: 1.9-3.0.6

If possible, did you break and replace the block: cant...crashes as soon as i open the save 

Please Pastebin.com the crash Report and put link here: http://pastebin.com/mssHGKu0

I also recieved a ton of error messages related to energy when placing the electric crucible next to a generator...

**Comment by pauljoda** [comment]
Some mod is using an invalid RF api, pipes are also gone now
