### ISSUE TITLE
Crucible crashes and pretty much corrupts maps

### ISSUE THREAD

**Issue by Zemnic12** [TeamBR-Modding/NeoTech#350]
What Version of NeoTech are you using:
Neotech-1.8.9-2.4.4 

If possible, did you break and replace the block:
Impossible, only was able to remove using a map editor

Please Pastebin.com the crash Report and put link here:
http://pastebin.com/Ztrqgi2n

**Comment by pauljoda** [comment]
Issue was related to Fluid Handler loading and the new Forge NBT system, resolved in next release
