### ISSUE TITLE
[Feature Request] AOE control and Silk Control

### ISSUE THREAD

**Issue by Phonavis** [TeamBR-Modding/NeoTech#351]
While AOE is toggleable on and off using the Armor and Tool menu, there isn't an option to switch between 3 x 3 and 5 x 5, could an option be added for this, as well as Silk touch/Fortune being made exchangeable? At the moment if you have both silk touch and fortune, only silk touch will take effect, nullifying Fortune at all. And while 5x5 is good for mining, I find 3x3 more useful for base building.

**Comment by pauljoda** [comment]
This is an intention of the upgrade system, you will have to plan out your tool and possibly have two tools for different purposes. I will keep these in mind as I continue and might make silk touch toggleable
