### ISSUE TITLE
Crashes on load after extremely long load time. 

### ISSUE THREAD

**Issue by varukasalt** [TeamBR-Modding/NeoTech#352]
NeoTech-1.9.4-3.1.0

If possible, did you break and replace the block: Unable. Bug does not appear when NeoTech is removed

http://pastebin.com/REDN5Ue8

**Comment by Dyonovan** [comment]
Looking at the log:

> java.lang.OutOfMemoryError: Java heap space
> 
> Memory: 194641248 bytes (185 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)

With that many mods, you need more then 1G

**Comment by varukasalt** [comment]
That's strange. I have 32 gigs of RAM 

Never mind. I see it. Thanks.

**Comment by Dyonovan** [comment]
What are you using to run minecraft? Which launcher? You need to change a couple of flags

Lol nm. Saw you found it

**Comment by varukasalt** [comment]
I fixed it. Totally forgot about that 1 gig default. Built a new system and it was so much faster I didn't notice until now. Put 20 of 32 gigs at it. Smooth as butter. Sorry for the false report. Keep up the good work.
