### ISSUE TITLE
Obsidian duping using Tinker's Construct

### ISSUE THREAD

**Issue by Insufficient-Charge** [TeamBR-Modding/NeoTech#353]
What Version of NeoTech are you using:
2.4.4, Minecraft 1.8.9
If possible, did you break and replace the block:
Not possible
Please Pastebin.com the crash Report and put link here:
Not a crash.

Obsidian into Tinker's smeltery makes 288 mb of Molten Obsidian.
Molten Obsidian in Electric Solidifier, takes only 36 mb to make 1 obsidian.
I didn't test this, just saw it in JEI.
![2016-06-19_14 16 28](https://cloud.githubusercontent.com/assets/13188566/16179345/712baf9a-3628-11e6-8ae7-165be9011d48.png)
![2016-06-19_14 16 15](https://cloud.githubusercontent.com/assets/13188566/16179346/74124886-3628-11e6-8200-dd014a30e807.png)

A fix for this would probably be to have obsidian melt into 288 mb, and solidify using 288 mb. I highly doubt Boni would be willing to make obsidian melt into only 36 mb.

**Comment by ghost** [comment]
I would call this mechanics of the mod there are plenty of different mods that give more back to what you would using another mod.  Tinkers is known to be less efficient in its return for a lot of liquids.

**Comment by pauljoda** [comment]
Tinkers has changed then. When we first implemented we copied their recipe. With them changing, we are out of date. Enjoy the fun while it lasts

**Comment by pauljoda** [comment]
We have updated to the new tinkers recipes
