### ISSUE TITLE
Crash to desktop when moving/flying

### ISSUE THREAD

**Issue by Renadarain** [TeamBR-Modding/NeoTech#354]
What Version of NeoTech are you using:
Neotech: NeoTech-1.9.4-3.1.0
Minecraft: 1.9.4
Forge: forge-1.9.4-12.17.0.1968

If possible, did you break and replace the block:
Seems to happen with movement, either running or flying

Please Pastebin.com the crash Report and put link here:
http://pastebin.com/jgsQ7EEn

Regards,
Renada

**Comment by pauljoda** [comment]
Issue with forge, we are passing the given parameters and that is causing crash. I would expect this to be fixed soon
