### ISSUE TITLE
control upgrade recipe change

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#355]
What Version of NeoTech are you using:1.9-3.0.6
If possible, did you break and replace the block:N/A

Please Pastebin.com the crash Report and put link here:N/A

Could you please make the control upgrade for the machines a shaped recipe? As a shapeless, it interferes with the redstone torch recipe. I can't craft multiple RS torches at once because it defaults back to the control upgrade after every craft.

I'm loving the rest of this mod, Thanks for all your hard work!

**Comment by pauljoda** [comment]
This has been changed
