### ISSUE TITLE
Crash on editing pipe whitelist

### ISSUE THREAD

**Issue by Nonsanity** [TeamBR-Modding/NeoTech#356]
What Version of NeoTech are you using: 1.9.4-3.1.0

If possible, did you break and replace the block: no, crashed putting a sapling in a pipe's filter

Please Pastebin.com the crash Report and put link here:
https://paste.ee/p/Vj4JE

**Comment by Nonsanity** [comment]
The crash is repeatable. The item being placed in the whitelist filter was an oak sapling.

**Comment by Nonsanity** [comment]
It seems like the pipes will also lose their visual state (having the extract mode bulge) and the items in the whitelist will become invisible if the pipe gets an update even (like from a tree growing next to it). This is probably related to the general mod-wide erver sync issues I'm seeing: putting items into some machines causes the items to visually disppear, though they are there; breaking some blocks (like the RF storage blocks) results in a second, phantom drop to generate which only goes away if you reload that chunk.

In fact, sync issues could be causing most of these problems—though this crash may have a bug of its own compounding things. Do you test much on servers? The FTOG patreon server where I encountered this issue already has at least one other mod author testing in situ there. I'm sure you could be invited, if it would help. We have a large number of mature (okay, older) players that can help test as well.

**Comment by pauljoda** [comment]
Pipes are gone
