### ISSUE TITLE
Random Crash using a Duel Crafter

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#357]
What Version of NeoTech are you using: 3.1.0 (1.9.4)
If possible, did you break and replace the block: yes, put Birch wood and Oak wood planks inside a Duel Crafter
Please Pastebin.com the crash Report and put link here: http://pastebin.com/bhPG4Bbg
On Forge Version 12.17.0.1980 (1.9.4)

**Comment by pauljoda** [comment]
Some mod must have been messing with recipes, unable to replicate. Needs more info please post the crash log again

**Comment by DatrixTHLK** [comment]
I'm unsure if I will get the same error again since forge has updated a lot since then and I play on 1.10.2 now. Closing the issue was a good idea.
