### ISSUE TITLE
Crash Right Clicking a Furnace Generator

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#358]
What Version of NeoTech are you using: 3.1.0 (1.9.4)

If possible, did you break and replace the block: Whether I did or didn't makes no difference breaking the block and replacing it only delays the inevitable crash. The only way I found to bypass this was to put hoppers above the machines and put them in through the chests above the hoppers except buckets of lava. Still looking into the machine itself is causing a crash which never happened in 1.8 of minecraft.

Please Pastebin.com the crash Report and put link here: http://pastebin.com/UKe0bZpd
Forge Version: 12.17.0.1987 (1.9.4)

**Comment by RoboCyclone** [comment]
Same problem;
Version: 3.1.0
Break & replace: yes, tried in different positions in world
Crash report: http://pastebin.com/J4sKhzQJ
Forge version: 12.17.0.1987

**Comment by OPlurker1005** [comment]
I am having the same problem
 Version: 3.1.0
 break and replace the block: no 
crash report: http://pastebin.com/a0VEBrGq
Forge version: 12.17.0.1987

**Comment by MoonCutter2B** [comment]
Same problem same version
I crafted, placed and used it in same game session, i.e. no reload of game/world. yesterday
Crash happend today, i.e. started MC an loaded world.
Break and replace worked

**Comment by cheshirenoir** [comment]
same version of NeoTech and Forge. Also affects Electric Crucible and electric Alloyer
[crash-2016-07-14_18.50.50-client.txt](https://github.com/TeamBR-Modding/NeoTech/files/363525/crash-2016-07-14_18.50.50-client.txt)

**Comment by ghost** [comment]
same thing occurs also to me with fluid generators unsure how this was missed in testing.

**Comment by pauljoda** [comment]
The port was a non official port to 1.9.4. The last version I've had a hand in was the initial port to 1.9 (which was buggy as is). I plan to give some more work to the mod soon. Hang in there, real life is kinda hectic at the moment

**Comment by pauljoda** [comment]
Issue was regarding the new NBT saving from forge, fixed in next release
