### ISSUE TITLE
[Suggestion] Standalone Pipes

### ISSUE THREAD

**Issue by ToadsworthLP** [TeamBR-Modding/NeoTech#359]
I've been playing on 1.9.4 for a while now, and I noticed that there's a lack of nice item/fluid transport methods. Well, there's NeoTech, EnderIO, etc., you may answer now. But what if I say you that every single pipe mod on 1.9.4 (except Hopperducts, but let's forget that thing for a moment) comes with a HUGE set of technical gadgets that just don't fit into vanilla? Don't get me wrong-- I really like big tech mods, but it would be still nice to have a standalone piping system on 1.9.4. I especially like NeoTech's, even though I don't like the "new" opaque pipes which doesn't show what's going through them. I know it was done for performance reasons, but that could also be achieved by just adding opaque AND transparent pipes, kinda like Thermal Dynamics did. This would even fit into the mod, since it's a kind-of-remake of TE for modern MC versions. So if you split NeoTech's main stuff and the pipes into two seperate mods, you would also satisfy players who would like to play NeoTech without the pipes (I know some 1.8.9 people that say they "I don't want the pipes as they are just increasing load times and stuff like this"). I know that this would be much work, and that this is a big suggestion. I hope you respond to this anyways, and eventually do it! Yours sincerely,
ToadsworthLP

**Comment by pauljoda** [comment]
This is probably where the pipes will end up, for now they are history
