### ISSUE TITLE
[bug] - Item Dupe

### ISSUE THREAD

**Issue by TOLoneWolf** [TeamBR-Modding/NeoTech#360]
What Version of NeoTech are you using:
NeoTech-1.9.4-3.1.0

If possible, did you break and replace the block:
yep

Please Pastebin.com the crash Report and put link here:
not a crash so no log.

forge-12.17.0.1987

Tanks dupe using wrench shift right click dropping another 2 tanks and leaving the original in world.

The original is reset to an empty tank and left in world as a block.
One of the tanks that it drops is empty.
The other dropped tank contains the fluid from the original.

**Comment by pauljoda** [comment]
Issue resolved
