### ISSUE TITLE
Motherboard Dupe Glitch

### ISSUE THREAD

**Issue by TigersFangs** [TeamBR-Modding/NeoTech#363]
What Version of NeoTech are you using: 1.9.4-3.1.0 on MC 1.10.2

If possible, did you break and replace the block: Yes

Please Pastebin.com the crash Report and put link here: N/A

No crash error. This occurs when you place any filled motherboard into any machine's motherboard upgrade slot. It works as intended for the machine upgrade, it functions as expected with sneak left/right click, but there is a major dupe glitch if you use your "Pick Block" key on the motherboard to remove it from the motherboard upgrade tab. You can acquire an infinite number of motherboards, anything from a single upgrade to max upgrades. This is easily repeatable.

**Comment by pauljoda** [comment]
Are you in creative when doing this? That happens in creative but not survival
