### ISSUE TITLE
Crash trying to create whitelist in item pipe interface

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#364]
What Version of NeoTech are you using: 1.9.4-3.1.0

If possible, did you break and replace the block: yes, same result

Please Pastebin.com the crash Report and put link here:

http://pastebin.com/weKt0bFd copper ore crash

http://pastebin.com/weKt0bFd copper ore crash

Any ideas?

**Comment by pauljoda** [comment]
Pipes have been removed
