### ISSUE TITLE
Batteries need to register subtype information for JEI

### ISSUE THREAD

**Issue by mezz** [TeamBR-Modding/NeoTech#365]
Hello, 

JEI is unable to understand the NBT on NeoTech batteries when used for crafting. Please register this information in your JEI integration with JEI's `ISubtypeRegistry`.

Here's an example of Botania implementing it:
https://github.com/williewillus/Botania/commit/32a28e83a5263a0709e9954685544b6ea4cdf707

Original issue: https://github.com/mezz/JustEnoughItems/issues/265

**Comment by pauljoda** [comment]
Totally on the list. Just forgot to get it setup. @Dyonovan

**Comment by pauljoda** [comment]
These have been removed
