### ISSUE TITLE
Thermal Binder not accepting tin

### ISSUE THREAD

**Issue by ShadowDrakken** [TeamBR-Modding/NeoTech#366]
What Version of NeoTech are you using: 3.1.0

Please Pastebin.com the crash Report and put link here: N/A

There's no way to get Molten Tin into the Thermal Binder... it can't be piped in with any mods including its own pipes until you make a motherboard and give it input/output, and it doesn't accept buckets of Molten Tin (TCon). This effectively means there's no way to build motherboards whatsoever.

**Comment by pauljoda** [comment]
Has since been resolved
