### ISSUE TITLE
[Suggestion] Crop Farm

### ISSUE THREAD

**Issue by Greg9711** [TeamBR-Modding/NeoTech#367]
The idea is that you could add a crop farm that works almost like your tree farm but with crops.
I would love to see someting like that and Btw thanks for updating it to 1.10 :)

**Comment by pauljoda** [comment]
It is on the list

**Comment by Greg9711** [comment]
Thanks :D

**Comment by pauljoda** [comment]
Quick update on this, it is actually going to come soon. I promise, as soon as I have set up our tier system we will be adding machines that have been on the list for ages and this was one of the first

**Comment by Greg9711** [comment]
Nice to hear, thanks for the update.

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
