### ISSUE TITLE
[Bug] Range in the tree farm is wrong

### ISSUE THREAD

**Issue by Greg9711** [TeamBR-Modding/NeoTech#368]
I´m using the first version of neotech for 1.10.2.
The range of the tree farm in the info box in the Gui shows a 13x13 range with 8 hard drives in the motherboard. The real range of the tree farm is 23x23.
And another thing is that in the info box of the tree farm is says that each hard drive gives another 4 more range but with all 8 its only a 23x23 which seems wrong so is that a bug?

**Comment by Greg9711** [comment]
![2016-08-17_23 50 17](https://cloud.githubusercontent.com/assets/20912744/17754559/67052038-64d5-11e6-827e-5d24ff1b0725.png)

^^^^^^^^^^
Look at the range

**Comment by pauljoda** [comment]
I was adding instead of multiplying by hard drive count. Sorry about that. Fixed in last commit
