### ISSUE TITLE
[Bug] Stack problem in the Electric Furnace

### ISSUE THREAD

**Issue by Greg9711** [TeamBR-Modding/NeoTech#369]
What Version of NeoTech are you using: NeoTech-1.10.2-3.2.0

![2016-08-17_23 45 13](https://cloud.githubusercontent.com/assets/20912744/17754488/1172447a-64d5-11e6-98d2-100a2fbaf451.png)

^^^^^^^^^^^^^^^^^
This picture should explain it all

**Comment by pauljoda** [comment]
Has been fix
