### ISSUE TITLE
[Suggestion] New Model(s) idea

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/NeoTech#371]
Instead of re-texturing the solid cubes with just new textures, why not go with a dynamic theme of rendering something from an input/output of the machine itself? So for example a generic solid cube model with an [inset box in the middle of the front](http://i.imgur.com/nlvzc.png)  side that renders say for example in the Chopper, the Axe it's currently using, or the Crusher renders the ore it's currently processing. 

Updated: [Like this?](http://imgur.com/zBbrUIa)

Maybe even add a simple RED[off]/GREEN[on] light indicator to show it's currently working or receiving power.

**Comment by pauljoda** [comment]
Closing this for now, going to pair with a asset creator for new design
