### ISSUE TITLE
[Suggestion] RF Shield

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/NeoTech#374]
Shield that absorbs damage using RF power. Have different tiers, perhaps have augmentative properties in higher tier versions as upgrades/modules, such as counter-offense abilities like deal x% of damage back to attacker. 

Other ideas:
- "Shocking" shocks attacker. 
- "Repulse" pushes the attacker back. 
- "Discharge" rapidly discharges electricity as an AOE attack.
- "Fortify" casts a force-field protecting the player from all damaging sources
- "Magnetic" if the player has [magnetic armor](https://github.com/TeamBR-Modding/NeoTech/issues/373), the shield can be thrown like a boomer-rang and have it return just like Captain America's shield.

**Comment by pauljoda** [comment]
I would actually love to add this. I'll have to look into it but should be pretty easy

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
