### ISSUE TITLE
[Suggestion] Beryl dust/Beryllium Alloy

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/NeoTech#375]
[Beryl](https://en.wikipedia.org/wiki/Beryllium) dust is a byproduct from grinding Emeralds (20% chance drop rate) and can be used as an alloying agent with Iron and copper to make Beryllium, which is harder than steel, but also thermally more stable than any other metal alloy. An idea candidate for a high-power conductive alloy in end-game RF generation/storage.

Beryllium tool harvest level would be higher than Obsidian, which makes it better than Diamond, but also a gateway tier to harvest another end-game ore. Armor made out of Beryllium could be the entry level into RF empowered armor provided by Neotech since Beryllium requires potentially ~120 Emeralds to make.

**Comment by pauljoda** [comment]
Not on current plan
