### ISSUE TITLE
[Suggestion] Subsonic Repulsor

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/NeoTech#376]
Subsonic Repulsors create an ultra sonic harmonic field that "confuse" hostile mobs into not targeting players. Perhaps make mobs attack other mobs. Repulsors are mid-game progression because they require a fairly high amount of RF to operate (500-1000rf/t), thus making simple coal generators insufficient to power them. Material cost to craft them is trivial, but interesting materials (such as [magnets](https://github.com/TeamBR-Modding/NeoTech/issues/373)) could be required to encourage use of other machines and/or mechanics.

Subsonic Repulsors with Subsonic Amplifiers (range boosters) can be used as wireless RF charging stations with Energy Transducers (upgrade? separate block?). They simply wirelessly charge RF accepting items, they're not a wireless energy network.

I'd imagine they slightly hum when standing next to them. Perhaps crackle a bit, maybe just use the vanilla fire burning sound? Paul, you could engineer the perfect sound.

**Comment by pauljoda** [comment]
For now, going on the backburner as EIO adds something like this
