### ISSUE TITLE
[Suggestion] In-game Guide/wiki

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/NeoTech#377]
JEI/NEI covers how to make things, but a guide/wiki introducing the blocks to players would be nice. [Enchiridion](https://mods.curse.com/mc-mods/minecraft/enchiridion) looks nice.. I know theres Guide-API and probably a ton of other in-game guide apis that are readily available.

A simple index, maybe by category (Ore processing, Power generation, Storage, Tools, Armor, Alloys, etc) which lists the blocks and includes a basic description, requirements, and possible upgrades/augments.

For example:
- **Chopper:** Automated tree chopper that consumes RF. Requires an Axe, can be equipped with shears to collect leaves. Accepts upgrade modules ["...", "....", "...."]
- **Miner:** Automated mining that consumes RF. Requires a Pickaxe to operate. Accepts upgrade modules ["...","...","..."]
- **Grinder:** Early game ore doubling. Finely grinds resources using momentum power. Requires a pressure plate placed on top of it, and the player fall distance determines how much momentum power is transferred into the grinder. The higher the jump, the more momentum the grinder has to process more resources. Using better pressure plates yields higher momentum transfer! ["Copper", "Gold","Iron","Diamond"] pressure plates accepted.

Nothing too elaborate, just an introduction to the items in the mod. Then again, you could just document it on the wiki here, too. But books are nice in-game! No alt-tabbing!

**Comment by ChilledDayz** [comment]
Have to agree I think most mods should have in documentation, even if it's just holding shift over an item. It's one of my problems with most mods I hate having to leave the game to find out how things work.

**Comment by pauljoda** [comment]
The machines have tabs the define their usage. Other info will be added to shift over item as needed
