### ISSUE TITLE
Crash when setting fluid interface pipe to extract from electric alloyer

### ISSUE THREAD

**Issue by phantomholo** [TeamBR-Modding/NeoTech#378]
What Version of NeoTech are you using:NeoTech-1.10.2-3.2.0

Please Pastebin.com the crash Report and put link here: http://pastebin.com/tsr1v7kB

**Comment by phantomholo** [comment]
now it crashes when i load the world

**Comment by jburrows82** [comment]
Confirmed with latest builds off Jenkins. 

[Crashlog](http://pastebin.com/nEppeG0w) and the [screenshot](https://snag.gy/5uGdHz.jpg)

#BlamePaul

**Comment by pauljoda** [comment]
Fix via 8e447f050f1e01c30d7c32de9d68429b17a4d965
