### ISSUE TITLE
BUG: Creative Fluid Tank not updating to piped in fluids

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/NeoTech#380]
Latest Jenkins build, of course. [picture](https://snag.gy/ldbq6A.jpg)

When extracting from one creative tank to another, the empty tank doesn't update until you try to insert another fluid. I thought it was a block update issue at first, but placing a block next to it or empty hand clicking the empty tank still shows the empty tooltip. I noticed it when trying to insert lava in the empty tank and it actually rendered lava for a split second, then updated to Molten Tin.

**Comment by pauljoda** [comment]
I never really intended them to be filled that way, but I can fix that
