### ISSUE TITLE
Neotech logger doesn't work with fertilized dirt from Random Things

### ISSUE THREAD

**Issue by phantomholo** [TeamBR-Modding/NeoTech#384]
What Version of NeoTech are you using: 1.10.2-3.2.0

Please Pastebin.com the crash Report and put link here: no crash report

when I try to replace the dirt blocks with fertilized dirt blocks from the Random Things mod, the electric logger from Neotech doesn't detect it as a dirt block and does not plant any saplings on them. If I try placing the saplings on the fertilized dirt blocks, after the tree grows, the logger would just break the tree as usual and instead of planting another sapling in place of it, the logger replaces the fertilized dirt block with a regular dirt block.

**Comment by pauljoda** [comment]
I'm afraid that is intended. We don't want the logger to be changed by other mods, in order to keep balance around the upgrades this is the options we have chosen.
