### ISSUE TITLE
Were pipes removed?

### ISSUE THREAD

**Issue by Renadarain** [TeamBR-Modding/NeoTech#385]
What Version of NeoTech are you using:
NeoTech-1.10.2-3.3.0.jar

Updating to this version it appears that all the pipes have been removed.  Is that intentional?

Regards,
Renada

**Comment by jburrows82** [comment]
The pipes were removed in this release in favor of a new concept that has yet to be implemented. Until then, pipes/conduits from another mod will have to be used. However, most of the machines allow sided IO configurations so you can I/O between machines directly.

**Comment by Renadarain** [comment]
Ahh ok thanks :)
