### ISSUE TITLE
[suggestion] Documentation for new upgrade system

### ISSUE THREAD

**Issue by phantomholo** [TeamBR-Modding/NeoTech#387]
What Version of NeoTech are you using: 1.10.2-3.3.0

I see that the new update removed the pipes and motherboard from neotech and also some upgrades.I also noticed that my inventory had many 1TB Hard Drives. I would like to know how the new system works and it would help if you could update the wiki and the changelog for the updates so that we can know what was changed in the latest update! Thanks in advance!

**Comment by pauljoda** [comment]
Once I finish it to where I feel it is ready I intended to do so

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
