### ISSUE TITLE
Client crash when placing a Star Light onto tall grass

### ISSUE THREAD

**Issue by Ommina** [TeamBR-Modding/NeoTech#388]
What Version of NeoTech are you using: NeoTech-1.10.2-3.3.0

Please Pastebin.com the crash Report and put link here: http://pastebin.com/xNNDEQMv

When placing a Star Light (any colour) onto tall grass, instead of overwriting the grass and placing it onto the block below, the client crashes.

If the tall grass is destroyed first, and the light placed directly onto the ground, all is fine.

**Comment by pauljoda** [comment]
Block has been removed
