### ISSUE TITLE
Cant solidfy molten obisidan.

### ISSUE THREAD

**Issue by PhoenixSmith** [TeamBR-Modding/NeoTech#389]
What Version of NeoTech are you using:1.10.2 3.3.0

I can not seem to solidify molten obsidian after the update. The task looks to be working but does not create/output obsidian.

**Comment by pauljoda** [comment]
Try deleting the solidifier recipe config and letting it regen

**Comment by OcAMD** [comment]
This is an issue with the 1.8.9 2.4.4 version as well. I tried to delete the entire Neotech config and let it regen but no luck.

**Comment by pauljoda** [comment]
This was a total oversight on my end. We had initially set the modes for metal blocks etc, not taking into account what mode it should be in. In my rework, this is being fixed

**Comment by pauljoda** [comment]
Fixed with new recipe handler
