### ISSUE TITLE
[1.10.2] Crash with Solidifier

### ISSUE THREAD

**Issue by PhoenixSmith** [TeamBR-Modding/NeoTech#390]
What Version of NeoTech are you using: 1.10.2-3.3.0

Please Pastebin.com the crash Report and put link here: http://pastebin.com/iYzy9gza

**Comment by pauljoda** [comment]
Delete the config for the solidifier and try again. Let me know if that fixes it

**Comment by pauljoda** [comment]
Fixed in new version
