### ISSUE TITLE
[1.10.2] Crashes while Shift-Clicking into the grinder

### ISSUE THREAD

**Issue by MCOfficer** [TeamBR-Modding/NeoTech#391]
What Version of NeoTech are you using: 1.10.2-3.3.0

Please Pastebin.com the crash Report and put link here: http://pastebin.com/X5GEjz5j

Happens when trying to shift-click a FunOres Ore (such as tin) from my inventory into the grinder. Moving the ore with the mouse (drag'n'drop) works just fine.
edit: standart minecraft ores work as well, seems to be FunOres related.

**Comment by pauljoda** [comment]
Try deleting the config registry and letting it refresh. The ores added may have messed up the registry but it should sort itself out

**Comment by MCOfficer** [comment]
works, thank you. i'm gonna leave out funores anyways, since i discovered neotech is capable of spawning ores as well :)
