### ISSUE TITLE
Fluid Tank Issues

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#393]
What Version of NeoTech are you using: 1.10.2-3.3.0

Please Pastebin.com the crash Report and put link here: no crash

Having problems with fluid tanks not retaining their contents. Crafted an Elite fluid tank, filled with about 45 buckets of Lava, broke the tank and placed on other side of Lava pool and it was empty again. Any ideas why this might be happening?

Thanks for all your hard work!

**Comment by garath77** [comment]
Same thing happening with RF Storage Blocks. Nothing is retained after breaking and replacing.

**Comment by Dyonovan** [comment]
For things to keep their contents, ie RF Storage or tanks, you need to use the wrench.

**Comment by garath77** [comment]
Why didn't I think of that? LOL Thanks
