### ISSUE TITLE
Crash when putting ore into Neotech crusher

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#394]
What Version of NeoTech are you using: 3.3.0

Please Pastebin.com the crash Report and put link here: https://gist.github.com/DatrixTHLK/237ee90b3f36c3ec74e5c0ad8eeae8d7

**Comment by pauljoda** [comment]
Delete the config dir and let it regen

**Comment by DatrixTHLK** [comment]
Done. Thanks again.
