### ISSUE TITLE
Basic Solar Panel recipe

### ISSUE THREAD

**Issue by AngelCry** [TeamBR-Modding/NeoTech#395]
What Version of NeoTech are you using:
3.3.0
Please Pastebin.com the crash Report and put link here:
...
hi. are you aware about not working recipe for Basic Solar Panel? looks like something wrong with Basic RF Battery. recipe shown in JEI but cant be made (panel just not appear when you fill all ingridients). im sure is about battery because i able 'fix' it (for personal use) using CraftTweaker by replacing neotech:basicRFBattery with ore:rfBattery. sorry if something wrong on my end (i hope is not)

**Comment by carstorm** [comment]
Are you charging the battery first, the battery must be fully charged to use it in the crafting recipe?

**Comment by AngelCry** [comment]
um... no. is first time i hear when recipe use charged battery. i come from times, where charging usually make batteries unusable (and, in some mods, even discharging wont help). this is explained somewhere or you just find out is by self (by trial and error)?

**Comment by Morpheus1101** [comment]
The Recipe is wrong in JEI as it shows an Uncharged battery, not a battery full.  I might also now query if the battery is meant to be full to go from the basic to the advanced battery or if using an uncharged battery which works is intended or a bug?

**Comment by pauljoda** [comment]
The recipe will be updated

**Comment by pauljoda** [comment]
Batteries have been removed, this is no longer applicable
