### ISSUE TITLE
Logger Misbehaving

### ISSUE THREAD

**Issue by Kename** [TeamBR-Modding/NeoTech#397]
What Version of NeoTech are you using: 3.3.0

NeoTech logger misbehaving - Saplings just disappear and then new ones are replanted.

Plants saplings - Check
Trees grow - Check
Trees instantly disappear - Check
Wood harvested - No :(
More saplings planted - Check

**Comment by pauljoda** [comment]
What is the tree it is cutting?

**Comment by Kename** [comment]
Plain oak saplings. Switched to birch and everything seems to work normally.

**Comment by DatrixTHLK** [comment]
Does the logger harvest modded trees logs? The logger doesn't seem to be able to do that at the moment (at least not for terraqueous). Maybe I've missed something...

**Comment by pauljoda** [comment]
From testing with the new version, this no longer seems to be an issue. As we get close to release, I will try with modded trees. Though, if they implemented their blocks correctly, it should work

**Comment by DatrixTHLK** [comment]
Thanks for the response.
