### ISSUE TITLE
Crash while putting a modded ore into crusher

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#398]
What Version of NeoTech are you using: 3.3.0
Forge: 2114
Minecraft 1.10.2

Please Pastebin.com the crash Report and put link here: https://gist.github.com/DatrixTHLK/293b7f1f503bb4a9f13a390b5945f5c7

**Edit:** Now I'm just CTDing when trying to open my world: https://gist.github.com/DatrixTHLK/37b5ec214fd059c2c3f6cae8acfaae2f

**Comment by Dyonovan** [comment]
Delete the neotech config directory. It will be recreated when you run minecraft again.

**Comment by DatrixTHLK** [comment]
Will do.

**Comment by Dyonovan** [comment]
I am guessing you removed or added a new mod? When ever you do that, you need to re-create the machine recipes by deleting the config files.

If not, once in a while they can become corrupted

**Comment by DatrixTHLK** [comment]
Yes, I updated a few mods. I will remember what to do the next time when updating mods then. Thanks for the information.

One question though: Is this only for your mod?
