### ISSUE TITLE
Exception loading model?

### ISSUE THREAD

**Issue by DatrixTHLK** [TeamBR-Modding/NeoTech#399]
Hello,

What Version of NeoTech are you using: 3.3.0
Minecraft 1.10.2
Forge: 12.18.2.2022

Please Pastebin.com the crash Report and put link here: https://gist.github.com/DatrixTHLK/732365a23e0815aff4bcad49bf280955

I seem to be getting this error in the FML log about Voidgalss for one: Lines: 1718-1769, 1817-1868. There may be more lines of this but I'm still looking

**Comment by Dyonovan** [comment]
That can be ignored.
