### ISSUE TITLE
textures not loading 

### ISSUE THREAD

**Issue by mutantroosta** [TeamBR-Modding/NeoTech#40]
the textures for the electric crusher and furnace are showing as the black and purple cubes, im also getting major frame rate issues if im standing closer than 10 blocks from the items in question, the frame rate can drop down to 6fps if its running while im within the 10 block radius of it, im not sure if thats a mod issue or a gfx card issue (1gig  geforce 210 low profile fanless, set at 800x600
![2015-12-15_12 37 07](https://cloud.githubusercontent.com/assets/16458443/12014083/02500e1c-ad8a-11e5-8883-0a3f966bfdb3.png)
![2015-12-15_12 37 26](https://cloud.githubusercontent.com/assets/16458443/12014084/0254614c-ad8a-11e5-9a09-a98fa2360b25.png)

**Comment by genthug** [comment]
If you're still having the issues, I would go re-download the latest stable version available (I'm not having the same issue, and I have each of those blocks in my world). I would also spend the $75-100 and upgrade your graphics card. Going with an AMD Radeon card you'll get a more recent chip than a GTX card. If you're interested in the upgrade go take a look at any in the R7 200 series of their cards.

**Comment by mutantroosta** [comment]
i updated forge and NEI and it loaded the textures, but the lag was still there, for now i just remove the items when not in use (the redstone battery also, i forget if thats your mod or power advantage)
