### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by Greg9711** [TeamBR-Modding/NeoTech#400]
Are you still working on the mod? If no why not? If yes are there any updates coming sometime anytime soon?
P.S. really like the mod and would love to see it grow more.

**Comment by pauljoda** [comment]
I'm not working on it at the moment. I've been very busy with my real life and work. This time of year is very busy so we will see if I can get back into it. Anyone is free to continue it during that time but for the next few months don't expect too much sadly.

Glad you like the mod, I'll get back to it at some point I'm sure I just need the time to do so.

**Comment by Greg9711** [comment]
Thanks for the feedback :).
