### ISSUE TITLE
Server crashed, [Server thread/ERROR] [FML/]: Caught exception from NeoTech (neotech)

### ISSUE THREAD

**Issue by Fireztonez** [TeamBR-Modding/NeoTech#401]
I have a problem when I install NeoTech on my server, It always crashes before the end of the bootup, which makes the server unusable ...

What Version of NeoTech are you using:
NeoTech-1.10.2-3.3.0-dev

Crash Report and put link here:
https://gist.github.com/Fireztonez/0d7a27c18a5ec65ac3cbbd05d8251b40

**Comment by pauljoda** [comment]
Block removed
