### ISSUE TITLE
Fluid Generator Config?

### ISSUE THREAD

**Issue by davqvist** [TeamBR-Modding/NeoTech#402]
What Version of NeoTech are you using:
1.10.2 3.3.0

I changed the config for the Fluid Generator, see pastebin: 
http://pastebin.com/9ygLDLUW

But when I try to put any bucket of those fluids in the Fluid Generator, it doesn't work.
Also I tried to put in lava (I removed Lava in the JSON), it goes in but gives no power, so it seemed to have some effect. I thought my JSON is wrong but it seems fine.  In fml-client-latest.log it says also:
[01:45:26] [Client thread/INFO] [bookshelfapi/neotech]: Loading fluidFuelValues Recipes...
[01:45:26] [Client thread/INFO] [bookshelfapi/neotech]: fluidFuelValues Recipes loaded successfully

In fluidFuelValuesRecipes.cfg I changed nothing, Do I have to change something for it? It says:

recipeconfig {
    B:autoupdate=true
    I:version=3
}

I hope someone can help me.

**Comment by pauljoda** [comment]
Delete both configs for the fluid generator and try again

**Comment by davqvist** [comment]
Sorry I must have missed your comment. I just created a new instance with only Neotech and Actually Additions and deleted lava and added the Actually Additions Oils and again it consumes lava without giving power but doesn't accept the Actually Additions Oils.

**Comment by pauljoda** [comment]
Will investigate

**Comment by pauljoda** [comment]
This has been fixed in the rewrite and improved upon
