### ISSUE TITLE
Client Crash on startup

### ISSUE THREAD

**Issue by Fizbe** [TeamBR-Modding/NeoTech#404]
What Version of NeoTech are you using:
Neotech 3.3.0
Please Pastebin.com the crash Report and put link here:
http://pastebin.com/xBCyBPis
(https://openeye.openmods.info/crashes/6cc9617629696506babab29fe6e57359)

**Comment by pauljoda** [comment]
You don't happen to have two instances of Neotech installed do you?

**Comment by Fizbe** [comment]
No I do not

**Comment by pauljoda** [comment]
Honestly I'm not sure. There must be some other mod using that ID. We probably could have named the id more unique so I accept blame for the issue but on the same note someone else made the same lazy mistake we did. Try removing mods that contain chunk loaders and see if you are able to load without one of those

**Comment by Fizbe** [comment]
I believe I found the issue, the conflict is with a mod called "Chunkloader" and it is made by mark232
