### ISSUE TITLE
Middle-click "pick block" loses colour of star light

### ISSUE THREAD

**Issue by xenoflot** [TeamBR-Modding/NeoTech#405]
What Version of NeoTech are you using:

1.10.2-3.0.0

No crash, just middle-click in creative on a star light and it returns a white one, regardless of what you're middle-clicking on.

**Comment by pauljoda** [comment]
Yeah it worked at one point. Then the block states change messed up everything. If I get back into work on this mod I'll be sure to look into that.

**Comment by pauljoda** [comment]
Block has been removed
