### ISSUE TITLE
Neotech upgrades and tool textures mixed up

### ISSUE THREAD

**Issue by TehFoxFire** [TeamBR-Modding/NeoTech#406]
What Version of NeoTech are you using: 1.10.2-3.3.0

![image](https://cloud.githubusercontent.com/assets/20863498/21510269/058cd956-cc57-11e6-9b2f-1b73d7cfa9c1.png)

As you can see the upgrades look like shards of something. I don't have any crash or errors to give because it doesnt seem to be giving any. Also, when you hold any of the items with the textures that are messed up you start lagging really bad and this bug persists with the electric armor too even tho the textures are fine. I hope you can get this fixed! 
~Fox

**Comment by pauljoda** [comment]
Are you using a very of optifine?

**Comment by TehFoxFire** [comment]
No, we are not using optifine.

**Comment by pauljoda** [comment]
These have been removed
