### ISSUE TITLE
Crash when placing a Thermal Binder

### ISSUE THREAD

**Issue by llloyd4** [TeamBR-Modding/NeoTech#407]
What Version of NeoTech are you using: NeoTech-1.10.2-3.2.0.jar

Please Pastebin.com the crash Report and put link here:

http://pastebin.com/MGCLhFbJ

**Comment by pauljoda** [comment]
Make sure you are using the correct version of our Bookshelf API along with this mod. If not, please list if you have IC2, RF API, Tesla, and their version number. There may be some incompatibility in there somewhere

**Comment by llloyd4** [comment]
Given I downloaded it at the same time I *think* it's right. Let me see...

Bookshelf-API-1.10.2-3.3.0.jar
Industrialcraft-2-2.6.105-ex110.jar

Not sure on the RF API thingy, I have Ender IO 1.10.2-3.0.1.138_beta which is the primary tech mod.

**Comment by pauljoda** [comment]
Thermal Binder Removed

**Comment by llloyd4** [comment]
Ok, when I get home I'll update everything and see how the new system works. :D

**Comment by pauljoda** [comment]
It isn't quite ready. Just cleaning issues as I prepare one. Want to close existing issues before releasing. Check our build server for updates.   http://teambrmodding.com:8080/
