### ISSUE TITLE
Item Duplication Glitch

### ISSUE THREAD

**Issue by PirateToshio** [TeamBR-Modding/NeoTech#408]
What Version of NeoTech are you using:
Using 1.10.2-3.3.0

Using steve's factory manager, you are able to pull items out of the grinder, i figured that was a bug in and of itself but along with that, when SFM pulls an item out of an inventory, it WILL place the same item in almost every slot of the output chest
see gold grit in the first screenshot and Lead Grit in the second: 

![2017-01-03_04 45 08](https://cloud.githubusercontent.com/assets/7453525/21604143/7d42a5f8-d16f-11e6-8845-ba69a3198c6d.png)

![2017-01-03_04 48 28](https://cloud.githubusercontent.com/assets/7453525/21604216/f4212a6e-d16f-11e6-9af3-6f67b257b6c1.png)

This also has worked with diamonds, lapis, coal and redstone.

**Comment by pauljoda** [comment]
This is no longer in Neotech but in Assisted Progression. But I will look into it for that release
