### ISSUE TITLE
NEI

### ISSUE THREAD

**Issue by WenXin20** [TeamBR-Modding/NeoTech#41]
Can you make it so NEI is not required or that the Just Enough Items (JEI) Mod can be used instead of NEI, because I use JEI instead of NEI.

**Comment by Dyonovan** [comment]
Already planned. I was waiting for NEI to do a 1.8.8 updated but I just found out about JEI. Will try to add both but not required for either.

**Comment by WenXin20** [comment]
Ok, thanks :)

**Comment by Dyonovan** [comment]
Removed NEI code and added JEI. Will be available for next release which will also be for 1.8.9
