### ISSUE TITLE
Spawner Relocator Minor Issue

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#411]
What Version of NeoTech are you using: 3.3.0

Please Pastebin.com the crash Report and put link here: no crash

I attempted to rename (in a vanilla anvil) an empty Spawner Relocator to correspond with the type of spawner that I was about to use it on (because the tooltip info on what type is currently not working). 

The rename worked, but not quite as expected. It returned a 'full' Spawner Relocator, which I only realized when trying to pick up the one that I renamed it for. When placing the spawner it was holding, I found it was a pig spawner, like when you place a spawner in vanilla without any of the specific variables required.

Not a big deal, but strange.

I also found that after placing the spawner, the relocator reverted to its original name, which I assume is intended. But it would be nice to either have the type field in the tooltip fixed, or retain the rename...

Further testing showed that renaming a full relocator did not affect the spawner inside.

Thanks

**Comment by pauljoda** [comment]
This has been moved to Assisted Progression. If the issue persists in that mod please post there if you don't mind
