### ISSUE TITLE
Step Assist issue. Step Height being reset to old (pre 1.8) value?

### ISSUE THREAD

**Issue by garath77** [TeamBR-Modding/NeoTech#412]
What Version of NeoTech are you using:3.3.0

Please Pastebin.com the crash Report and put link here: no crash

working with chisels and bits, I ran across an issue with step height not working properly after changing any gear. I narrowed down the issue to leggings only, then, one at a time, removed the 4 mods that include leggings from my pack. The issue seems to be tied to yours. Someone suggested to me that maybe your step height value is still reseting to 0.5, which is the pre-1.8 value, when post value is 0.6(?). Could you take a look at this when you have a chance please? Thanks

**Comment by pauljoda** [comment]
Armor removed
