### ISSUE TITLE
Missing Chunkloader? New config folder?

### ISSUE THREAD

**Issue by BamaJoe411** [TeamBR-Modding/NeoTech#414]
What Version of NeoTech are you using: Neotech-1.10.2-4.0.0-B151

Please Pastebin.com the crash Report and put link here: no crash to report

I updated Neotech-1.10.2-3.3.0 to Neotech-1.10.2-4.0.0-B151 and a few blocks were removed including the chunk loader. I'm not sure if this is a bug or not because I don't see anything about removing the chunk loader in the change log. Also there is a new config folder. The old config folder was labeled  "NeoTech" and the new config folder is labeled "Neotech" (notice the capitalized "T").

**Comment by pauljoda** [comment]
Yeah sorry, I didn't think it would even let you update to the newest version. They weren't supposed to be compatible. The naming change is on purpose and those blocks have been removed as we focus our vision in a bit and moved things over to assisted progression
