### ISSUE TITLE
Missing Upgrades and Mekanism support issue

### ISSUE THREAD

**Issue by BamaJoe411** [TeamBR-Modding/NeoTech#415]
What Version of NeoTech are you using: Neotech-1.10.2-4.0.0-B151

Please Pastebin.com the crash Report and put link here:

I updated Neotech-1.10.2-3.3.0 to Neotech-1.10.2-4.0.0-B151 and All of the upgrades i has in all of my neotech machines are gone. Also Mekanism universal cables no longer connect to neotech machines.

**Comment by pauljoda** [comment]
Yes sorry, the old version has been completely rewritten. It will not be compatible with older versions as the entire data design has changed. As for the universal cables, which kind of cables? The just the energy ones?

**Comment by BamaJoe411** [comment]
Yeah we are using the cables from mekanism for power since NeoTech doesn't have any and Mekanism was our only mod we had that had really good power cables (trying to keep our modpack light) and now it doesn't work with neotech which was the mod I was using to generate most of my power at the time.

**Comment by pauljoda** [comment]
If mekanism isn't using the Forge Energy system then we won't have compatibility. Put an EIO capacitor or conduit in between them to convert

**Comment by BamaJoe411** [comment]
EIO? is that in NeoTech? or are you referring to another mod?

**Comment by pauljoda** [comment]
Ender IO
