### ISSUE TITLE
Electric Alloyer ignoring I/O Config

### ISSUE THREAD

**Issue by BamaJoe411** [TeamBR-Modding/NeoTech#416]
What Version of NeoTech are you using: Neotech-1.10.2-4.0.0-B151

Please Pastebin.com the crash Report and put link here: N/A

I have an Electric Alloyer set up with 2 Electric Crucibles (one on the top with Blaze rods and one on the Left with Iron Blocks).
I have a network card in the Electric Alloyer and set the Electric Alloyer I/O Config like [this](http://i.imgur.com/zXnaaz1.png) and the Electric Alloy is still accepting molten iron in both fill slots in the Electric Alloyer.

**Comment by pauljoda** [comment]
This was an issue I discovered and fixed in 1.11.2. I wish I had a fix for you, but with the amount of changes that have occured it would be difficult to go back and patch this. Closing for now, but may reopen if I plan on going back and supporting 1.10.2
