### ISSUE TITLE
Solidifier Requires Initial Seed Ingot

### ISSUE THREAD

**Issue by timbrown81** [TeamBR-Modding/NeoTech#417]
What Version of NeoTech are you using: 2.5

Please Pastebin.com the crash Report and put link here:

The solidifier wouln't start producing ingots (tormented) until I placed a tormented ingot in the output slot.   It shouldn't require anything in the output slot, especially items that can only be created via the solidifer.

**Comment by SDUBZ** [comment]
also having problems with the output of solidifier not producing any output

**Comment by TheLimePixel** [comment]
Actually the Solidifier overall doesn't output anything in 1.11.2
![2017-04-18_20 25 40](https://cloud.githubusercontent.com/assets/25333164/25146890/e0bfc85a-2475-11e7-961d-e63b3089c8ad.png)
