### ISSUE TITLE
crash when client was looking at gui of energy(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [TeamBR-Modding/NeoTech#422]
What Version of NeoTech are you using:
Neotech-1.11.2-5.0.0
forge:1.11.2-2282

Please Pastebin.com the crash Report and put link here:
[crash-2017-04-18_17.20.27-client.txt](https://github.com/TeamBR-Modding/NeoTech/files/930310/crash-2017-04-18_17.20.27-client.txt)

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
