### ISSUE TITLE
Positive Feedback Loop Between Actually Additions Batteries and NeoTech RF Batteries

### ISSUE THREAD

**Issue by Pinaz993** [TeamBR-Modding/NeoTech#423]
NeoTech Version: 1.10.2-3.3.0

If you have a NeoTech RF battery and an activated single/double/triple/quadruple/quintuple AA battery, and there's power in either of them, they will establish a positive feedback loop that will drain the NeoTech battery and charge the AA battery to capacity, along with any other items in your inventory that can accept power. Below is the issue on the AA GitHub.

https://github.com/Ellpeck/ActuallyAdditions/issues/749

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
