### ISSUE TITLE
Infinite Energy when adding a Single-Core Processor to the Furnace Generator

### ISSUE THREAD

**Issue by binarybagel** [TeamBR-Modding/NeoTech#425]
What Version of NeoTech are you using: Neotech-1.11.2-5.0.0

As the name of this issue says, as soon as I add the upgrade it gets infinite burn time for no apparent reason. I did not check what happens when I add a higher processor since I changed it's recipe in the pack I play and haven't reached the point where I can afford those yet.

Please Pastebin.com the crash Report and put link here: No crash.

PS: I can also provide a modlist if needed. But I doubt that this is mod-interaction.

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
