### ISSUE TITLE
crafting problem

### ISSUE THREAD

**Issue by Bardyon** [TeamBR-Modding/NeoTech#426]
What Version of NeoTech are you using:1.10.2-3.3.0

so the problem is when i was crafting a solar panel the basic one we can say i had all the stuff but when i used the rf battery like i placed the rf battery in my inventory and it got  the charge bar and when i used it it wouldnt craft the solar panel same with the tank so i think that needs a fix?

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
