### ISSUE TITLE
mod asking for version of bookshelf api that does not exist

### ISSUE THREAD

**Issue by mutantroosta** [TeamBR-Modding/NeoTech#427]
What Version of NeoTech are you using: 4.0.0-B151
no crash to report, forge halts and says neotech requires bookshelfapi version 5.0.0" while the bookshelf api is only up as far as 1.4.4.347
![screenshot 2017-07-14 15 31 24](https://user-images.githubusercontent.com/16458443/28197237-a071f82c-68a9-11e7-9d89-90e18b615dc2.png)

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
