### ISSUE TITLE
Centrifuge clipping

### ISSUE THREAD

**Issue by roswellguitar** [TeamBR-Modding/NeoTech#428]
What Version of NeoTech are you using: 3.3.0 (M 1.10.2)

I don't really know if this is an issue but worth asking. I'm playing AoE modpack and i'm having issue with the centrifuge. The crucible is filling the centrifuge full and the centrifuge keep stopping, starting, stopping, starting. It's like processing few millibuckets and then stop while it still have plenty of liquids to process in the buffer. Weirdly sometimes, after reloading the save it's processing correct, but when i'm changing the ore processing it's doing those stops again. 

Hope i've been clear and understundable. Thanks in adance for any tips and help. Really apreciate this mod so i'd love to help fix some troubles.

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
