### ISSUE TITLE
Centrifuge keeps getting stuck with 12mb of dirty molten ore

### ISSUE THREAD

**Issue by landrus** [TeamBR-Modding/NeoTech#429]
What Version of NeoTech are you using: 1.10.2-3.3.0
Playing Age of Engineering 1.0.5

I do have the ore tripling setup: Crucible - Centrifuge - Solidifier. I have a top tier processor and memory upgrade (one each) in every machine. And I pump out the molten ore from the centrifuge into the solidifier by the output mechanism and pump the lava out on a different side into a trash can (liquids).
After each ore (I process iron, gold, copper, tin, lead and silver on larger quantities) the centrifuge is stuck because 12mb of the dirty molten ore is still in the input. I have to break it and place it again.

This is somewhat annoying :)

**Comment by landrus** [comment]
I rechecked. I originally used ender io pressurized conduits to move the liquids around, and most probably these are the source of the problem.

When strictly using neotech mechanisms to move liquids around (putting the three machines next to each other and via network card push out the liquids) it works like a charm.

**Comment by Quest79** [comment]
Thank you @landrus for the tip. having this issue as well. Will try a directly connected approach.

**Comment by pauljoda** [comment]
You should be able to shift click the tank in the GUI to clear it if it gets stuck. It is in a build but not sure which one

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
