### ISSUE TITLE
Electric Alloyer liquids flowing into both chambers

### ISSUE THREAD

**Issue by cstalker** [TeamBR-Modding/NeoTech#431]
What Version of NeoTech are you using:  1.10.2 v 3.3.0

Please Pastebin.com the crash Report and put link here: no crash report

I have added a network card and configured the intake chambers as teal and violet. and the output as orange. When adding fluids (iron and coal) if one side empties out and there is excess of the other it will fill into the 2nd chamber. Shouldn't the configuring of sides keep the fluids in their respective colors.  I am using Ender IO ( 1.10.2 3.1.193) conduits to pipe the liquids in at this time. I tried having the machines next to each other and i thought that was the issue.

**Comment by taleteller** [comment]
Just stumbled upon exactly the same issue. Does not matter if machines are touching other Neotech machines or getting fed by pipes. Also there is no way of removing fluids from the mixing chambers. 

Looks like this happens when the internal Tanks overflow.

**Comment by Wdrussell1** [comment]
Exact same issue. Seems as though the color of the chambers doesnt matter. I will put a TINY amount of liquid in one of the chambers and then proceeds to fill the second. Almost as if the machine has to figure out what to do with the liquid every time it gets liquid. Which of course breaks it.

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
