### ISSUE TITLE
[1.10.2]JEI can't recognise Tanks with durability tag

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [TeamBR-Modding/NeoTech#432]
What Version of NeoTech are you using:
3.3.0

Problem:

[When Craft a tank via NEI](https://i.imgur.com/l63TgrA.png)
[Gives a tank with durability 0/16](https://i.imgur.com/QbyPe22.png)
[NEI then can't recognise the tank](https://i.imgur.com/TPSKLrs.png)
[Manually placing the items,however,works](https://i.imgur.com/WdoTHDx.png)

**Comment by Pythonic-Rainbow** [comment]
What was that? half year passed and no one cares

**Comment by Buuz135** [comment]
Entitled Alert! Modding is a hobby that doesn't need to be continued for ever.

**Comment by Pythonic-Rainbow** [comment]
yeah I know , sad but true :(

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite

**Comment by Pythonic-Rainbow** [comment]
Oh I forgot this issue already lmao anyways keep it up :D
