### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by Trixz2018** [TeamBR-Modding/NeoTech#433]
any chance of this getting updated to 1.12?

**Comment by pauljoda** [comment]
50/50

**Comment by pauljoda** [comment]
That being said, I still don’t know either way. If you can provide some feedback that might help. Mainly, with things like Thermal Expansion updated does Neotech bring its own enough to stand next to it? As of now, if I were to bring it back it would be to make new tech that is somewhat niche or random. I would like to hear your feedback or any others reading this on why it should be updated.

**Comment by Trixz2018** [comment]
To be honest i have been writing a paragraph about this is mod and what i think it should be and become but then i just scraped it because it just ended up turning into a mod that i use to love know as redpower. so you don't need update this mod. At this state there really isn't a place for it with all the tech mods that are out there like mekanism, thermal mods, ic2, tech reborn, ender io (still waiting for that), and immersive engineering. but if you would ever want to bring this mod back i would stick to the computerized theme and turn it into a complex computer system mod that did all kinds of things like sorting, storage, ore processing, different ore gen, etc,

**Comment by Hakameda** [comment]
I like this mod, and it'd be cool to see it worked on. It doesn't matter of its the same as any other mod. That's just bs tbh. Most mods copy each other, there is very little unique content when it comes to that but people will use mods they like. Though it'd be cool not to take the xycraft/DE route and just make it more OP to force people to use it

**Comment by ghost** [comment]
^

**Comment by pauljoda** [comment]
Neotech as it is is dead. As I’m learning 1.14.2 porting this mod as is wouldn’t be doable. I’m considering a complete renewal of this mod and concept for the new version, but it would be a rewrite. Not a port. I’m going to attempt porting the core mod nucleus to 1.14.2 and we shall see. I don’t really intend to do 1.12 honestly at this point as I feel well late to the game and would rather focus on new stuff, it is neotech and made to be a new tech mod so makes sense to aim at 1.14
