### ISSUE TITLE
[Pickaxe] Area Upgrade doesn' work on everything

### ISSUE THREAD

**Issue by Steeph** [TeamBR-Modding/NeoTech#434]
Neotech : 1.10.2-3.3.0
Modpack : Age of Engineering

The area upgrade doesn't work on any Chisels block so far. For instance, when i mine Limestone, marble. It doesn't work on some ore like osmium from Mekanism.

The area effect doesn't get triggered if i mine this very block, and if i mine the stone block next to it, it won't get mine.

And some block doesn't recognize it the neotech pickaxe as pickaxe (i forgot the name of the block sorry)

As you can see on the picture, the area is triggered for the stone and tin ore, but not the marble on the left.

![xbesk8t](https://user-images.githubusercontent.com/15182080/34360885-5347bf9e-ea65-11e7-9f6e-90a4124c65bc.png)

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
