### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by boop5** [TeamBR-Modding/NeoTech#435]
Removing items from the back with an exu2 transfer node. After a couple of seconds it's crashing every time. playing on [Age of Engineering 1.1.2](https://minecraft.curseforge.com/projects/age-of-engineering/files/2503175)

What Version of NeoTech are you using:
1.10.2-3.3.0
Please Pastebin.com the crash Report and put link here:
[Log](https://gist.githubusercontent.com/anonymous/c94d68712bb4a5394e360a6f2fb2fec0/raw/ab7d06b228cac0f4ac1533e11b66b8e2ec7f3b7c/gistfile1.txt)

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
