### ISSUE TITLE
Centrifuge ignoring network card sides

### ISSUE THREAD

**Issue by Nalebaen** [TeamBR-Modding/NeoTech#437]
What Version of NeoTech are you using: 1.10.2-3.3.0

The centrifuge will output lava to an EnderIO pressurize pipe on a red side even when set to yellow on another side. Also, it becomes VERY slow when there are no lava at all. An octa processor was also used.

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
