### ISSUE TITLE
Electric crusher not using its energy 

### ISSUE THREAD

**Issue by coolgaza16** [TeamBR-Modding/NeoTech#44]
Currently as long as you put a little power in the crusher it operates but doesn't use any power so it's processing ores for free. Surprisingly this only happens with the crusher as the furnace is working fine. Also I noticed the second output slot of the crusher is not being used not sure if this is a bug or planed expansion on the gui. P.s. Using version 2.05 on ftb unstable.

**Comment by Dyonovan** [comment]
Fixing the rf issue as we speak. 

The second slot will be used once I get the upgrade system added.It will be a % change for secondary output

**Comment by coolgaza16** [comment]
Great thanks for the update

**Comment by Dyonovan** [comment]
Ok fixed in in release 2.2.4 (not released yet but should be later today)

Keep the bugs coming :)
