### ISSUE TITLE
Hopper placed on the bottom of a grinder sucks from all slots [1.8.9]

### ISSUE THREAD

**Issue by BBoldt** [TeamBR-Modding/NeoTech#46]
Would be nice if it only sucked from the bottom slots, so you can hopper into a furnace.

**Comment by pauljoda** [comment]
No problem

**Comment by pauljoda** [comment]
Oh you meant the grinder, I was thinking the crusher. This is intentional as I don't want you to be able to pull outputs out of it. If you try, it will pull the inputs. This is made to be manual and early game, not automated
