### ISSUE TITLE
[1.8.9] Furnace Generator not filling internal buffer

### ISSUE THREAD

**Issue by SwordKorn20** [TeamBR-Modding/NeoTech#48]
Using the Furnace Generator to power machines and transmitting that power through the FluxedRedstone conduits.

The internal buffer for the generator didn't fill once connected to a electric furance via cables from Fluxed Redstone. Not sure why.

**Comment by Dyonovan** [comment]
Sounds like an issue with the fluxedredstone conduits. Try with our pipes and see if it still happens

**Comment by SwordKorn20** [comment]
Seems that the FluxedRedstone conduits have internal buffers but no way of knowing how much is stored in their network. Mustn't be your mod. Sorry to have bothered you.

**Comment by Dyonovan** [comment]
No worries. If there is anything I can do to help figure it out, just let me know. Would be happy to work with the other mod author if needed.

**Comment by SwordKorn20** [comment]
I don't think it was an intended bug on either end. I think the other mod author intended his power network to charge and discharge the power to surrounding blocks on the network if their buffer empties.

What might be nice though is some form of network monitor... I'll mess with my OpenComputers computer and see if I can make a visual display of the network.
