### ISSUE TITLE
Electric Miner - Starts then Stops

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#5]
You have a serious problem with it. There are no client or server console messages either. You can scan and it returns the number of blocks it is gonna do. And after you successfully power it, when you hit start, it'll go for a tiny bit and then sounds like it is hitting gravel and it stops. Also, how to get stuff out of it? It doesn't appear to send anything through the item pipes.

See the following unlisted video for details: https://youtu.be/x_95rwor8z8?t=5m17s

**Comment by Dyonovan** [comment]
I replied to the comment on the forums. you need to place a chest on top of the miner. then you can pipes things out of the chest. Its a known issue as the pipes are going to be redone to fix it.

**Comment by kreezxil** [comment]
Cool

-----Original Message-----
