### ISSUE TITLE
Electric grinder not accepting colored wool to be turned to string?

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamBR-Modding/NeoTech#51]
Is this intended?

**Comment by Dyonovan** [comment]
Hrm wierd. Thought I accounted for that. Can you pastebin your config/Neotech/Registries/crusherRecipes.json file so i can take a look at it.

**Comment by Dyonovan** [comment]
Never mind. For some reason Wool doesnt have an oredict in forge.
