### ISSUE TITLE
[1.8.9] Missing filled motherboad after rotating the facing of a machine

### ISSUE THREAD

**Issue by GWYOG** [TeamBR-Modding/NeoTech#52]
Everytime I rotate the facing of a machine by using a wrench, the filled motherboard in the machine will disappear.
Using NeoTech-1.8.9-2.3.0

**Comment by Dyonovan** [comment]
https://github.com/TeamBR-Modding/NeoTech/commit/06d3884a3119538d11e50fa9f405ec898bafedb5
