### ISSUE TITLE
[1.8.9] Thermal binder's consumption timing of the upgrades needs to be changed

### ISSUE THREAD

**Issue by GWYOG** [TeamBR-Modding/NeoTech#53]
Actually, these upgrades will be consumed only after the countdown of some ticks has finished.
However, I can put in or pull out the upgrades in the inventory of thermal binder when the countdown is going down.
Thus, I can put 1 upgrade in the slot, press the 'start' button, and then put the other upgrades in. In this  way, the countdown is merely about 400 ticks rather than 7000+ ticks.
I assume that this is not a feature you added.
Using NeoTech-1.8.9-2.3.0

**Comment by Dyonovan** [comment]
Def not a feature :P

**Comment by Dyonovan** [comment]
Fixed for next release
