### ISSUE TITLE
grinder not working 1.8.9

### ISSUE THREAD

**Issue by coolgaza16** [TeamBR-Modding/NeoTech#57]
i have placed a stack of iron ore in the grinder and tried jumping on every plate available to me to try to get the grinder working but still not grinding any ore i placed the plate on top and next to the grinder too

**Comment by Dyonovan** [comment]
Are you using the AutoTech mod? There is an issue with that mod that for some reason removes fall damage.

**Comment by Dyonovan** [comment]
Never heard back. Closing as an issue with another mod
