### ISSUE TITLE
(feature request) upgrades for machines or upgraded machines

### ISSUE THREAD

**Issue by NarigudoBR** [TeamBR-Modding/NeoTech#58]
I tested the furnace that this mod have and I'm quite a little disappointed , because it rans in a normal speed furnace(boring!) and did not have any space for upgrades or IO config. Sorry for any inconvenience

**Comment by Dyonovan** [comment]
This is already in game for the most part. Right click the machine with our wrench. More documentation coming soon.

https://github.com/TeamBR-Modding/NeoTech/wiki
