### ISSUE TITLE
Placed fluid tanks seem to vanish when you break them.

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamBR-Modding/NeoTech#59]
It seems old fluid tanks that you place and leave and later on when you come back they seem to completely vanish when you break them.

Only seem to happen to tanks that been in the world a while.

**Comment by Dyonovan** [comment]
What version of NeoTech are you using? We had some earlier issues that we solved but not sure if they are the same.

**Comment by Kazzamkablam** [comment]
Was latest before today's update. I'll reply here if it still keeps happening.

**Comment by Kazzamkablam** [comment]
seems to work now, doesn't vanish when I break it anymore.
