### ISSUE TITLE
NeoTech FPS drop problem produced by using mouse buttons

### ISSUE THREAD

**Issue by Simuciokas** [TeamBR-Modding/NeoTech#6]
Hello,

I have tried to use your mod in a private modpack, and it seems that your mod produces lag by using any mouse button.
For ex.:
Once I press the right click button and hold it also move the mouse around the blocks i'm looking at, it starts to lag.
Same goes for breaking blocks with the left mouse button, once I start breaking blocks I start to lag.
For now, I have tested each mod in my modpack to see which mod kept causing this lag, and I haven't tested your mod standalone with forge for now, currently I used these mods in my server(Singleplayer):
BattleTowers-1.8
Chameleon-1.8-0.1.0
CodeChickenCore-1.8-1.0.5.34-universal
NeoTech-1.8-1.6
NotEnoughItems-1.8-1.0.5.82-universal
OptiFine_1.8.0_HD_U_D3
Paintball-1.8.0v2
Pixelmon-1.8-4.0.3-universal
Ruins-1.8
StorageDrawers-1.8-2.0.2
UpdateCheckerMod-1.8
Here's the full log of my client:
http://www.mediafire.com/download/nxo3nrtbmuxssnv/fml-client-latest.log
at [16:58:51] I joined the server (I think, btw, I am bad at log checking ;D)

And the forge version I am using is 1.8-11.14.1.1412
Thank you in advance if you manage to fix it and thank you for making an awesome mod!

-Simuciokas

**Comment by mjuksel** [comment]
Yeah, it does the same for me.
Even when it was JATM it happened to me as well.
Tested it on a clean 1.8 with Forge 11.14.3.1493 (currently) and before (as JATM) with older forge versions obviously.

**Comment by Dyonovan** [comment]
Should be fixed in rewrite. Initial release later today
