### ISSUE TITLE
NoSuchFieldError: rock

### ISSUE THREAD

**Issue by bubblesayoyo** [TeamBR-Modding/NeoTech#60]
I've tried loading up 2.3.1-dev with the 2.2.6 Bookshelf against Forge 22, 24, and 29 and no such luck:

[crash-2016-02-02_11.58.12-client.txt](https://github.com/TeamBR-Modding/NeoTech/files/114311/crash-2016-02-02_11.58.12-client.txt)

**Comment by Dyonovan** [comment]
The -dev build is only for using in a dev environment. Just use the normal jar.

http://minecraft.curseforge.com/projects/neotech/files/2279569/download
