### ISSUE TITLE
Energy interface pipes working as intended?

### ISSUE THREAD

**Issue by Kazzamkablam** [TeamBR-Modding/NeoTech#61]
When I have two power outputting blocks next to energy interface on NeoTech-1.8.9-2.3.0 it only takes energy from one of the blocks and ignores the other? Even with them outputting way less than the interface can handle.

**Comment by Dyonovan** [comment]
Pretty sure we fixed this in ver 2.3.1. Give it a try (you will need to update bookshelf as well) and let us know. Going to close but if it still happens with new version go ahead and reopen.

Dont forget to delete the NeoTech config directory when updating, as we have changed a lot of stuff.

**Comment by Kazzamkablam** [comment]
Nope, happens with newest version too. Basically what I did was hook them to actually additions solar panels and it went all weird. Made mistake with the version numbering, Guess I shoudn't write bug reports when tired.

**Comment by Dyonovan** [comment]
KK. Will look into it. Thanks for the report

**Comment by pauljoda** [comment]
I see the behavior you are talking about. It isn't really something simple to fix. It is part of the round robin algorithm. It is stuck in a state of always moving to the next sink, the second output returns false as it runs out of space in the sink list. If you change the mode from round robin, use one more input, or add one more sink the issue will be solved. I'll keep an eye on it and see what I can do about it at a later time

**Comment by pauljoda** [comment]
Fixed in next update
