### ISSUE TITLE
Furnace Generator not using fuel

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#62]
Hi,

I am using Version 2.3.1 of your mod and the furnace generator produces RF as it should, but does not use up any fuel. Supplying it with one piece of Coal/Charcoal lets it run forever.
The Upgrades increase the output as they should. 
The Liquid Generator uses up fuel as it should

Best regards!

**Comment by pauljoda** [comment]
Wow I can't believe I missed that. We just rewrote all machines and I knew I'd miss something

**Comment by pauljoda** [comment]
Fix for next release 3057475a52484033f93ab20ac9ad137535dcf1de
