### ISSUE TITLE
items spitting 

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#65]
updated to 2.3.2 and its better than it was but it keeps spitting stuff on the floor 

set up box of coal piped it to furnace its 3 pipe blocks from chest every time it drops to 63 coal the cest sends one then 2 then 3 then the first one hits the furnace this stops the flow of coal but the 2 pieces in the pies pop out at the furnace 

if i add a third item interface the items just bounce between the chests but when the furnace calls for more coal it still drops the 2 coal even tho there are 15 or so blocks bouncing between the chests constantly

can it be set to let the item hit before another is sent or a way to have it read how many it needs to send ? the longer the pipe the more it sends and the more i have on the floor (seems to do the same with all the machines i have tried so far )

and thanks for the great mod just a few things to make it a grand mod

**Comment by pauljoda** [comment]
Hmm. It should be handling that by remembering how much to send. The switch to IItemHandlers maybe have introduced this issue again. I'll look into it for sure

**Comment by pauljoda** [comment]
You are correct, that issue is back. Let me see what I can do to sort this out
