### ISSUE TITLE
Flickering tree

### ISSUE THREAD

**Issue by Umiyaki** [TeamBR-Modding/NeoTech#66]
Minecraft  1.8.9, last Optifine, last forge. (AMD R9 270, last driver, Win 10, last Java version)
When I used pipe (items moved in pipe), trees leaves to be jittery and unstable and shaky looking. Only restart minecraft client repairs this bug. Enable/disable Optifine doesn't help.

edit: Problem is conflicts with setting MIPMAP LEVELS (Option>Video setting>Quality>). Setting 1 or 4 = "flickering", disable MIPMAP LEVELS = "no flickering". But the disable degrades game graphics quality.
thx Umi

**Comment by pauljoda** [comment]
An interesting issue, but I'm going to avoid conflicts that involve Optifine. Even if you say disabling it helps they do a lot of direct gl stack manipulation while we have moved away from even accessing the stack. I don't see how this could be related to us but if you find more information linking it to our mod please let us know
