### ISSUE TITLE
[1.8.9-2.3.1] Duel crafter voids items on break

### ISSUE THREAD

**Issue by Buuz135** [TeamBR-Modding/NeoTech#67]
As the duel crafter stores items, when you break it, the item void.

**Comment by pauljoda** [comment]
I know exactly what the issue is. The switch to IItemHandlers caused a few side effects. I thought I caught all these but it seems I missed one

**Comment by pauljoda** [comment]
Fixed in new version of bookshelf  https://github.com/TeamBR-Modding/Bookshelf/commit/0be5b01a18d1a9afb45f10aeaeb0250cc3fd17b1
