### ISSUE TITLE
[1.8.9-2.3.1]Dimensional Storage increases insert amount

### ISSUE THREAD

**Issue by Buuz135** [TeamBR-Modding/NeoTech#68]
Upon inserting items over 64*64 items the item count increases rapidly even the item insertion rate is the same and it increases by itself without inserting. When it reaches X amount it resets

![](https://i.gyazo.com/d5809a142739debb03b5d60c40cc713f.gif)

![](https://i.gyazo.com/17557dceaf260d626074c6c3b6ed9923.gif)

**Comment by pauljoda** [comment]
@Dyonovan
