### ISSUE TITLE
Pipes try and insert (Dim Storage) More items then can handle. Exess is just dropped on ground

### ISSUE THREAD

**Issue by Dyonovan** [TeamBR-Modding/NeoTech#71]

**Comment by pauljoda** [comment]
Make absolutely sure your code is saying it won't accept any even when simulating. It sounds like it's returning some stack saying it took some and my pipes are sending things in

**Comment by Dyonovan** [comment]
The storage is returning the stack minus what I can take, but the pipes are still trying to send the full stack not the partial stack that it can accept.

**Comment by pauljoda** [comment]
Can you debug on will accept resource for item pipes and see what is around
when it returns true? If not I'll look at it tomorrow

**Comment by ghost** [comment]
to add additional information to this, the sending does stop, but the bounce back behaviour doesn't seem to be functioning correctly, transferring from a chest to a pneumaticraft pressure chamber allows the first one in, but the pipe drops any that are still in transit when the inventory closes

**Comment by pauljoda** [comment]
That has been fixed in the next release

**Comment by ghost** [comment]
is it available somewhere for public consumption?

**Comment by pauljoda** [comment]
You can build our source or access Jenkins. Click the build passing icon at
the main git page
