### ISSUE TITLE
Pipes cause flickering in distant trees

### ISSUE THREAD

**Issue by mille449** [TeamBR-Modding/NeoTech#73]
Place a pipe.  Look at a tree a few chunks away.  Lots of flickering.

**Comment by mille449** [comment]
Also the flickering seems to persist after breaking the pipe until the client is restarted.

**Comment by pauljoda** [comment]
Which pipes? All types or just one type

**Comment by mille449** [comment]
All types.

**Comment by Umiyaki** [comment]
to pauljoda: Hi, this problem I reported 3 days ego. (Flickering tree #66). It was closed without resolving. :-/
Problem is trasport items in pipes. Lava and energy balls are OK. Animamtion items in pipes disable and enable MIPMAP Level = flickering of distant objects. This is most visible in the trees.
