### ISSUE TITLE
storage crates acting wierd after storing items over 4000

### ISSUE THREAD

**Issue by SDUBZ** [TeamBR-Modding/NeoTech#74]
the diamonds i had in a crate went over 4000 and didnt tell me it was full then gave this
![2016-02-07_01 53 56](https://cloud.githubusercontent.com/assets/14084377/12867316/5ab9c808-cd3e-11e5-938a-067ffda58040.png)

just thought id let you know before it affects too many people

**Comment by Dyonovan** [comment]
Already fixed for next release which should be late today.

Duplicate #68
