### ISSUE TITLE
Description in curseforge is incorrect.

### ISSUE THREAD

**Issue by noisyboi** [TeamBR-Modding/NeoTech#75]
I just wanted to notify that the : 
com.dyonovan.neotech.managers.NeotechWorldGenerator
  Is incorrect, it should be 
com.dyonovan.neotech.world.NeotechWorldGenerator

I had hell not realizing why it just wouldn't regenerate the ore until i figured maybe it's this that is wrong.

Have a great day sir. :P

**Comment by Dyonovan** [comment]
Woops. We refactored a bunch of files. Forgot about that. Will switch it right now. 

Thanks for the heads up
