### ISSUE TITLE
items on the floor

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#81]
so its worse in 2.3.3 than it was in 2.3.2

now once the machine requests an item the chest dumps everthing on the floor there is no reason for it to send more than 1

in 2.3.2 it send items till the machine got one then it stoped so you had just a little on the floor 

in 2.3.3 i have an entire chest of coal on the floor and the chest is empty anything that goes in is automatically pumped out

**Comment by Dyonovan** [comment]
Duplicate #71
