### ISSUE TITLE
Client Crash (Render)

### ISSUE THREAD

**Issue by JoeSchmo2840** [TeamBR-Modding/NeoTech#82]
Another player placed an Electric Crusher, I broke said crusher while in creative (dont know if that matters) and we both crashed client side. 

http://pastebin.com/XAeNWH4S

**Comment by JoeSchmo2840** [comment]
Also happens with the Electric Furnace

**Comment by JoeSchmo2840** [comment]
Happens whether or not you are in creative mode

**Comment by Dyonovan** [comment]
I think I know whats happening. Will have it fixed for next release.

**Comment by JoeSchmo2840** [comment]
Thanks Dyonovan, I really like where neotech is heading. I run a dedicated testing server for SpongePowered so we are always looking for things to break.

**Comment by pauljoda** [comment]
Yeah I think we fixed this issues. I'll put double redundant checks in to be safe
