### ISSUE TITLE
Add Support for Power Advantage API

### ISSUE THREAD

**Issue by DrPlantabyte** [TeamBR-Modding/NeoTech#9]
Hi TeamBR,

I'm DrCyano, author of the [Power Advantage API](https://github.com/cyanobacterium/PowerAdvantageAPI), and I want to add compatibility between the power systems of your mod and Power Advantage.

There are three ways we can do this. Method one would be for me to create a converter block that accepts Power Advantage energy types and outputs the energy type (RF?) used in your mod. Method two is that you could use the Power Advantage API yourself and convert your base machine class to be a simple power consumer (Power Advantage API can do the rest). Method three is that I could try to do the conversion for you and hand you a pull request, but then I'd need to know a little more about how your mod works under-the-hood and I might make changes that you don't like to facilitate compatibility.

Let me know what you prefer,
-DrCyano

**Comment by DrPlantabyte** [comment]
I've updated Power Advantage to have a light-weight API for registering your machines as acceptors of Power Advantage power types without rewriting any of your Block or TileEntity classes. You can see an example here: [https://github.com/cyanobacterium/PowerAdvantageAPI/releases/tag/v1.2.2](https://github.com/cyanobacterium/PowerAdvantageAPI/releases/tag/v1.2.2)

**Comment by Dyonovan** [comment]
Ive picked up working on NeoTech again and will add the support

**Comment by Dyonovan** [comment]
Working on this as we speak. Should have an initial release later today

**Comment by Dyonovan** [comment]
Added. Not sure if its working as I cant seem to find any conduits

**Comment by DrPlantabyte** [comment]
I can confirm that it is working. Good job and thank you!
