### ISSUE TITLE
Only one item move.

### ISSUE THREAD

**Issue by Umiyaki** [TeamBR-Modding/NeoTech#90]
https://www.youtube.com/watch?v=U6Iai4m7Yw0

forge-1.8.9-11.15.1.1732
NeoTech-1.8.9-2.3.4
Bookshelf-1.8.9-2.2.9

**Comment by pauljoda** [comment]
Ah you've found my struggle. While trying to figure out why IItemHandlers have made life difficult the item pipes no longer store the amount they are expecting. This means they will only accept new items when they aren't waiting for something. In the meantime while I try to figure this out, pop some acceleration pipes down and it should make things easier. Sorry for the issue. I'm going to close this for the moment as it is related to a larger issue. By the way, thanks for the video, makes understanding issues loads easier
