### ISSUE TITLE
Furnace Generator continues to burn fuel when energy buffer is full

### ISSUE THREAD

**Issue by rckymtnrfc** [TeamBR-Modding/NeoTech#91]
I have a Furnace Generator that continues to burn coal even when it's internal buffer and the 2 attached machines are full.

Running Bookshelf-1.8.9-2.2.8 and NeoTech-1.8.9-2.3.3.

Thanks

**Comment by pauljoda** [comment]
Does it just finish what it had started burning or continue to burn a new piece of coal?

**Comment by rchiav** [comment]
I've seen the same issue.. it continues to burn coal after the buffer is full and after it finished burning the piece where the buffer was full. I didn't have a chance to do any more testing to see if it only happened in certain conditions though.
