### ISSUE TITLE
Strange interaction with furnace generator when holding the wrench

### ISSUE THREAD

**Issue by rchiav** [TeamBR-Modding/NeoTech#92]
The way to reproduce this issue is to have the wrench selected and open the interface for the furnace generator. Once you do that, try and either put coal into the generator or take coal out of the generator. I wasn't able to grab the coal from my hot bar or from the generator. If I closed the interface and selected another hot bar location, I was able to either add or remove coal. I don't know if this is only the furnace generator or if other machines have the same issue.

**Comment by pauljoda** [comment]
I know exactly what is going on here. Let me have a look into it
