### ISSUE TITLE
Issue when applying item interface pipe to Quantum Storage Unit (DSU Style)

### ISSUE THREAD

**Issue by BrewingCoder** [TeamBR-Modding/NeoTech#94]
Buildcraft pipes work.  NeoTech crashes the server when an item pipe is added.  Log Attached

[latest.zip](https://github.com/TeamBR-Modding/NeoTech/files/124232/latest.zip)

BookShelf Ver:  2.2.9
Neo Ver:  2.3.9

Forge Ver: 11.15.1.1736

**Comment by BrewingCoder** [comment]
Here's the error on subsequent restarts of the server
[latest.zip](https://github.com/TeamBR-Modding/NeoTech/files/124234/latest.zip)

**Comment by pauljoda** [comment]
If you could please provide the crash log, this is the console log and doesn't provide me with enough information

**Comment by BrewingCoder** [comment]
[crash-2016-02-10_00.42.13-server.txt.zip](https://github.com/TeamBR-Modding/NeoTech/files/125271/crash-2016-02-10_00.42.13-server.txt.zip)

**Comment by pauljoda** [comment]
This issue is fixed in the next release
