### ISSUE TITLE
Expansion upgrade doesnt work on item interface pipes

### ISSUE THREAD

**Issue by ghost** [TeamBR-Modding/NeoTech#95]
Specifically the round-robin setting. The pipe will still act as if it's set to "First available"

Using Neotech v2.3.3 and Bookshelf v2.2.8 on the Unstable modpack

**Comment by pauljoda** [comment]
Yes this was an issue I have been dealing with. I believe I have the solution and from what I've tested it all seems to work. There are a couple more things I'll be watching but the next release should fix this issue
