### ISSUE TITLE
Can't add coal to Furnace Generator with coal in it.

### ISSUE THREAD

**Issue by rckymtnrfc** [TeamBR-Modding/NeoTech#97]
I just tried to add some more coal to my Furnace Generator that had a few pieces in it.  I couldn't add them.  I had to remove the existing pieces, combine with my partial stack and then add that to the generator.  Clicking in a single piece doesn't seem to work either.

Not a major problem but just thought you'd want to know.

Thanks

**Comment by pauljoda** [comment]
That is interesting. Shift click works but normal drop clicks don't. I'll have a look. Thanks for the info
