### ISSUE TITLE
Inputs and Outputs

### ISSUE THREAD

**Issue by Darktotaled** [TeamBR-Modding/NeoTech#98]
I've downloaded the new version( 2.3.4) and i've found something really annoying.

http://prntscr.com/a1pcfq

this was working on the 2.3.2 version btw.

from right to the left i got a crusher, a item pipe and a furnace. I've set the inputs and outputs and the pipe just doesnt pull the items from the crusher. there is no redstone signal nearby and tried both blacklist and whitelist in the pipe. Nothing worked. The pipe under the furnace however, pulls items normally.

EDIT: Was messing with the sides of the furnace and made the pipe work like this:  http://prntscr.com/a1puay

Buildcraft pipes doesnt recognize the sides of the machine as if it was a normal block. Tried to put a buildcraft wooden pipe in all the sides and it didnt conect. Only interface pipes and Buildcraft energy and fluid pipes are working with the machines.

Also, is there a place where i can send sugestions about the mod?

**Comment by Dyonovan** [comment]
I am in the midst of pushing an update to curse now. Let me know if this fixes the issue.

Also, feel free to put suggestions here as well.
